### ISSUE TITLE
Unable to apply apparmor profile - on AlmaLinux.

### ISSUE THREAD

**Issue by YuriyTigiev** [docker/cli#4030] opened 2023-02-14 17:46 UTC
### Description

Hello, 

The full information about issue below. As I know an AppArmor is for Ubuntu OS, and SeLinux is for AlmaLinux. 
The current docker version is not compaitable with AlmaLinux. 

```
[ytigiev@screener ~]$ uname -a
Linux screener.market 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[ytigiev@screener ~]$ cat /etc/*-release
AlmaLinux release 8.7 (Stone Smilodon)
AlmaLinux release 8.7 (Stone Smilodon)
NAME="AlmaLinux"
VERSION="8.7 (Stone Smilodon)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.7 (Stone Smilodon)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
AlmaLinux release 8.7 (Stone Smilodon)
AlmaLinux release 8.7 (Stone Smilodon)
[ytigiev@screener ~]$ docker -v
Docker version 23.0.1, build a5ee5b1
[ytigiev@screener ~]$ docker run hello-world
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: : apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown.
ERRO[0000] error waiting for container:                 
```

### Reproduce

docker run hello-world

### Expected behavior

Run docker Hello World

### docker version

```bash
[ytigiev@screener ~]$ docker version 
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:47 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.2.3
    Path:     /home/ytigiev/.docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 23.0.1
 Storage Driver: fuse-overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-46-generic
 Operating System: AlmaLinux 8.7 (Stone Smilodon)
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 9.313GiB
 Name: screener.market
 ID: YI6G:EDNA:AYEV:ZKRF:FIGF:H7QS:7YQI:XZBC:ASCT:2HUE:KMUG:HZT5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2023-02-14 17:56
This looks to be a duplicate of https://github.com/moby/moby/issues/44970

This error may indicate that you have a kernel / host configured with AppArmor enabled, but the `apparmor` package (which includes `apparmor_parser`) is missing. To fix that;

- install the `apparmor` package
- restart the docker service

I'll close this ticket in favour of https://github.com/moby/moby/issues/44970, which is tracking some of the remaining work needed in containerd (but subscribe to that ticket to get informed on updates, and that ticket may provide additional information)

**Closed by thaJeztah** 2023-02-14 17:56 UTC
Labels: kind/bug, status/0-triage, version/23.0

**Comment by YuriyTigiev** [comment] 2023-02-14 18:02
This is not the same issue. Do you realy know how to install the AppArmor on the AlmaLinux (CentOS)? Is it theoretical possible? If yes, can you share a resource of instructions how to install the AppArmor on Rocky Linux, AlmaLinux, RedHat?

https://eternalcenter.com/the-difference-between-selinux-and-apparmor/

**Comment by thaJeztah** [comment] 2023-02-14 18:17
Ah, you're right on the "install apparmor" part; has my wires crossed, as there's probably no package for this on AlmaLinux.

The underlying issue is very likely still the same though. How was docker installed? Was this using the RPM packages, or using static binaries?

Could you check the output of (the first two) of the commands I commented in https://github.com/moby/moby/issues/44970#issuecomment-1425846578 ? Because I'm curious why the AppArmor code (either in the engine or containerd) would be triggered on a kernel without AppArmor support

**Comment by YuriyTigiev** [comment] 2023-02-14 18:22
The previous version of docker worked on the same server a few month without any issues.

**Comment by thaJeztah** [comment] 2023-02-14 20:41
I had a quick check on a standard AlmaLinux install;

```
# ls /sys/kernel/security/apparmor
ls: cannot access '/sys/kernel/security/apparmor': No such file or directory
# cat /sys/module/apparmor/parameters/enabled
cat: /sys/module/apparmor/parameters/enabled: No such file or directory

# uname -a
Linux almalinux-s-1vcpu-1gb-ams3-01 5.14.0-70.22.1.el9_0.x86_64 #1 SMP PREEMPT Tue Aug 9 11:45:52 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Looks like you're running AlmaLinux on a non-standard kernel; was this a kernel you built yourself, or is this somewhere on a hosted environment? (As I normally wouldn't expect AppArmor to be enabled on an AlmaLinux distro).

The reason for this failure was a regression in containerd (more specifically, in library code used from containerd). We applied a patch in Docker 23.0.1 to partially work around this issue, but additional changes are still needed from the containerd code. Patches for that were accepted by the containerd maintainers, but not yet released.

> The previous version of docker worked on the same server a few month without any issues.

I should add to that that the previous behavior of the docker engine was not correct, as it silently ignored the missing AppArmor dependencies, resulting in containers not getting AppArmor protection in setups where this was expected to be applied. Future versions of Docker Engine may produce an error in this situation, but will provide a configuration option for situations where the user wants to explicitly opt-out of AppArmor protection on kernels with AppArmor enabled.

**Comment by YuriyTigiev** [comment] 2023-02-15 16:36
Might this information will helpful - LXD servers use the underlying hosts kernel - which is running Ubuntu.

**Comment by YuriyTigiev** [comment] 2023-02-25 18:11
I have installed the latest version of docker 23.0.1 but I still getting the error apparmor 
Should I wait a new version of docker ?

```

[ytigiev@screener screener.market]$ sudo dnf remove docker-ce docker-ce-cli containerd.io docker-compose-plugin
Dependencies resolved.
===============================================================================================================================================================
 Package                                  Architecture          Version                                                 Repository                        Size
===============================================================================================================================================================
Removing:
 containerd.io                            x86_64                1.6.18-3.1.el8                                          @docker-ce-stable                113 M
 docker-ce                                x86_64                3:23.0.1-1.el8                                          @docker-ce-stable                 94 M
 docker-ce-cli                            x86_64                1:23.0.1-1.el8                                          @docker-ce-stable                 28 M
 docker-compose-plugin                    x86_64                2.16.0-1.el8                                            @docker-ce-stable                 45 M
Removing unused dependencies:
 container-selinux                        noarch                2:2.189.0-1.module_el8.7.0+3407+95aa0ca9                @appstream                        57 k
 docker-buildx-plugin                     x86_64                0.10.2-1.el8                                            @docker-ce-stable                 53 M
 docker-ce-rootless-extras                x86_64                23.0.1-1.el8                                            @docker-ce-stable                 15 M
 docker-scan-plugin                       x86_64                0.23.0-3.el8                                            @docker-ce-stable                 12 M
 fuse-common                              x86_64                3.3.0-16.el8                                            @baseos                          5.1 k
 fuse-overlayfs                           x86_64                1.9-1.module_el8.7.0+3407+95aa0ca9                      @appstream                       145 k
 fuse3                                    x86_64                3.3.0-16.el8                                            @baseos                          100 k
 fuse3-libs                               x86_64                3.3.0-16.el8                                            @baseos                          274 k
 libcgroup                                x86_64                0.41-19.el8                                             @baseos                          136 k
 libslirp                                 x86_64                4.4.0-1.module_el8.7.0+3407+95aa0ca9                    @appstream                       134 k
 slirp4netns                              x86_64                1.2.0-2.module_el8.7.0+3407+95aa0ca9                    @appstream                       103 k

Transaction Summary
===============================================================================================================================================================
Remove  15 Packages

Freed space: 362 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                       1/1 
  Running scriptlet: docker-ce-3:23.0.1-1.el8.x86_64                                                                                                       1/1 
  Running scriptlet: docker-ce-3:23.0.1-1.el8.x86_64                                                                                                      1/15 
  Erasing          : docker-ce-3:23.0.1-1.el8.x86_64                                                                                                      1/15 
  Running scriptlet: docker-ce-3:23.0.1-1.el8.x86_64                                                                                                      1/15 
  Erasing          : docker-ce-cli-1:23.0.1-1.el8.x86_64                                                                                                  2/15 
  Running scriptlet: docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                        3/15 
  Erasing          : docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                        3/15 
  Running scriptlet: docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                        3/15 
  Running scriptlet: containerd.io-1.6.18-3.1.el8.x86_64                                                                                                  4/15 
  Erasing          : containerd.io-1.6.18-3.1.el8.x86_64                                                                                                  4/15 
  Running scriptlet: containerd.io-1.6.18-3.1.el8.x86_64                                                                                                  4/15 
  Erasing          : container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                    5/15 
  Running scriptlet: container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                    5/15 
  Running scriptlet: docker-buildx-plugin-0.10.2-1.el8.x86_64                                                                                             6/15 
  Erasing          : docker-buildx-plugin-0.10.2-1.el8.x86_64                                                                                             6/15 
  Running scriptlet: docker-buildx-plugin-0.10.2-1.el8.x86_64                                                                                             6/15 
  Running scriptlet: docker-compose-plugin-2.16.0-1.el8.x86_64                                                                                            7/15 
  Erasing          : docker-compose-plugin-2.16.0-1.el8.x86_64                                                                                            7/15 
  Running scriptlet: docker-compose-plugin-2.16.0-1.el8.x86_64                                                                                            7/15 
  Running scriptlet: docker-scan-plugin-0.23.0-3.el8.x86_64                                                                                               8/15 
  Erasing          : docker-scan-plugin-0.23.0-3.el8.x86_64                                                                                               8/15 
  Running scriptlet: docker-scan-plugin-0.23.0-3.el8.x86_64                                                                                               8/15 
  Erasing          : fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                             9/15 
  Erasing          : fuse3-3.3.0-16.el8.x86_64                                                                                                           10/15 
  Erasing          : slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64                                                                             11/15 
  Erasing          : fuse-common-3.3.0-16.el8.x86_64                                                                                                     12/15 
  Erasing          : libslirp-4.4.0-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                                13/15 
  Erasing          : fuse3-libs-3.3.0-16.el8.x86_64                                                                                                      14/15 
  Running scriptlet: fuse3-libs-3.3.0-16.el8.x86_64                                                                                                      14/15 
  Erasing          : libcgroup-0.41-19.el8.x86_64                                                                                                        15/15 
  Running scriptlet: libcgroup-0.41-19.el8.x86_64                                                                                                        15/15 
  Verifying        : container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                    1/15 
  Verifying        : containerd.io-1.6.18-3.1.el8.x86_64                                                                                                  2/15 
  Verifying        : docker-buildx-plugin-0.10.2-1.el8.x86_64                                                                                             3/15 
  Verifying        : docker-ce-3:23.0.1-1.el8.x86_64                                                                                                      4/15 
  Verifying        : docker-ce-cli-1:23.0.1-1.el8.x86_64                                                                                                  5/15 
  Verifying        : docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                        6/15 
  Verifying        : docker-compose-plugin-2.16.0-1.el8.x86_64                                                                                            7/15 
  Verifying        : docker-scan-plugin-0.23.0-3.el8.x86_64                                                                                               8/15 
  Verifying        : fuse-common-3.3.0-16.el8.x86_64                                                                                                      9/15 
  Verifying        : fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                            10/15 
  Verifying        : fuse3-3.3.0-16.el8.x86_64                                                                                                           11/15 
  Verifying        : fuse3-libs-3.3.0-16.el8.x86_64                                                                                                      12/15 
  Verifying        : libcgroup-0.41-19.el8.x86_64                                                                                                        13/15 
  Verifying        : libslirp-4.4.0-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                                14/15 
  Verifying        : slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64                                                                             15/15 

Removed:
  container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                  containerd.io-1.6.18-3.1.el8.x86_64                                      
  docker-buildx-plugin-0.10.2-1.el8.x86_64                                           docker-ce-3:23.0.1-1.el8.x86_64                                          
  docker-ce-cli-1:23.0.1-1.el8.x86_64                                                docker-ce-rootless-extras-23.0.1-1.el8.x86_64                            
  docker-compose-plugin-2.16.0-1.el8.x86_64                                          docker-scan-plugin-0.23.0-3.el8.x86_64                                   
  fuse-common-3.3.0-16.el8.x86_64                                                    fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64                 
  fuse3-3.3.0-16.el8.x86_64                                                          fuse3-libs-3.3.0-16.el8.x86_64                                           
  libcgroup-0.41-19.el8.x86_64                                                       libslirp-4.4.0-1.module_el8.7.0+3407+95aa0ca9.x86_64                     
  slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64                           

Complete!
[ytigiev@screener screener.market]$ sudo rm -rf /var/lib/docker
[ytigiev@screener screener.market]$ sudo rm -rf /var/lib/containerd
[ytigiev@screener screener.market]$ sudo yum remove docker-ce docker-ce-cli containerd.io docker-compose-plugin
No match for argument: docker-ce
No match for argument: docker-ce-cli
No match for argument: containerd.io
No match for argument: docker-compose-plugin
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
[ytigiev@screener screener.market]$ sudo rm -rf /var/lib/docker
[ytigiev@screener screener.market]$ sudo rm -rf /var/lib/containerd
[ytigiev@screener screener.market]$ sudo yum -y update
Last metadata expiration check: 0:07:07 ago on Sat 25 Feb 2023 05:56:28 PM UTC.
Dependencies resolved.
Nothing to do.
Complete!
[ytigiev@screener screener.market]$ sudo yum -y upgrade
Last metadata expiration check: 0:07:13 ago on Sat 25 Feb 2023 05:56:28 PM UTC.
Dependencies resolved.
Nothing to do.
Complete!
[ytigiev@screener screener.market]$ sudo yum remove docker \
>                   docker-client \
>                   docker-client-latest \
>                   docker-common \
>                   docker-latest \
>                   docker-latest-logrotate \
>                   docker-logrotate \
>                   docker-engine
No match for argument: docker
No match for argument: docker-client
No match for argument: docker-client-latest
No match for argument: docker-common
No match for argument: docker-latest
No match for argument: docker-latest-logrotate
No match for argument: docker-logrotate
No match for argument: docker-engine
No packages marked for removal.
Dependencies resolved.
Nothing to do.
Complete!
[ytigiev@screener screener.market]$ sudo yum install -y yum-utils
Last metadata expiration check: 0:07:41 ago on Sat 25 Feb 2023 05:56:28 PM UTC.
Package yum-utils-4.0.21-14.1.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[ytigiev@screener screener.market]$ sudo yum-config-manager \
>     --add-repo \
>     https://download.docker.com/linux/centos/docker-ce.repo
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
[ytigiev@screener screener.market]$ sudo yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin
Docker CE Stable - x86_64                                                                                                       49 kB/s | 3.5 kB     00:00    
Dependencies resolved.
===============================================================================================================================================================
 Package                                  Architecture          Version                                                  Repository                       Size
===============================================================================================================================================================
Installing:
 containerd.io                            x86_64                1.6.18-3.1.el8                                           docker-ce-stable                 34 M
 docker-ce                                x86_64                3:23.0.1-1.el8                                           docker-ce-stable                 23 M
 docker-ce-cli                            x86_64                1:23.0.1-1.el8                                           docker-ce-stable                7.1 M
 docker-compose-plugin                    x86_64                2.16.0-1.el8                                             docker-ce-stable                 11 M
Installing dependencies:
 container-selinux                        noarch                2:2.189.0-1.module_el8.7.0+3407+95aa0ca9                 appstream                        59 k
 docker-ce-rootless-extras                x86_64                23.0.1-1.el8                                             docker-ce-stable                4.7 M
 fuse-common                              x86_64                3.3.0-16.el8                                             baseos                           21 k
 fuse-overlayfs                           x86_64                1.9-1.module_el8.7.0+3407+95aa0ca9                       appstream                        72 k
 fuse3                                    x86_64                3.3.0-16.el8                                             baseos                           53 k
 fuse3-libs                               x86_64                3.3.0-16.el8                                             baseos                           94 k
 libcgroup                                x86_64                0.41-19.el8                                              baseos                           69 k
 libslirp                                 x86_64                4.4.0-1.module_el8.7.0+3407+95aa0ca9                     appstream                        69 k
 slirp4netns                              x86_64                1.2.0-2.module_el8.7.0+3407+95aa0ca9                     appstream                        53 k
Installing weak dependencies:
 docker-buildx-plugin                     x86_64                0.10.2-1.el8                                             docker-ce-stable                 12 M
 docker-scan-plugin                       x86_64                0.23.0-3.el8                                             docker-ce-stable                3.8 M

Transaction Summary
===============================================================================================================================================================
Install  15 Packages

Total download size: 96 M
Installed size: 362 M
Is this ok [y/N]: y
Downloading Packages:
(1/15): fuse-common-3.3.0-16.el8.x86_64.rpm                                                                                    829 kB/s |  21 kB     00:00    
(2/15): fuse3-3.3.0-16.el8.x86_64.rpm                                                                                          1.9 MB/s |  53 kB     00:00    
(3/15): fuse3-libs-3.3.0-16.el8.x86_64.rpm                                                                                     3.2 MB/s |  94 kB     00:00    
(4/15): libcgroup-0.41-19.el8.x86_64.rpm                                                                                        12 MB/s |  69 kB     00:00    
(5/15): container-selinux-2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch.rpm                                                    9.6 MB/s |  59 kB     00:00    
(6/15): fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64.rpm                                                            12 MB/s |  72 kB     00:00    
(7/15): libslirp-4.4.0-1.module_el8.7.0+3407+95aa0ca9.x86_64.rpm                                                                12 MB/s |  69 kB     00:00    
(8/15): slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64.rpm                                                             10 MB/s |  53 kB     00:00    
(9/15): docker-buildx-plugin-0.10.2-1.el8.x86_64.rpm                                                                            23 MB/s |  12 MB     00:00    
(10/15): docker-ce-cli-23.0.1-1.el8.x86_64.rpm                                                                                  25 MB/s | 7.1 MB     00:00    
(11/15): docker-ce-23.0.1-1.el8.x86_64.rpm                                                                                      22 MB/s |  23 MB     00:01    
(12/15): docker-ce-rootless-extras-23.0.1-1.el8.x86_64.rpm                                                                      14 MB/s | 4.7 MB     00:00    
(13/15): docker-scan-plugin-0.23.0-3.el8.x86_64.rpm                                                                             24 MB/s | 3.8 MB     00:00    
(14/15): containerd.io-1.6.18-3.1.el8.x86_64.rpm                                                                                22 MB/s |  34 MB     00:01    
(15/15): docker-compose-plugin-2.16.0-1.el8.x86_64.rpm                                                                          20 MB/s |  11 MB     00:00    
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                           36 MB/s |  96 MB     00:02     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                       1/1 
  Installing       : docker-scan-plugin-0.23.0-3.el8.x86_64                                                                                               1/15 
  Running scriptlet: docker-scan-plugin-0.23.0-3.el8.x86_64                                                                                               1/15 
  Installing       : docker-compose-plugin-2.16.0-1.el8.x86_64                                                                                            2/15 
  Running scriptlet: docker-compose-plugin-2.16.0-1.el8.x86_64                                                                                            2/15 
  Running scriptlet: container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                    3/15 
  Installing       : container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                    3/15 
  Running scriptlet: container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                    3/15 
  Installing       : fuse3-libs-3.3.0-16.el8.x86_64                                                                                                       4/15 
  Running scriptlet: fuse3-libs-3.3.0-16.el8.x86_64                                                                                                       4/15 
  Installing       : containerd.io-1.6.18-3.1.el8.x86_64                                                                                                  5/15 
  Running scriptlet: containerd.io-1.6.18-3.1.el8.x86_64                                                                                                  5/15 
  Installing       : docker-buildx-plugin-0.10.2-1.el8.x86_64                                                                                             6/15 
  Running scriptlet: docker-buildx-plugin-0.10.2-1.el8.x86_64                                                                                             6/15 
  Installing       : docker-ce-cli-1:23.0.1-1.el8.x86_64                                                                                                  7/15 
  Running scriptlet: docker-ce-cli-1:23.0.1-1.el8.x86_64                                                                                                  7/15 
  Installing       : libslirp-4.4.0-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                                 8/15 
  Installing       : slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64                                                                              9/15 
  Running scriptlet: libcgroup-0.41-19.el8.x86_64                                                                                                        10/15 
  Installing       : libcgroup-0.41-19.el8.x86_64                                                                                                        10/15 
  Running scriptlet: libcgroup-0.41-19.el8.x86_64                                                                                                        10/15 
  Installing       : fuse-common-3.3.0-16.el8.x86_64                                                                                                     11/15 
  Installing       : fuse3-3.3.0-16.el8.x86_64                                                                                                           12/15 
  Installing       : fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                            13/15 
  Running scriptlet: fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                            13/15 
  Installing       : docker-ce-3:23.0.1-1.el8.x86_64                                                                                                     14/15 
  Running scriptlet: docker-ce-3:23.0.1-1.el8.x86_64                                                                                                     14/15 
  Installing       : docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                       15/15 
  Running scriptlet: docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                       15/15 
  Running scriptlet: container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                   15/15 
  Running scriptlet: docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                       15/15 
  Verifying        : fuse-common-3.3.0-16.el8.x86_64                                                                                                      1/15 
  Verifying        : fuse3-3.3.0-16.el8.x86_64                                                                                                            2/15 
  Verifying        : fuse3-libs-3.3.0-16.el8.x86_64                                                                                                       3/15 
  Verifying        : libcgroup-0.41-19.el8.x86_64                                                                                                         4/15 
  Verifying        : container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                                                                    5/15 
  Verifying        : fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                             6/15 
  Verifying        : libslirp-4.4.0-1.module_el8.7.0+3407+95aa0ca9.x86_64                                                                                 7/15 
  Verifying        : slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64                                                                              8/15 
  Verifying        : containerd.io-1.6.18-3.1.el8.x86_64                                                                                                  9/15 
  Verifying        : docker-buildx-plugin-0.10.2-1.el8.x86_64                                                                                            10/15 
  Verifying        : docker-ce-3:23.0.1-1.el8.x86_64                                                                                                     11/15 
  Verifying        : docker-ce-cli-1:23.0.1-1.el8.x86_64                                                                                                 12/15 
  Verifying        : docker-ce-rootless-extras-23.0.1-1.el8.x86_64                                                                                       13/15 
  Verifying        : docker-compose-plugin-2.16.0-1.el8.x86_64                                                                                           14/15 
  Verifying        : docker-scan-plugin-0.23.0-3.el8.x86_64                                                                                              15/15 

Installed:
  container-selinux-2:2.189.0-1.module_el8.7.0+3407+95aa0ca9.noarch                  containerd.io-1.6.18-3.1.el8.x86_64                                      
  docker-buildx-plugin-0.10.2-1.el8.x86_64                                           docker-ce-3:23.0.1-1.el8.x86_64                                          
  docker-ce-cli-1:23.0.1-1.el8.x86_64                                                docker-ce-rootless-extras-23.0.1-1.el8.x86_64                            
  docker-compose-plugin-2.16.0-1.el8.x86_64                                          docker-scan-plugin-0.23.0-3.el8.x86_64                                   
  fuse-common-3.3.0-16.el8.x86_64                                                    fuse-overlayfs-1.9-1.module_el8.7.0+3407+95aa0ca9.x86_64                 
  fuse3-3.3.0-16.el8.x86_64                                                          fuse3-libs-3.3.0-16.el8.x86_64                                           
  libcgroup-0.41-19.el8.x86_64                                                       libslirp-4.4.0-1.module_el8.7.0+3407+95aa0ca9.x86_64                     
  slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64                           

Complete!
[ytigiev@screener screener.market]$ sudo systemctl start docker
[ytigiev@screener screener.market]$ docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete 
Digest: sha256:6e8b6f026e0b9c419ea0fd02d3905dd0952ad1feea67543f525c73a0a790fefb
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown.
ERRO[0003] error waiting for container:                 
[ytigiev@screener screener.market]$ docker version 
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:47 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Comment by capriciousduck** [comment] 2023-02-26 05:38
I too see this error. The issue is with the latest version. I got it solved by switching to older version v20.x.x

**Comment by YuriyTigiev** [comment] 2023-03-18 06:58
Any news ? Any solution for this issue ?

**Comment by capriciousduck** [comment] 2023-03-19 13:46
Looks like it's not fixed yet. I'm too waiting to use the latest version of Docker.
