### ISSUE TITLE
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "open /proc/self/fd: no such file or directory".

### ISSUE THREAD

**Issue by suiwenfeng** [docker/cli#297] opened 2017-07-05 08:03 UTC
**Description**

**Steps to reproduce the issue:**
1. docker build
```
FROM nginx
MAINTAINER suiwenfeng <suiwenfeng@fedoraproject.org>

# add config to 
# copy ./default.conf /etc/nginx/conf.d

VOLUME [".","/usr/share/nginx/html"]

CMD ["nginx", "-g", "daemon off;"]
```
2. docker rm -f {containerid}
3. docker volume rm $(docker volume ls -qf dangling=true)

**Describe the results you received:**
> docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "open /proc/self/fd: no such file or directory".

throw the same error for each docker run , and docker run failed.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.06.0-ce, build 02c1d87
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: AX4D:5GVQ:SDCP:PFA2:BJFW:Y3RJ:YYCB:QWV7:UW4B:U5BF:5UJB:CZHF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 34
 System Time: 2017-07-05T08:02:41.906145547Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by suiwenfeng** [comment] 2017-07-05 08:04
i have tried reset docker deamon, it not work.

**Comment by suiwenfeng** [comment] 2017-07-05 08:12
not working even after restart the computer.

**Comment by suiwenfeng** [comment] 2017-07-05 08:13
looks some symlink removed from /dev, and the mobylinux crashed? so i have to reinstall docker?

**Comment by lPegz** [comment] 2017-07-15 10:43
same issue, running same version and on Fedora 25 here too.

**Comment by dnephin** [comment] 2017-07-19 16:06
https://github.com/docker/for-linux/issues is probably a better place to report this issue. I don't believe this is related to the cli.

**Comment by supernelis** [comment] 2017-10-09 09:10
Isn't this because you try to define the volume twice? This volume is already defined in the nginx docker file...

**Comment by bitliubei** [comment] 2017-11-29 08:39
same error, same arm64, same docker version

**Comment by thaJeztah** [comment] 2017-12-26 22:46
```Dockerfile
VOLUME [".","/usr/share/nginx/html"]
```

@suiwenfeng What exactly are you trying to do with that line? Using the JSON notation for `VOLUME` in this case attempts to define _two_ volumes; one at `"."` (current working-directory), and one at `"/usr/share/nginx/html"` (which is already defined as a volume in the base image)

The first (`"."`) is what's causing the issue here, because the working-dir for the `nginx` image is `/`, which effectively would try to create a volume for the whole container (which isn't allowed / won't work). 
You can find the current working-directory for the image using the following;


```bash
$ docker run --rm nginx pwd
/
```

Interesting bit here, is that there is _some_ validation in the daemon, but it's missing validation for certain cases. For example, these Dockerfiles all build without producing an error during build;

```Dockerfile
FROM nginx
VOLUME ["/"]
```

```Dockerfile
FROM nginx
VOLUME /
```

```Dockerfile
FROM nginx
VOLUME ["."]
```

```Dockerfile
FROM nginx
VOLUME .
```


But starting a container from any of the above (as expected) won't work;

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"open /dev/ptmx: no such file or directory\"": unknown.
```

When defining a volume at _runtime_, the following correctly produces a validation error;

```bash
$ docker run -it --rm -v myvolume:/ nginx 
docker: Error response from daemon: invalid volume specification: 'myvolume:/': invalid mount config for type "volume": invalid specification: destination can't be '/'.
See 'docker run --help'.
```

But only specifying the "container path" does _not_ perform the correct validation, thus results in the same "cryptic" error;

```bash
$ docker run -it --rm -v / nginx
docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"open /dev/ptmx: no such file or directory\"": unknown.
```

**Comment by thaJeztah** [comment] 2017-12-26 22:52
I opened https://github.com/moby/moby/issues/35879 for tracking this in the Moby repository (where this validation should be performed). Given that this is not a bug in the CLI, and the bug is missing _validation_ for these cases (the Dockerfile is actually incorrect), I'm closing the issue here, but feel free to continue the conversation

**Closed by thaJeztah** 2017-12-26 22:52 UTC
Labels: area/builder

**Comment by pumba-lt** [comment] 2018-01-21 01:16
Same problem on `docker-ce` within `jenkins` container, running on Windows 10 host (inception):

    docker run -d --name test.nginx -p 90:80 -p 554:443 --network graphityplatform_default --network-alias test.nginx -v /var/jenkins_home/workspace/docker-platform_stage.localhost_/docker/nginx-frontend/nginx.test.conf:/etc/nginx/nginx.conf nginx
    docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/var/jenkins_home/workspace/docker-platform_stage.localhost_/docker/nginx-frontend/nginx.test.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/81cb11389790f97d5026133a05e4f555d499963dd614e082072276ca6a362bc6/merged\\\" at \\\"/var/lib/docker/overlay2/81cb11389790f97d5026133a05e4f555d499963dd614e082072276ca6a362bc6/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
    def81c6ffdf5f699517b2908d6a96ca40551646c4a965cef2be561c9cffd6433

**Comment by akivanctp** [comment] 2018-02-28 09:14
Any solutions on this error ?

**Comment by thaJeztah** [comment] 2018-02-28 10:35
@pumba-lt your error looks different; from the error (copied the important parts below):

```
mounting "/var/jenkins_home/workspace/docker-platform_stage.localhost_/docker/nginx-frontend/nginx.test.conf" to rootfs 
at "/var/lib/docker/overlay2/81cb11389790f97d5026133a05e4f555d499963dd614e082072276ca6a362bc6/merged/etc/nginx/nginx.conf"
caused "not a directory """: unknown: 
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

That error indicates that likely the `nginx.test.conf` file did not exist on the daemon host. If you were attempting to mount a file using the `-v <host-path>:<container-path>` option, and `<host-path>` doesn't exist on the daemon host, docker will assume you want to bind-mount a _directory_, and create the directory if it doesn't exist. It then bind-mounts the directory in the container at `<container-path>`, which will fail if `<container-path>` is a file (because you cannot mount a directory on top of a file). That's the last part of the error message:

```
Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

- check if the file `/var/jenkins_home/workspace/docker-platform_stage.localhost_/docker/nginx-frontend/nginx.test.conf` exists on the daemon host
- if it didn't exist, docker now created a _directory_ at the path above; remove that directory and replace it with the file you're trying to mount
- you can also use the `--mount` flag instead of `-v` / `--volume`: the `--mount` flag will _not_ automatically create a directory if the host-path is missing, but instead produce an error, so that you're aware the path (file/directory) on the host is missing.

Bind-mounting always happens from the host where the _daemon_ runs, so even though the file may be present on your "client" machine; if that machine is a local machine, and not the machine where the daemon runs, bind-mounting won't work.

**Comment by thaJeztah** [comment] 2018-02-28 10:38
@akivanctp the original error reported is an invalid volume path (`/` cannot be used as a volume). For other situations, see my comment above: TL;DR make sure that, when using bind-mounts, the path that you're trying to mount exists.

**Comment by atiasadir** [comment] 2018-11-12 17:02
any solution for this issue ?
 oci runtime error: container_linux.go:265: starting container process caused "exec:

**Comment by hemangjoshi37a** [comment] 2018-12-27 20:38
Any solution??

**Comment by jakubzloczewski** [comment] 2018-12-28 11:17
same with "Version 2.0.0.0-mac78 (28905)"
reset to factory settings helped

**Comment by Liuchengda** [comment] 2019-01-10 11:59
I have a similar issue, when I tried to install elasticsearch on my personal laptop, I execute docker run --name=amp-es -d -v ~/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml -p 9200:9200 -p 9300:9300 --network=amp-network elasticsearch:2.4, then got the same error: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/cliu426/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/53adcd81e2c00ea1f7b40ee67b5ae62ae6d80afbb939b57ef48adf37d003f7fd/merged\\\" at \\\"/var/lib/docker/overlay2/53adcd81e2c00ea1f7b40ee67b5ae62ae6d80afbb939b57ef48adf37d003f7fd/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Error: failed to start containers: amp-es

**Comment by thaJeztah** [comment] 2019-01-10 12:17
@Liuchengda Not the same error (cleaned up the error for readability);

```
mounting "/Users/cliu426/elasticsearch.yml" to rootfs "/var/lib/docker/overlay2/53adcd81e2c00ea1f7b40ee67b5ae62ae6d80afbb939b57ef48adf37d003f7fd/merged"
at "/var/lib/docker/overlay2/53adcd81e2c00ea1f7b40ee67b5ae62ae6d80afbb939b57ef48adf37d003f7fd/merged/usr/share/elasticsearch/config/elasticsearch.yml"
caused "not a directory": unknown:

Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```


That last line is the actual error; you're trying to mount a local file or directory from your host (`/Users/cliu426/elasticsearch.yml`) into the container (at `/usr/share/elasticsearch/config/elasticsearch.yml`). However, the path on your host cannot be found, or is a directory;


- Check if the file `/Users/cliu426/elasticsearch.yml` exists
  - When using the `-v` option; docker creates a directory at the given location if the file/path does not exist
- Note that bind-mounting is done from the host that the _daemon_ runs on, and thus won't work if the daemon is running remotely ("remotely" could be a Virtual Machine)

**Comment by ldynia** [comment] 2019-01-18 15:14
For me the error occurred when I was trying to execute command to run my startup script `command: bash startup.sh`. Problem was that my image build was made on `alpine`  linux  which uses **ash** as shell instead of **bash**. Just double check that you are referring to correct shell interpreter.

**Comment by bvenkatr** [comment] 2019-04-10 04:16
This is because you have changed `COPY` to `VOLUME`, The first image was built with COPY command then now you commented that and added VOLUME , so existing layer was there with COPY, don't know why this is causing error.
But I have fixed this error by deleting existing image which was built using COPY command, and now rebuild image fixed the issue

**Comment by n0str** [comment] 2019-05-15 08:30
It is also may be caused by modified credentials (on Windows). When you have changed your system password, Docker cannot automatically determine it.
You should go to Settings\Shared Drives and Reset credentials.

**Comment by iwpnd** [comment] 2019-05-15 13:05
> 
> 
> It is also may be caused by modified credentials (on Windows). When you have changed your system password, Docker cannot automatically determine it.
> You should go to Settings\Shared Drives and Reset credentials.

This actually fixed it for me. Went nuts for a whole afternoon. Thank you!

**Comment by meirkr** [comment] 2019-05-21 16:56
> > It is also may be caused by modified credentials (on Windows). When you have changed your system password, Docker cannot automatically determine it.
> > You should go to Settings\Shared Drives and Reset credentials.
> 
> This actually fixed it for me. Went nuts for a whole afternoon. Thank you!

Same what happened for me: "This actually fixed it for me. Went nuts for a whole afternoon. Thank you!"

**Comment by ThaSami** [comment] 2019-10-27 13:00
same error here when running Hello-world docker version.. Docker on Fedora 31

> [ThaSami@localhost ~]$ docker run hello-world
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"open /sys/fs/cgroup/docker/cpuset.cpus.effective: no such file or directory\"": unknown.
> ERRO[0009] error waiting for container: context canceled

**Comment by thaJeztah** [comment] 2019-10-28 16:13
@ThaSami current version of Fedora 31 switched to using cgroupsV2 by default, which is not yet supported by the container runtimes (and kubernetes); work is in progress on this, but not yet complete, and not yet production ready. To disable v2 cgroups, run:

```
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
```

And restart your machine.

**Comment by tomwj** [comment] 2019-11-01 14:54
I had the same issue on a host running Ubuntu and needed to use:

`sudo update-grub "systemd.unified_cgroup_hierarchy=0"`

For anyone else that is on Ubuntu so doesn't have `grubby`

**Comment by florianajir** [comment] 2019-11-20 15:48
I have this error on windows and I never changer my credentials

**Comment by dkypuros** [comment] 2019-11-22 22:58
> @ThaSami current version of Fedora 31 switched to using cgroupsV2 by default, which is not yet supported by the container runtimes (and kubernetes); work is in progress on this, but not yet complete, and not yet production ready. To disable v2 cgroups, run:
> 
> ```
> sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
> ```
> 
> And restart your machine.

Thanks for your fix. I'm on Fedora 31, and docker works with latest docker documentation for fedora: https://docs.docker.com/install/linux/docker-ce/fedora/#install-docker

**Comment by mokaymakci** [comment] 2019-11-23 12:36
> @ThaSami current version of Fedora 31 switched to using cgroupsV2 by default, which is not yet supported by the container runtimes (and kubernetes); work is in progress on this, but not yet complete, and not yet production ready. To disable v2 cgroups, run:
> 
> ```
> sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
> ```
> 
> And restart your machine.

The solution worked like a charm for Fedora 31.

**Comment by Montana** [comment] 2019-12-16 02:57
Getting this on Mac OSX Catalina still.

**Comment by sergio00** [comment] 2020-01-23 20:26
> Getting this on Mac OSX Catalina still.

Any advice or suggest?

**Comment by SalathielGenese** [comment] 2020-02-05 17:37
Fedora 31

```
$ sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
grub2-editenv: error: invalid environment block.
grub2-editenv: error: invalid environment block.
grub2-editenv: error: invalid environment block.
grub2-editenv: error: invalid environment block.
grub2-editenv: error: invalid environment block.
grub2-editenv: error: invalid environment block.
```

**Comment by GoPerry** [comment] 2020-03-20 14:30
Fedora31 docker also has the issue :
`
I already add the systemd.unified_cgroup_hierarchy=0 to grub.

BOOT_IMAGE=/vmlinuz-5.5.8-200.fc31.x86_64 root=/dev/mapper/fedora_localhost--live-root ro resume=/dev/mapper/fedora_localhost--live-swap rd.lvm.lv=fedora_localhost-live/root rd.lvm.lv=fedora_localhost-live/swap modprobe.blacklist=nouveau systemd.unified_cgroup_hierarchy=0


docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"xtensa-build-all.sh\": executable file not found in $PATH": unknown.`

**Comment by jeffgallo** [comment] 2020-05-11 01:48
I am experiencing the same under Ubuntu 20.04 with zfs on root after a reboot. I have reinstalled docker and cannot get my containers up. 

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/entrypoint.sh\": stat /entrypoint.sh: no such file or directory": unknown.

**Comment by subbu05** [comment] 2020-05-18 01:23
Same issue
`docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 23.49GiB
 Name: docker-desktop
 ID: DZJE:3T56:26T2:GW7G:XM52:A6Y6:5ZAH:XEBW:VXLH:QKS7:EDWG:ODH3
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 39
  Goroutines: 51
  System Time: 2020-05-18T01:21:22.371080486Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine`

 docker run -it centos centos /bin/sh
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"centos\": executable file not found in $PATH": unknown.

**Comment by 0xSeb** [comment] 2020-05-19 19:05
Had the same issue here on Manjaro 20.0.1 -> Docker version 19.03.8-ce -> Container centos:7

**Solved it** by doing:  _chmod+x entry-point.sh_ from the host.

**Comment by smc181002** [comment] 2020-06-26 12:33
I executed this command `docker run -it centos` and the error shows up

**Comment by minaee** [comment] 2020-07-07 12:03
I executed `sudo docker run busybox -it --rm`, it throws back this error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-it\": executable file not found in $PATH": unknown.
> ERRO[0002] error waiting for container: context canceled

any ideas?

**Comment by thaJeztah** [comment] 2020-07-07 12:21
@minaee docker flags should be put _before_ the image name, otherwise they're passed to the container as arguments for the container's main process:

```console
docker run [options] [image name] [arguments for container's process]
```

So in your case;

```bash
sudo docker run -it --rm busybox
```

**Comment by minaee** [comment] 2020-08-12 06:00
> @minaee docker flags should be put _before_ the image name, otherwise they're passed to the container as arguments for the container's main process:
> 
> ```
> docker run [options] [image name] [arguments for container's process]
> ```
> 
> So in your case;
> 
> ```shell
> sudo docker run -it --rm busybox
> ```

Oh, yes. Thanks

**Comment by Firass7** [comment] 2020-09-08 14:06
Hey everyone, what about this error please.
i execute this command "sudo docker run hello-world" , it gives me this error 

<<< docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/63492ef766e4b2f1ae17d5b6abc40fc07b910caeb46a570fdd43d25c82694a04/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown.
ERRO[0003] error waiting for container: context canceled >>>

**Comment by przemo-hemmersbach** [comment] 2020-09-15 06:16
In my case, incorrect volume declaration cause this issue. I had "- ./" in volumes section of docker-compose.yml.

**Comment by wongjiahau** [comment] 2020-09-30 08:56
> @jakubzloczewski double-check the exact command you're running to start your container; from that output, it looks like you passed the `-d` option _after_ the name of the image you're trying to run. Because of that, `-d` is used as the command to run _inside_ the container, thus will fail;
> 
> ```shell
> docker run busybox -d
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"-d\": executable file not found in $PATH": unknown.
> ```
> 
> The `-d` (`--detach`) option is an option for _docker run_, so must be passed _before_ the name of the image you're running;
> 
> ```shell
> docker run -d busybox
> ```

My goodness you're right, it's because I messed up the argument positions, regardless the error message (or the argument parser) needs improvement, without this thread it's impossible to figure out why.

**Comment by Thomas-X** [comment] 2020-10-11 13:08
still getting this, 2 years later and 40+ reactions on macOS catalina, stuff like this makes me doubt the time I save with docker for development.. 🙃

**Comment by iamm3chanic** [comment] 2020-11-13 08:38
@dkypuros Thanks a lot! This documentation also works for Fedora 32.

**Comment by Light--** [comment] 2020-11-19 03:41
ubuntu 20.04:
```
$ sudo update-grub "systemd.unified_cgroup_hierarchy=0"
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.4.0-53-generic
Found initrd image: /boot/initrd.img-5.4.0-53-generic
Found linux image: /boot/vmlinuz-5.4.0-52-generic
Found initrd image: /boot/initrd.img-5.4.0-52-generic
Found Windows Boot Manager on /dev/sdb1@/efi/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for UEFI Firmware Settings
done


$ docker run --gpus all nvcr.io/nvidia/mxnet:20.10-py3
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded\\\\n\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by ThomasGeor** [comment] 2020-12-02 19:11
> `sudo update-grub "systemd.unified_cgroup_hierarchy=0"` not helped. @tomwj
> 
> ubuntu 20.04:
> 
> ```
> $ sudo update-grub "systemd.unified_cgroup_hierarchy=0"
> Sourcing file `/etc/default/grub'
> Sourcing file `/etc/default/grub.d/init-select.cfg'
> Generating grub configuration file ...
> Found linux image: /boot/vmlinuz-5.4.0-53-generic
> Found initrd image: /boot/initrd.img-5.4.0-53-generic
> Found linux image: /boot/vmlinuz-5.4.0-52-generic
> Found initrd image: /boot/initrd.img-5.4.0-52-generic
> Found Windows Boot Manager on /dev/sdb1@/efi/Microsoft/Boot/bootmgfw.efi
> Adding boot menu entry for UEFI Firmware Settings
> done
> 
> 
> $ docker run --gpus all nvcr.io/nvidia/mxnet:20.10-py3
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded\\\\n\\\"\"": unknown.
> ERRO[0000] error waiting for container: context canceled
> ```

Same error on ubuntu 20.04

**Comment by Sagzster** [comment] 2020-12-03 16:49
Debian 10 and following instructions from site.
$ sudo docker run hello-world
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"proc\\\" to rootfs \\\"/var/lib/docker/overlay2/85e3fff3dba9f06037ec713e0cb5cfe963b761dfd6edd5c0eed79857dbfc5d66/merged\\\" at \\\"/proc\\\" caused \\\"permission denied\\\"\"": unknown.
ERRO[0000] error waiting for container: context canceled

**Comment by ThomasGeor** [comment] 2020-12-03 20:10
> > `sudo update-grub "systemd.unified_cgroup_hierarchy=0"` not helped. @tomwj
> > ubuntu 20.04:
> > ```
> > $ sudo update-grub "systemd.unified_cgroup_hierarchy=0"
> > Sourcing file `/etc/default/grub'
> > Sourcing file `/etc/default/grub.d/init-select.cfg'
> > Generating grub configuration file ...
> > Found linux image: /boot/vmlinuz-5.4.0-53-generic
> > Found initrd image: /boot/initrd.img-5.4.0-53-generic
> > Found linux image: /boot/vmlinuz-5.4.0-52-generic
> > Found initrd image: /boot/initrd.img-5.4.0-52-generic
> > Found Windows Boot Manager on /dev/sdb1@/efi/Microsoft/Boot/bootmgfw.efi
> > Adding boot menu entry for UEFI Firmware Settings
> > done
> > 
> > 
> > $ docker run --gpus all nvcr.io/nvidia/mxnet:20.10-py3
> > docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: nvml error: driver not loaded\\\\n\\\"\"": unknown.
> > ERRO[0000] error waiting for container: context canceled
> > ```
> 
> Same error on ubuntu 20.04

I was copying a directory instead of an executable file in my dockerfile so it was crushing like this. Be careful when you copy stuff in containers.

**Comment by kalipichandiarumugam** [comment] 2021-02-26 02:53
I fixed such issues in my local.

Error is below:
**"Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/<mylocalpath>\\\" to rootfs \\\"/var/lib/docker/overlay2/830894f27fcb8f3c523234f1da8504dd2dda4424343d71bddeb477b07888061a/merged\\\" at \\\"/var/lib/docker/overlay2/830894f27fcb8f3c523234f1da8504dd2dda4424343d71bddeb477b07888061a/merged/docker-entrypoint-initdb.d/init.sql\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type"**

Root Causes:
Deleted the mounting path in local which is already connected with my local docker. I was running docker without this file <mylocalpath>, hence I got above error.

Resolution:
I just recreated the path (<mylocalpath>) and restarted the docker. Then i could able to start my docker container.

**Comment by sorrynofocus** [comment] 2021-05-27 02:59
This issue is a little old --  but why not comment anyway ^_^  

Earlier, I assigned a new mount on my system under /etc/fstab. When I unmounted ,I noticed the mounts were busy. I didn't think of it and tried to mount again. The newly added mount was fine. I just ignored it and went on. 

I later ran a container with a volume mount point (option -v ) on a local (not connected to any local mount points, btw) I got this lovely and inviting error. I discovered it was me who caused the error when I modified /etc/fstab and messed with the mounts. I nifty reboot helped when umounting failed.

Hope this helps.

**Comment by yomofo2s** [comment] 2021-06-18 20:37
Looks like this is really a common problem with the mount volume while using docker ![image](https://user-images.githubusercontent.com/44329653/122613818-c4728780-d085-11eb-8091-8214acbdba4f.png) by nginx

$docker run --name spa-web -v $(pwd):/usr/share/nginx/html:ro -d nginx

I have have similar issue with OCI runtime create failed: invalid mount while mounting my mount file. I observed a new folder was created which is totally different from my current directory where my html files are..This is absolutely strange to me.

![image](https://user-images.githubusercontent.com/44329653/122613843-ce948600-d085-11eb-9c56-fe01a2433a76.png)


the spa was what i specified in my code while spa;C kept popping up after i run my command.

any help would be greatly appreciated

Docker version 20.10.7, build f0df350
windows 10

**Comment by yomofo2s** [comment] 2021-06-18 21:15
Okay so i figured out a workaround. I changed my terminal and stopped using bash script in interi,m. So i tried powershell instead because of windows os. However, something changed. in my code, () now {}

`$docker run --name spa-web -v ${pwd}:/usr/share/nginx/html:ro -d nginx`

**Comment by jgod** [comment] 2021-07-06 04:55
I kept getting `directoryName;C` pop up as an extra folder alongside where I was invoking the command. It turned out that it likes `$PWD` more than `$(pwd)`. On Windows 10 in Git Bash shell.

**Comment by luoyixin2019** [comment] 2021-08-05 06:28
I used Docker20 in CentOS7， and the issues is solved by degrading docker from 20 to 17.

**Comment by LinxiFan** [comment] 2021-08-29 18:43
Killing any currently running docker containers and then `docker container prune` worked for me. It looks like some container went bananas and affected the host environment ... 😨

**Comment by gauravkantrod** [comment] 2021-09-04 14:04
assign +x permissions, deleting the existing image, rerun docker build command worked for me

**Comment by IvRRimum** [comment] 2021-11-11 07:09
Everytime i restart my pc, i have this error :// Ubuntu 21

**Comment by fredqi** [comment] 2021-11-13 09:22
In my case, this is related to the **rootless** mode. To disable rootless mode, do as follows:
1. Uninstall two packages: `sudo apt purge docker-ce-rootless-extras uidmap`
2. Remove the lines contain my username in both `/etc/subuid` and `/etc/subgid`.
3. Comment out `export DOCKER_HOST=unix:///run/user/1000/docker.sock` in `$HOME/.bashrc`
4. Restart docker with `sudo service docker restart`.

**Comment by stru001** [comment] 2021-11-25 06:43
使用目录映射了容器内的文件导致的，检查一下宿主机和容器目录或文件的对应关系是否正确。

**Comment by pidgeon777** [comment] 2022-01-20 23:42
I had the `docker: Error response from daemon: oci runtime error: container_linux.go` when trying to do:

`docker run hello-world`

In my setup I'm using docker installed in WSL 1.

First of all I upgraded my Ubuntu VM from WSL 1 to 2, then inside WSL I did:

```sh
sudo apt update
sudo apt upgrade
```

Finally, I was able to run the `docker run hello-world` and build every other `Dockerfile`.

**Comment by bitliubei** [comment] 2022-02-07 09:43
unsubscribe

**Comment by troinoiOdekoloN** [comment] 2022-04-15 09:04
Reboot helped me on my mac :)

**Comment by mjovanc** [comment] 2022-06-18 12:47
For anyone else experiencing this it was due to a wrong configuration of VOLUME in my Dockerfile.

**Comment by ArunPresent** [comment] 2022-09-03 05:15
if anyone of you are still not able to resolve this  just add 
**RUN apt-get install nginx -y** 
to your docker file  and rebuild the image it will work

**Comment by amrohendawi** [comment] 2022-09-11 17:34
I was struggling with this issue trying to build my CI/CD pipeline with gitlab-runner and docker:dind. I ran

`ls $PWD`

I found out somehow docker-compose was one directory behind.


> Same problem on `docker-ce` within `jenkins` container, running on Windows 10 host (inception):
> 
> ```
> docker run -d --name test.nginx -p 90:80 -p 554:443 --network graphityplatform_default --network-alias test.nginx -v /var/jenkins_home/workspace/docker-platform_stage.localhost_/docker/nginx-frontend/nginx.test.conf:/etc/nginx/nginx.conf nginx
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/var/jenkins_home/workspace/docker-platform_stage.localhost_/docker/nginx-frontend/nginx.test.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/81cb11389790f97d5026133a05e4f555d499963dd614e082072276ca6a362bc6/merged\\\" at \\\"/var/lib/docker/overlay2/81cb11389790f97d5026133a05e4f555d499963dd614e082072276ca6a362bc6/merged/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
> def81c6ffdf5f699517b2908d6a96ca40551646c4a965cef2be561c9cffd6433
> ```

I was struggling with this issue with my nginx reverse proxy while trying to build my CI/CD pipeline with gitlab-runner and docker:dind. I ran

`ls $PWD`

I found out somehow docker-compose was one directory behind.

I changed my docker-compose from

```yaml
nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8001:8001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
```

to

```yaml
  nginx:
    image: nginx
    container_name: nginx
    build:
        context: ./nginx
    ports:
      - "8001:8001"
    volumes:
      - ./nginx:/etc/nginx/nginx
```

And finally problem solved!

**Comment by devsingh1234** [comment] 2022-10-24 06:11
> Any solutions on this error ?

got any solution why is this happening

**Comment by ArunPresent** [comment] 2022-10-24 16:34
> if anyone of you are still not able to resolve this just add **RUN apt-get install nginx -y** to your docker file and rebuild the image it will work

I guess you need to install nginx on your docker image and it will work then

**Comment by shoxabbos** [comment] 2023-02-06 12:54
If you trying to run shell command like this: 

```
ENTRYPOINT ["/var/www/.docker/run.sh"]
```
You need try this way

```
ENTRYPOINT ["/bin/sh", "-c", "/var/www/.docker/run.sh"]
```
