### ISSUE TITLE
Volume or container completion is broken in zsh

### ISSUE THREAD

**Issue by ay0o** [docker/cli#1997] opened 2019-07-11 11:36 UTC
**Description**
Completion does not work for volumes or container's id/names in ZSH

**Steps to reproduce the issue:**
`docker run -v <TAB>`
or
`docker exec -it `<TAB>`

**Describe the results you received:**
Nothing is completed

**Describe the results you expected:**
I expected to have a list of directories in the current path in the first case, or a list of containers in the second.

**Additional information you deem important:**
For example, in Bash that works like a charm. `docker run -v <TAB>` will return a list of the directories, meanwhile `docker exec -it <TAB>` will return a list of the containers.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 38
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: trvdyzd4jc8jra925irru11ac
 Is Manager: true
 ClusterID: ravg59u2mm6svhkryrq61uvlv
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.3
 Manager Addresses:
  192.168.65.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 4V4B:GQBZ:QWT4:W4NP:V5Q2:ZX57:YBJE:LMQY:LIMN:7LBB:KDVH:RIPN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 46
 Goroutines: 169
 System Time: 2019-07-11T11:34:34.2064696Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine```

**Comment by SKoschnicke** [comment] 2020-02-10 12:52
Seems to be an issue with the flags. `docker exec <TAB>` works while `docker exec -it <TAB>` does not.

**Comment by CB79** [comment] 2020-03-25 09:29
`docker exec -i <TAB>` works
`docker exec -i -t <TAB>` works
`docker exec -it <TAB>` does not work

The same applies to `docker run`. As soon as arguments are combined auto-completion of images doesn't work.

**Comment by pseyfert** [comment] 2020-05-04 17:51
This looks to me like a duplicate of https://github.com/docker/cli/issues/993 . The solution reported there (in [this reply](https://github.com/docker/cli/issues/993#issuecomment-380301049) ) is that the capability of option stacking can be enabled with
```
zstyle ':completion:*:*:docker-*:*' option-stacking yes 
```

**Comment by m-zat** [comment] 2021-03-04 20:21
I don't think stacking options is solving the issue raised above. It might with `-it` (did not test) but it does not with `-v`.
It would be nice to have completion for
```
docker run -v <TAB>
```
to show file completion too, not only volume completion.

**Comment by pseyfert** [comment] 2021-03-04 20:43
indeed, sorry i was focussing on the `-it`. volumes are indeed missing at the end of this line https://github.com/docker/cli.git

**Comment by pseyfert** [comment] 2021-03-04 22:03
@m-zat thanks for the ping. I opened #2998.

**Comment by m-zat** [comment] 2021-03-05 07:57
Thanks @pseyfert! Just tested it and it works like a charm!

**Closed** 2024-03-25 16:20 UTC
Labels: platform/desktop, area/completion
