### ISSUE TITLE
`docker images [REPOSIROTY[:TAG]]` does not shows images related to defined REPOSITORY and TAG

### ISSUE THREAD

**Issue by Dgeremi** [docker/cli#2642] opened 2020-07-21 08:19 UTC
**Description**
According to documentation (https://docs.docker.com/engine/reference/commandline/images/#list-images-by-name-and-tag) the following command:
`docker images debian` should display all the images related to Debian repository but instead, it shows an empty list

**Steps to reproduce the issue:**
1. pull some base images for tests:
```
> docker pull fedora
> docker pull fedora:31
> docker pull fedora:30
> docker pull debian
> docker pull debian:jessie

> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
fedora              latest              a368cbcfa678        10 days ago         183MB
fedora              31                  4d1ff2457258        10 days ago         177MB
debian              jessie              a3590c0e9ff9        6 weeks ago         129MB
debian              latest              1b686a95ddbf        6 weeks ago         114MB
fedora              30                  177d5adf0c6c        5 months ago        238MB
```

2. execute the following commands:
```
> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
fedora              latest              a368cbcfa678        10 days ago         183MB
fedora              31                  4d1ff2457258        10 days ago         177MB
debian              jessie              a3590c0e9ff9        6 weeks ago         129MB
debian              latest              1b686a95ddbf        6 weeks ago         114MB
fedora              30                  177d5adf0c6c        5 months ago        238MB
> docker images fedora
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> docker images debian
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> docker images debian:latest
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> docker images -a debian
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
> docker images -q debian
<no output here>
```

**Describe the results you received:**
When specifying `[REPOSITORY[:TAG]]` after `docker images` command it shows an empty list 

**Describe the results you expected:**
The `docker images` command takes an optional `[REPOSITORY[:TAG]]` argument that restricts the list to images that match the argument. If you specify `REPOSITORY` but no `TAG`, the `docker images` command lists all images in the given repository.

**Additional information you deem important (e.g. issue happens only occasionally):**
The same issue appears when you use `docker image ls` command with the same STR and same result

**Output of `docker version`:**

```
> docker version
Client: Docker Engine - Community
 Version:           19.03.11-ol
 API version:       1.40
 Go version:        go1.14.4
 Git commit:        a9b9315
 Built:             Tue Jun 23 03:33:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11-ol
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.4
  Git commit:       a9b9315
  Built:            Tue Jun 23 03:31:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
 containerd:
  Version:          v1.2.0-rc.0-108-gc444666
  GitCommit:        c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
> docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 19.03.11-ol
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc version: 4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.13.1.el7.x86_64
 Operating System: Oracle Linux Server release 7.5
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 9.764GiB
 Name: localhost.localhost
 ID: FSPV:3Z4J:FMRC:7EEB:ETFW:ZTL6:CBHE:Z2CX:KY35:2SCS:JUE5:BJOV
 Docker Root Dir: /porta_var/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

Registries:
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running VirtualBox environment
```
>  vboxmanage --version
6.0.16r135674
```
On Fedora OS:
```
>  cat /etc/fedora-release
Fedora release 30 (Thirty)
```

**Comment by dominikbraun** [comment] 2020-07-21 17:24
I cannot reproduce this issue with Docker 19.03.8 - all `docker images` commands work as intended.

<details>
<summary>Version information</summary>

```shell script
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
</details>

**Comment by thaJeztah** [comment] 2020-07-21 17:28
I'm unable to reproduce this on Docker 19.03.12;

```bash
docker images debian

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
debian              sid                 7765f8c69f16        6 weeks ago         119MB
debian              buster              1b686a95ddbf        6 weeks ago         114MB
debian              latest              1b686a95ddbf        6 weeks ago         114MB
```

However, I see you're running the Oracle fork of Docker, which has modifications to the source code that I've seen causing issues like this

**Comment by LambdaDriver** [comment] 2020-08-17 17:27
I can reproduce this bug running the Oracle fork as well, installing from the docker-CE repo for centos on the same Oracle Linux server resolves the issue.

**Comment by thaJeztah** [comment] 2020-08-17 17:59
Thanks for checking; let me go ahead and close this one, as it looks like it's an issue with the Oracle fork, which we don't maintain. Feel free to continue the conversation after I closed

**Closed by thaJeztah** 2020-08-17 17:59 UTC
