### ISSUE TITLE
 OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/liquibase/liquibase\": permission denied": unknown.

### ISSUE THREAD

**Issue by chtcs-vamsi** [docker/cli#2553] opened 2020-05-28 02:33 UTC
image used: liquibase/liquibase
image source url: https://github.com/liquibase/docker

command: docker run --rm -v <path>:/liquibase liquibase/liquibase  update
path contains liquibase.properties file

Tried: added path in shared resources for through docker settings [Settings>Resources>File Sharing added path]

**Comment by thaJeztah** [comment] 2020-06-05 14:53
if that's the exact command you're running, it looks like you did not specify the host path for the bind-mount;

```
docker run --rm -v :/liquibase liquibase/liquibase update
```

Which should probably be something like

```
docker run --rm -v $(pwd):/liquibase liquibase/liquibase update
```

or

```
docker run --rm -v /Users/yourname/somedir/:/liquibase liquibase/liquibase update
```


However, there's not much information in your report to actually reproduce the issue. When reporting a bug, please provide the information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-05 14:53 UTC
