### ISSUE TITLE
Docker log rotation is not working the container log keeps on growing

### ISSUE THREAD

**Issue by avi-kalar** [docker/cli#1148] opened 2018-06-26 17:03 UTC
I have an issue that even though I set the docker log configuration it does not kick in and my docker logs grows till I run out of disk space. Can you please tell me when the log rotation is cleaned up, I have the following config set for my container when I run 

`docker inspect <container-id>`

          `"LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "5",
                    "max-size": "100m"
                }
            }`

and my log size is above 400 MB right now, but the log rotation hasn't kicked in.

**Steps to reproduce the issue:**
1. docker run --name badguy --log-opt max-size=1k --log-opt max-file=5 -d ubuntu sh -c "while true; do printf A; done"
2. wait for a while
3. `docker kill badgu`

**Describe the results you received:**
my log size is above 1k right now, but the log rotation hasn't kicked in.

**Describe the results you expected:**
Log rotation with file size not exceeding 1k

**Output of `docker version`:**

```

```

**Output of `docker info`:**

```
Containers: 39
 Running: 1
 Paused: 0
 Stopped: 38
Images: 1441
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1214
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 6GE7:EIWS:LOD2:IFS2:3UHV:A62R:FWGU:RYUM:LTSJ:7D4B:VWES:DLEL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 32
 System Time: 2018-06-26T10:22:08.783714835Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment] 2018-06-26 21:35
How are you checking the log size?

**Comment by kavinash-athena** [comment] 2018-06-27 05:07
by running the command 
`sh -c "du -ch /var/lib/docker/containers/*/*-json.log"` 
and the output I get is 
```
24K	/var/lib/docker/containers/40ab2ef8b7c01f5d41d672b064fc34fcaeb51c8d2c35285e7aaf3c3f48485baa/40ab2ef8b7c01f5d41d672b064fc34fcaeb51c8d2c35285e7aaf3c3f48485baa-json.log
390M	/var/lib/docker/containers/c074baa1bd4879bee699a636ddc681884ff85b6cf5b6203cc1d5a8d75bae0e94/c074baa1bd4879bee699a636ddc681884ff85b6cf5b6203cc1d5a8d75bae0e94-json.log
8.0K	/var/lib/docker/containers/dfea013ce11098384eb4861c53ad1df3f4cf72af07fccacd5e8531f4af34e0ee/dfea013ce11098384eb4861c53ad1df3f4cf72af07fccacd5e8531f4af34e0ee-json.log
390M	total
```

**Comment by thaJeztah** [comment] 2018-06-27 08:38
17.03.1 is a really old version of Docker; are you still seeing the problem if you upgrade to a current version?

**Comment by kavinash-athena** [comment] 2018-06-27 09:02
@thaJeztah - I have an EC2 instance with the following version
```
docker version
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built:	Tue Apr  3 23:37:44 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6/17.12.1-ce
  Built:	Tue Apr  3 23:38:52 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```
Will it work on this version, and do you know how often does the job for log rotation gets triggered?

**Comment by kavinash-athena** [comment] 2018-06-27 09:36
@thaJeztah the test container is rotating logs as expected in the above version, but I still face issues with the container I have created for my application. I am not sure why I get different behaviour in this case even though the configs are similar and the only difference is that I set the log config via ECS task

```
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "5",
                    "max-size": "100m"
                }
            },
```
Do you see anything wrong with the config ?

The config set on ECS task definition is 

```
      "logConfiguration": {
        "logDriver": "json-file",
        "options": {
          "max-size": "100m",
          "max-file": "5"
        }
```

**Comment by cpuguy83** [comment] 2018-06-27 18:17
Is this the config that's actually set on the container in question in Docker?

**Comment by kavinash-athena** [comment] 2018-06-28 05:17
yes @cpuguy83

**Comment by kavinash-athena** [comment] 2018-07-02 08:45
@cpuguy83 This is working now for a smaller `max-size` limit, the issue was the way I have been expanding the logs to reach 100m. I was appending the same file to the end of the file and thus growing the log files. Something wasn't quite adding up. Any guess what could have gone wrong here?

**Comment by thaJeztah** [comment] 2018-07-02 09:14
You cannot change the configuration for existing containers; when you mention "expanding the logs"; were you trying to change the configuration after containers were already started with the old configuration? Are your tools attempting to change/update the configuration of existing containers?

**Comment by cpuguy83** [comment] 2018-07-02 18:51
Ok, so maybe some misunderstanding of these params here.
`max-size` is max size *per file*, `max-file` is the maximum number of files.

**Comment by wouterds** [comment] 2018-10-07 22:31
Can confirm that it does not work as expected.

![screen shot 2018-10-08 at 00 30 45](https://user-images.githubusercontent.com/1210628/46587770-7d890300-ca91-11e8-842a-fe0660e273d8.jpg)

**Comment by lucas-dehandschutter** [comment] 2019-01-15 15:33
Hello,

I have a similar issue but by setting these value in the /etc/docker/daemon.json:

```
{
  "storage-driver": "overlay2",
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "log-level": "info",
  "iptables": true,
  "insecure-registries": [],
  "cgroup-parent": "docker",
  "icc": false
}
```
Even after rebooting the server and redeploying all my docker services, the logs file of each services keeps growing with no limit.

**Comment by miande-acxiom** [comment] 2019-02-21 17:22
Any update to this issue?

**Comment by widovsky** [comment] 2019-03-26 13:33
It's not possible to change the log driver. To change it, you need to rerun the container.

**Comment by akatiyar** [comment] 2019-04-22 22:27
I updated /etc/docker/daemon.json to {"live-restore": true, "storage-driver": "overlay2", "log-driver":"gcplogs"}, restarted the host, and I am still seeing json logs filling the disk.

**Comment by cpuguy83** [comment] 2019-04-23 18:24
Just updating the driver in the daemon.json is not enough... as stated you must re-create the container.

**Comment by wekeepofficial** [comment] 2019-06-12 20:16
Recreating the container worked for me.

**Comment by boid-com** [comment] 2019-10-23 00:35
What is the solution to this problem? Logrotate doesn't seem to work even when containers are recreated.

**Comment by cpuguy83** [comment] 2019-10-23 02:15
What's the exact settings in your config?
What's the container's config ("docker inspect")

**Comment by boid-com** [comment] 2019-10-23 03:40
docker inspect HostConfig.LogConfig 
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },

docker-compose.yml
version: '3' 
services:
  prisma:
    image: prismagraphql/prisma:1.27.1
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"

**Comment by cpuguy83** [comment] 2019-11-05 19:34
This looks like compose is not passing down the options for some reason.
I'm not intimately familiar with the compose schema here.

Doing a `docker run` manually with log options works just fine.

**Comment by achimnol** [comment] 2020-03-04 06:25
The log rotation is working there, but it seems not to be very accurate.
I think this may be due to I/O buffering, line-based buffering (e.g., it would not skip the file size check when a line output on the console is very long enought to exceed the file size), etc.

**Comment by achimnol** [comment] 2020-03-04 06:46
We could test the log rotation by using [my gist](https://gist.github.com/achimnol/afe1608fd64692b57cf9aed2eaeb9262), where the first argument is the size of total output and the second argument is the length of lines.

For instance,
```
docker run -it \
  -v $(pwd)/long-logs.py:/root/long-logs.py \
  --log-driver json-file \
  --log-opt max-size=50 \
  --log-opt max-file=2 \
  python:3.8-alpine \
  python /root/long-logs.py 100000 700
```
results in
```console
$ docker logs xxxx | wc -c
1304
```
whose log size  exceeds 50 x 2 = 100 bytes significantly.

**Comment by achimnol** [comment] 2020-03-04 06:59
Also, the log size applies to the console output, so depending on the logging driver, the actual filesystem size may vary. The differences may get quite large if the log size is big and when there are many short lines in the log. (e.g., an infinite loop of printing a single character line-by-line.)
This behavior should be documented or the implementation should be improved.

**Comment by cpuguy83** [comment] 2020-03-05 01:15
I do not think there is any reason to try and make this so exact.
There is a 1MB line buffer.
We always write a full line (plus metadata like timestamp and which i/o stream it came from) to the log.

Having a log file stay smaller than 1MB and also write lines as large as 1MB does not seem like a real use-case.
Likewise having a container write lines that are larger than the max log file size does not seem like a real use case.

I'm going to close this as issues seem to be related to incorrect configuration. We have tests for this in tree as well.
If you are having  this issue on Docker 19.03.6 please let us know the details.
And remember, containers must be re-created if you are relying on changes made daemon.json.
Thanks! 😇

**Closed by cpuguy83** 2020-03-05 01:15 UTC

**Comment by Dpz94** [comment] 2020-04-08 06:47
This is not working even in the practical use case. Where I have given 50mb as max size and it still grows to GB.

**Comment by thaJeztah** [comment] 2020-04-08 08:35
@Dpz94 have you verified the correct options are set on the container that has this issue (i.e., not just the daemon configuration)?

**Comment by Dpz94** [comment] 2020-04-08 09:03
Am deploying my container using ansible, I have updated the daemon.json with above configuration and restarted the service and then created the container, any other additional steps required>??

**Comment by thaJeztah** [comment] 2020-04-08 10:54
@Dpz94 I don't know what the Ansible deploy does w.r.t. configuration, so to find out what options the container was created with you need to do a `docker inspect` of the container and check its configuration.

**Comment by Dpz94** [comment] 2020-04-08 13:04
Is there any particular option should we use while creating the container??, I edited the daemon.json file with the below config restarted docker service and deployed my container but still i could see my single log json file which is gone till 1 GB.

docker inspect on log config:

"LogConfig": {
                "Type": "json-file",
                "Config": {}

dameon.json:
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "20"
  }

**Comment by thaJeztah** [comment] 2020-04-08 13:19
the `LogConfig` of that container shows that no options are set for the `json-file` logging driver, which means it does not have limits set.

When creating the container, either;

- set _no logging options_ (including _no_ logging-driver); in that case, the daemon defaults will be applied (which should be reflected in the container config after it's created (`docker inspect <container-id>`)
- or provide all custom options for the container (logging-driver + log-opts)

If you provide only the logging-driver, docker assumes you want to use that driver, and override the defaults that are set in the daemon configuration. If you don't provide `log-opts` for the container, it means: "reset the default limits that are set in the daemon configuration" (in other words: don't set any limits for this container).

**Comment by Dpz94** [comment] 2020-04-08 16:51
@thaJeztah Thankyou so much, Am able to achieve it through custom options for the container but not able to make it use the daemon.json configuration I tried to create the container using logging option none but it is not taking the config from daemon.json rather it is showing as log driver none. If that is not correct method of doing the set no logging options please assist. TIA

**Comment by MondaySam** [comment] 2020-05-19 08:54
I'm sorry but we have the same issues with logging options not finding their way into the container.
we have set options in our docker-compose.yml but an inspect of the container shows empty log-opts.

We use
```
logging:
      driver: 'json-file'
      options:
        max-size: '1m'
        max-file: '5'
```
in our yml-file.

**Comment by thaJeztah** [comment] 2020-05-19 10:05
@MondaySam Hm.. not able to reproduce that; I tried on:

```bash
docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6

docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
...
```

With this `docker-compose.yaml`:

```yaml
version: "3.7"
services:
  web:
    image: nginx:alpine
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "5"
```

Deploy the compose-file with `docker-compose`:

```bash
docker-compose up -d
Creating network "repro-1148_default" with the default driver
Creating repro-1148_web_1 ... done
```

Inspect:

```bash
docker container inspect --format '{{ json .HostConfig.LogConfig }}' repro-1148_web_1 | jq .

{
  "Type": "json-file",
  "Config": {
    "max-file": "5",
    "max-size": "1m"
  }
}
```

Deploy the compose-file as swarm stack;

```bash
docker stack deploy -c compose.yml repro-1148

Creating network repro-1148_default
Creating service repro-1148_web
```

```bash
docker container inspect  --format '{{ json .HostConfig.LogConfig }}' repro-1148_web.1.jyyc9wo6iklxdk5sdrpsu9ogj | jq .

{
  "Type": "json-file",
  "Config": {
    "max-file": "5",
    "max-size": "1m"
  }
}
```

**Comment by MondaySam** [comment] 2020-05-19 10:13
Nevermind. I'm stupid and wasn't fast enough to delete/revise my comment here. 
Sorry to have bothered you.
Hope you are healthy and doing fine!

**Comment by HendrixSimon** [comment] 2020-06-18 12:36
Hi,
I'm on Docker version 19.03.6 and am still experiencing the issue that docker would just log without constraints. Options are
```
logging:
    driver: json-file
    options:
        max-size: "50m"
        max-file: "3"
```
inspect shows:
```
"LogConfig": {
    "Type": "json-file",
    "Config": {
        "max-file": "3",
        "max-size": "50m"
    }
}
```
However, the log file still exceeds these limits and goes into gigabytes.
Anything I am missing?

**Comment by MondaySam** [comment] 2020-06-18 12:38
The solution to my problem was rather simple.
Docker restart is simply not enough.
If the container was already running after you added the log rotation, you must use docker up -d again.

**Comment by HendrixSimon** [comment] 2020-06-18 12:58
The container was completely recreated, but the issue still persists.
Also I updated to 19.03.11. Same issue.

**Comment by yifeikong** [comment] 2020-11-18 09:05
I can confirm that you have to recreate the container to make existing containers work. This should be added to the docs.

docker version: Docker version 19.03.12, build 48a66213fe

**Comment by jvleminc** [comment] 2021-02-04 21:53
Can confirm: Difference after container restarts, when on one container I had done a `docker rm -f` beforehand and on the other one not:

```
$ docker inspect prometheus_server| grep -B 0 -A 6 LogConfig
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "3",
                    "max-size": "50m"
                }
            },
docker inspect nova_compute| grep -B 0 -A 6 LogConfig
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": null,
            "RestartPolicy": {
```

**Comment by migutak** [comment] 2021-05-20 10:08
Was there a solution to this. I am facing the same problem

**Comment by MondaySam** [comment] 2021-05-20 10:14
> Was there a solution to this. I am facing the same problem
Yes. You need to recreate the container. 
Docker restart does not suffice here.
https://github.com/docker/cli/issues/1148#issuecomment-729539456

**Comment by nyetwurk** [comment] 2022-07-31 06:39
```
$ cat /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "9"
  }
}
```

```
$ docker inspect <container> | jq .[].HostConfig.LogConfig
{
  "Type": "json-file",
  "Config": {}
}
```

**Comment by KES777** [comment] 2024-01-03 00:46
> I can confirm that you have to recreate the container to make existing containers work. This should be added to the docs.
> 
> docker version: Docker version 19.03.12, build 48a66213fe

Was it added to the docs?

**Comment by aiwell-ac5000** [comment] 2024-08-09 08:25
> > Was there a solution to this. I am facing the same problem
> 
> Yes. You need to recreate the container. Docker restart does not suffice here. [#1148 (comment)](https://github.com/docker/cli/issues/1148#issuecomment-645990725) + [#1148 (comment)](https://github.com/docker/cli/issues/1148#issuecomment-729539456)

This is not a solution. We have been using the same configuration on multiple identical devices. Sometimes rotation works, and sometimes it doesn't.

```
$ docker inspect <container> | jq .[].HostConfig.LogConfig
{
  "Type": "json-file",
  "Config": {
    "max-file": "1",
    "max-size": "10m"
  }
}
```
It is only when the log grows that we know if it works.

**Comment by vvoland** [comment] 2024-08-09 08:40
There's a mention of the `local` logging driver in our docs now: https://docs.docker.com/config/containers/logging/configure/

**Comment by aiwell-ac5000** [comment] 2024-08-09 09:00
> There's a mention of the `local` logging driver in our docs now: [https://docs.docker.com/config/containers/logging/configure/](https://docs.docker.com/config/containers/logging/configure/)

We are testing that now. So far the issue has only occurred with the json-file driver. Hard to reproduce, since it appears random. Devices are ARM-based with cloned images. Storage is limited.
