### ISSUE TITLE
Feature Request: docker image fetch-tags

### ISSUE THREAD

**Issue by castarco** [docker/cli#836] opened 2018-01-26 14:55 UTC
## Feature request

Create a docker subcommand `docker image fetch-tags [[[image_name] image_name] ...]` to download all the missing tags pointing to locally available versions of the pulled images.

If `image_name` is provided, restrict the fetch operation only to the specified images.

### Use case

Suppose we have an image named `my_service` , and tagged with `1.0`. As an extra supposition, `1.0` refers to the version of the main packaged software, but we may want to have more fine grained versions also for the image version (because we may introduce build improvements without changing the version of the packaged software). So we may have two tags to the same image:

  *  `my_service:1.0`, with hash `abcdef0123456789`
  *  `my_service:1.0_35`, with hash `abcdef0123456789`
  *  `my_service:1.0_34`, with hash `0123456789abcdef`

This is what we have in the docker registry, but in the client-side our picture can be different. A lot of people will directly use the "generic" tag (`1.0`), which is good if the containers are short-lived, but could be problematic if containers are long-lived.

When someone performs a pull operation, a new version of the image is downloaded, the generic tag points to the new image, and all the containers using the old tag lose their tag, so it becomes more difficult to understand which image is the base of these containers (because we only have the image hash, but not its tag). This also happens for the images themselves when we type `docker image ls`, we can see the image name, but not its tag because it gets lost).

### Potential problems that could arise if the feature gets implemented

Of course, fetching tags comes with its own potential problems: more tags imply more work when we want to get rid of useless downloaded images (at least if you don't master the tooling). 

This isn't critical since the usage of the feature is completely optional.

### Other ways to go

Add a `--fetch-tags` (not the same as `--all-tags`!) option to the `docker pull` command. It should be documented that this option only fetches the tags (the pointers, not the content) for the already downloaded images.

### Related & interesting potential feature: "Weak/Implicit fetched tags"

An extra interesting & related feature could be to distinguish between explicitly pulled tags and implicitly fetched tags (as some package managers do for some packages, like APT in Debian). Why? Because the implicitly fetched tags could act as weak references, if the "hard" pointers disappear, then the "weak" pointers disappear too, making more easy to maintain the list of locally available images.

**Comment by dnephin** [comment] 2018-01-26 20:06
If the problem is just to keep track of the tag used to create an image I would suggest using a `--label` to document the image tag (or even better, also document the software version instead that is running in the image). Another option is to use a more specific label that isn't going to change.

Adding another command `image fetch-tags` isn't a good option, it is too similar to `pull`.

`pull --fetch-tags` is slightly better, but is still very similar to `--all-tags`.

I don't think `--fetch-tags` actually fixes the problem. At any time someone could `docker pull image:1` and you'd be in the same situation. Using an image label or immutable tags is more reliable.

**Comment by mrchapp** [comment] 2018-02-27 17:40
My approach to this use case is with `docker pull image`, which will get the latest version of the image. The recommended way to upgrade is to `docker pull image` again when a new version is out, so, after a while, `docker ps -a` gives a list of meaningless hashes that don't really tell what version those instances ran from.

`docker pull --tags image` would be a great way to fetch those tags to pair the existing (local) hashes with published versions.

**Comment by dnephin** [comment] 2018-02-27 18:06
You can already do that with `docker pull -a`.  The image data is already local so it wont be downloaded again.

**Comment by dnephin** [comment] 2018-02-27 18:10
> It should be documented that this option only fetches the tags (the pointers, not the content) for the already downloaded images.

This is already the behaviour of `-a`. If you have the content it wont download it again.

I'm going to close this issue as I believe `docker pull -a` already does what you want. If you disagree, please do comment.

**Closed by dnephin** 2018-02-27 18:10 UTC
Labels: area/distribution

**Comment by mrchapp** [comment] 2018-02-27 18:43
That's not at all what I'd want:
```
$ docker images homeassistant/home-assistant
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
homeassistant/home-assistant   latest              2d4a31952029        44 hours ago        1.64GB
homeassistant/home-assistant   <none>              cfc772d4dc3a        4 weeks ago         1.54GB
homeassistant/home-assistant   <none>              04d0d1debd6a        7 weeks ago         1.65GB
```

Matching those images (those worked for me, I liked them) against a released tag is not exactly easy.

This is `docker pull -a homeassistant/home-assistant`:
```
$ docker pull -a homeassistant/home-assistant
0.14.2: Pulling from homeassistant/home-assistant
efd26ecc9548: Pulling fs layer 
a3ed95caeb02: Pulling fs layer 
d1784d73276e: Pulling fs layer 
72e581645fc3: Waiting
[...] ^C
```
There is no way to fetch the tags without pulling all of the published versions, which in some cases would be insane. In order to get the tag for version 0.62 I need to get 50+ images.

**Comment by dnephin** [comment] 2018-02-27 19:04
Why isn't it just `docker pull homeassistant/home-assistant:0.62` ?

**Comment by mrchapp** [comment] 2018-02-27 19:08
Because matching a local hash to a published version is not trivial. In fact, there's not knowing what version I just downloaded with `git pull jenkins/jenkins:lts` until an instance of that image is launched.
A way to fetch the tags (not the images) would be tremendously helpful.

**Comment by dnephin** [comment] 2018-02-27 19:28
I don't think there is any way to query the registry by image ID. I believe the registry stores things by named reference and by digest. The image ID is there, but not indexed. If you want the tag you can always pull using the tag. 

Since this is a feature that would require changes to multiple components (engine and registry) I would suggest a feature request be opened on `docker/for-linux` (https://github.com/docker/docker-ce#issues).

As a workaround you can pull the specific tag you want to run, or use labels to tag the image with important details (like software version).

**Comment by castarco** [comment] 2018-02-28 09:39
I don't think that there are valid reasons to close this issue given the current feedback. Even if there are multiple involved components.

**Comment by C180257** [comment] 2019-11-21 02:33
Why would you close this issue without addressing it? it's perfectly valid!

**Comment by sabik** [comment] 2021-01-06 01:29
+1 on this feature request.

Expected usage:
```
$ docker pull --fetch-tags nginx:latest
...
$ docker inspect --format='{{.RepoTags}}' nginx:latest
[nginx:1 nginx:1.19 nginx:1.19.6 nginx:latest nginx:mainline]
```

Currently, the options are:
* use ``docker pull --all-tags nginx`` which pulls a large number of obsolete or otherwise irrelevant versions of nginx; or
* manually list the tags via the REST API (per [this StackOverflow answer](https://stackoverflow.com/a/52942903/683329)), then `docker pull $image:$tag` for each tag with the same digest.

Since the tag list is already available via the REST API, no change to the backend should be needed; only the `docker pull` command itself would have to be extended to pull the relevant metadata.

**Comment by thaJeztah** [comment] 2021-01-11 12:49
Let me cross-post my reply on  here; https://github.com/docker/for-linux/issues/455#issuecomment-755223150

> If you have Docker Desktop installed, you can use the `hub-tool` utility that's currently in preview (still beta, and both UX and name will likely change); https://www.docker.com/blog/docker-hub-experimental-cli-tool/
> 
> ```
> $ hub-tool tag ls --sort updated nginx
> 
> TAG                           DIGEST                                                                     STATUS    LAST UPDATE      LAST PUSHED    LAST PULLED       SIZE
> nginx:stable-alpine-perl      sha256:0c85226446a083d92fbf432faee51d12933eafdcf13eb0b7d06fc465368ae908    active    2 weeks ago      2 weeks        3 minutes         124.8MB
> nginx:stable-alpine           sha256:da3716611fb965f3fda1f3281882baeb2760ca8bb7317f1d22ed45e75570827b    active    2 weeks ago      2 weeks        5 minutes         64.99MB
> nginx:mainline-alpine-perl    sha256:65f87cf0859fc1de79c1346ce9b7b7ecb4abb6042339a6b696fc08309453d74c    active    2 weeks ago      2 weeks        21 minutes        126.3MB
> nginx:mainline-alpine         sha256:55533d629d34a30401be42a186c2d7f6338feb808e42a3b40f40faf3f99b5596    active    2 weeks ago      2 weeks        2 minutes         66.49MB
> nginx:alpine-perl             sha256:4737b313d0297ec1a570279002be57c4440ba229b6937a9a3e54775823d3f17f    active    2 weeks ago      2 weeks        21 minutes        126.3MB
> nginx:alpine                  sha256:50bf829ce093e6a1b5e244a9017bb8679590344332f01f8d1eb947877c9a3694    active    2 weeks ago      2 weeks        2 minutes         66.49MB
> nginx:1.19.6-alpine-perl      sha256:63a230880775f228250a85db638626f1d5c323bbf4b18014dd2e0e9f616ee746    active    2 weeks ago      2 weeks        21 minutes        126.3MB
> nginx:1.19.6-alpine           sha256:336994e7a9b771908b905b1c0124e11895780b0e3af50075a2014063b3292bfd    active    2 weeks ago      2 weeks        2 minutes         66.49MB
> nginx:1.19-alpine-perl        sha256:e431b86f520afaf3e800e15b428e969f67eecb34b85bae5c25fbc0bddf519ce2    active    2 weeks ago      2 weeks        21 minutes        126.3MB
> nginx:1.19-alpine             sha256:50bf829ce093e6a1b5e244a9017bb8679590344332f01f8d1eb947877c9a3694    active    2 weeks ago      2 weeks        2 minutes         66.49MB
> nginx:1.18.0-alpine-perl      sha256:b2c101d2a7dbe9a3aa31b59a73ae9fb7dcf768502eebc75ffd61345b166271f4    active    2 weeks ago      2 weeks        3 minutes         124.8MB
> nginx:1.18.0-alpine           sha256:52e7d61873346c887de8258923a52e3f06a2f8e84caa8c9133376acd00c8da13    active    2 weeks ago      2 weeks        5 minutes         64.99MB
> nginx:1.18-alpine-perl        sha256:b2c101d2a7dbe9a3aa31b59a73ae9fb7dcf768502eebc75ffd61345b166271f4    active    2 weeks ago      2 weeks        3 minutes         124.8MB
> nginx:1.18-alpine             sha256:a41846b6a41f298784b7dd9925d0b6649794d47244fe01e17b7f9ad8af344494    active    2 weeks ago      2 weeks        5 minutes         64.99MB
> nginx:1-alpine-perl           sha256:71c78821092dcb3764fae2d1e6d78fc38417f7dc486451125efaa06563165a44    active    2 weeks ago      2 weeks        21 minutes        126.3MB
> nginx:1-alpine                sha256:d152c79d06eeb7d7acd4041f47b8c71ef93e52b2f6fa70aee4e0fc365bdc475d    active    2 weeks ago      2 weeks        2 minutes         66.49MB
> nginx:perl                    sha256:b7d135f454cb7e64cc0189b23dca7c72523689db7245f2bc381782b30c4bbade    active    3 weeks ago      3 weeks        9 minutes         506.4MB
> nginx:mainline-perl           sha256:29934d835af32d2af4156df8676d420e0471234634f42c2a241f62fdd79c9278    active    3 weeks ago      3 weeks        9 minutes         506.4MB
> 
> ...
> ```

**Comment by diversario** [comment] 2021-01-26 08:28
The `hub-tool` is nice, but does not seem to work for privately hosted registries (at least there's nothing in the help about it).

**Comment by silvin-lubecki** [comment] 2021-01-26 09:15
No indeed, the `hub-tool` uses the Hub API to list the tags, so it works only with Docker Hub.

**Comment by thaJeztah** [comment] 2021-01-26 09:31
The Docker Hub API provides more metadata that is not available on other registries. The "distribution spec" (specification for OCI registries) allows listing tags, but does not provide additional metadata, e.g., the "tags" list returned by other registries only returns the list of tags, but not other details; https://github.com/opencontainers/distribution-spec/blob/v1.0.0-rc1/spec.md#content-discovery
