### ISSUE TITLE
Docker cli command to view log size of containers

### ISSUE THREAD

**Issue by davidnateberg** [docker/cli#3714] opened 2022-07-20 15:15 UTC
**Description**
Recently I was troubleshooting and issue with disk space being taken up by docker. I did all the various `docker system df` commands but nothing indicated that the docker container was taking up the 40gb of space like filesystem showed it was. After some digging into the docker file system itself, I realized it was the log file for the container that was taking up all the space. I think there should be a docker log command to show log sizes for a container. Or that should be included in the `docker system df` command somehow. Theres just not a lot of insight into the log file and its a little obscured. The easiest way I've found to show it is with this command:

`sudo du -h $(docker inspect --format='{{.LogPath}}' $(docker ps -qa))`

But a built in docker cli command would be helpful. Thanks.

**Comment by thaJeztah** [comment] 2022-07-21 11:11
Thanks for opening this ticket; this looks something to be implemented in the daemon (as the cli may be connected with a remote daemon, so the files may not be on the local machine).

There's some existing tickets that look to be a duplicate of this;

- https://github.com/moby/moby/issues/38341
- (slightly overlaps) https://github.com/moby/moby/issues/32205
- https://github.com/moby/moby/issues/38848

Let me close this ticket as a duplicate of those to prevent the conversation from diverging, but feel free to participate in those tickets 👍

**Closed by thaJeztah** 2022-07-21 11:11 UTC
Labels: kind/feature, area/runtime
