### ISSUE TITLE
Another "failed to start daemon: Devices cgroup isn't mounted" problem on CentOS 7.7

### ISSUE THREAD

**Issue by gavin310** [docker/cli#2369] opened 2020-03-02 16:27 UTC
**Description**

This is the same problem as #2104 but nothing I'm doing is fixing it. I have the latest version of Docker.

**Steps to reproduce the issue:**
1. I didn't have any kernel files in /boot nor did I have any grub files, so I did a "yum install kernel" then used `grub2-mkconfig -o /boot/grub/grub.cfg` to build the grub file.
2. I ran `grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"` and also created the file `/etc/default/grub` and included `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"` in that file, then generated the grub.cfg file again.
3. I restarted the server to be safe, but still when I try to start docker using `sudo systemctl start docker` I get the `failed to start daemon: Devices cgroup isn't mounted` error.

Nothing is fixing this problem and I have no idea how to get Docker working.

**Comment by amd3963** [comment] 2020-04-14 21:03
I am having the same issue.  Trying to do docker inside a LXD Centos 7.7 container.  I ran the grubby command above and am still getting the same error "failed to start daemon: Devices cgroup isn't mounted".

**Comment by thaJeztah** [comment] 2020-06-15 14:17
closing as duplicate of https://github.com/docker/cli/issues/2104

you can also run the `check-config.sh` script to see if things are possibly missing in your environment; https://github.com/moby/moby/blob/master/contrib/check-config.sh

**Closed by thaJeztah** 2020-06-15 14:17 UTC

**Comment by gavin310** [comment] 2020-06-15 17:58
I just wanted to add, the reason I was having this issue is because of my web host. I was on a Media Temple dedicated server and apparently they don't allow docker. I also found out that Media Temple is owned by GoDaddy. I'm much happier on DigitalOcean now and docker is running just fine.
