### ISSUE TITLE
macOS fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by kaosagnt** [docker/cli#3595] opened 2022-05-09 00:49 UTC
**Description**

20.10.15 on macOS 11.6.5 x86_64

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2062bc9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2062bc9e
stack: frame={sp:0x7ffee3a90828, fp:0x7ffee3a90878} stack=[0x7ffee3a118c8,0x7ffee3a90930)
0x00007ffee3a90728:  0x01007ffee3a90748  0x0000000100000004 
0x00007ffee3a90738:  0x000000000000001f  0x00007fff2062bc9e 
0x00007ffee3a90748:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffee3a90758:  0x000000010c1a4451 <runtime.throw+0x0000000000000071>  0x00007ffee3a907f8 
0x00007ffee3a90768:  0x000000010d477b71  0x00007ffee3a907b0 
0x00007ffee3a90778:  0x000000010c1a4708 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000010e9acae0 
0x00007ffee3a90788:  0x0000000000000001  0x0000000000000001 
0x00007ffee3a90798:  0x00007ffee3a907f8  0x000000010c1a4451 <runtime.throw+0x0000000000000071> 
0x00007ffee3a907a8:  0x000000010e9acae0  0x00007ffee3a907e8 
0x00007ffee3a907b8:  0x000000010c1a4690 <runtime.fatalthrow+0x0000000000000050>  0x00007ffee3a907c8 
0x00007ffee3a907c8:  0x000000010c1a46c0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000010e9acae0 
0x00007ffee3a907d8:  0x000000010c1a4451 <runtime.throw+0x0000000000000071>  0x00007ffee3a907f8 
0x00007ffee3a907e8:  0x00007ffee3a90818  0x000000010c1a4451 <runtime.throw+0x0000000000000071> 
0x00007ffee3a907f8:  0x00007ffee3a90800  0x000000010c1a4480 <runtime.throw.func1+0x0000000000000000> 
0x00007ffee3a90808:  0x000000010d491e40  0x000000000000002a 
0x00007ffee3a90818:  0x00007ffee3a90868  0x000000010c1b9fd6 <runtime.sigpanic+0x0000000000000396> 
0x00007ffee3a90828: <0x000000010d491e40  0x000000c000370000 
0x00007ffee3a90838:  0x00007ffee3a908a8  0x000000010c196546 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffee3a90848:  0x000000c000370000  0x0000000000006000 
0x00007ffee3a90858:  0x000000c000000008  0x0000000000000000 
0x00007ffee3a90868:  0x00007ffee3a908b0 !0x00007fff2062bc9e 
0x00007ffee3a90878: >0x00007ffee3a908b0  0x000000010e8f7028 
0x00007ffee3a90888:  0x00000000000004dd  0x000000010c29ac65 <github.com/docker/cli/vendor/golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffee3a90898:  0x000000010c1d711f <runtime.syscall+0x000000000000001f>  0x000000c00061fda0 
0x00007ffee3a908a8:  0x00007ffee3a908f0  0x000000c00061fd70 
0x00007ffee3a908b8:  0x000000010c1d4f70 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000003 
0x00007ffee3a908c8:  0x000000010c175a00 <runtime.sendDirect+0x0000000000000000>  0x5a00000000001018 
0x00007ffee3a908d8:  0x0000000000000000  0x000000010e9e21b8 
0x00007ffee3a908e8:  0x00000000000002b8  0x000000c0000001a0 
0x00007ffee3a908f8:  0x000000010c1d3089 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffee3a90908:  0x000000010da578e0  0x000000010e9acae0 
0x00007ffee3a90918:  0x00007ffee3a90960  0x000000010c1d2f85 <runtime.mstart+0x0000000000000005> 
0x00007ffee3a90928:  0x000000010c1d2f3d <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x10d491e40, 0xc000370000})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2062bc9e
stack: frame={sp:0x7ffee3a90828, fp:0x7ffee3a90878} stack=[0x7ffee3a118c8,0x7ffee3a90930)
0x00007ffee3a90728:  0x01007ffee3a90748  0x0000000100000004 
0x00007ffee3a90738:  0x000000000000001f  0x00007fff2062bc9e 
0x00007ffee3a90748:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffee3a90758:  0x000000010c1a4451 <runtime.throw+0x0000000000000071>  0x00007ffee3a907f8 
0x00007ffee3a90768:  0x000000010d477b71  0x00007ffee3a907b0 
0x00007ffee3a90778:  0x000000010c1a4708 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000010e9acae0 
0x00007ffee3a90788:  0x0000000000000001  0x0000000000000001 
0x00007ffee3a90798:  0x00007ffee3a907f8  0x000000010c1a4451 <runtime.throw+0x0000000000000071> 
0x00007ffee3a907a8:  0x000000010e9acae0  0x00007ffee3a907e8 
0x00007ffee3a907b8:  0x000000010c1a4690 <runtime.fatalthrow+0x0000000000000050>  0x00007ffee3a907c8 
0x00007ffee3a907c8:  0x000000010c1a46c0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000010e9acae0 
0x00007ffee3a907d8:  0x000000010c1a4451 <runtime.throw+0x0000000000000071>  0x00007ffee3a907f8 
0x00007ffee3a907e8:  0x00007ffee3a90818  0x000000010c1a4451 <runtime.throw+0x0000000000000071> 
0x00007ffee3a907f8:  0x00007ffee3a90800  0x000000010c1a4480 <runtime.throw.func1+0x0000000000000000> 
0x00007ffee3a90808:  0x000000010d491e40  0x000000000000002a 
0x00007ffee3a90818:  0x00007ffee3a90868  0x000000010c1b9fd6 <runtime.sigpanic+0x0000000000000396> 
0x00007ffee3a90828: <0x000000010d491e40  0x000000c000370000 
0x00007ffee3a90838:  0x00007ffee3a908a8  0x000000010c196546 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffee3a90848:  0x000000c000370000  0x0000000000006000 
0x00007ffee3a90858:  0x000000c000000008  0x0000000000000000 
0x00007ffee3a90868:  0x00007ffee3a908b0 !0x00007fff2062bc9e 
0x00007ffee3a90878: >0x00007ffee3a908b0  0x000000010e8f7028 
0x00007ffee3a90888:  0x00000000000004dd  0x000000010c29ac65 <github.com/docker/cli/vendor/golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffee3a90898:  0x000000010c1d711f <runtime.syscall+0x000000000000001f>  0x000000c00061fda0 
0x00007ffee3a908a8:  0x00007ffee3a908f0  0x000000c00061fd70 
0x00007ffee3a908b8:  0x000000010c1d4f70 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000003 
0x00007ffee3a908c8:  0x000000010c175a00 <runtime.sendDirect+0x0000000000000000>  0x5a00000000001018 
0x00007ffee3a908d8:  0x0000000000000000  0x000000010e9e21b8 
0x00007ffee3a908e8:  0x00000000000002b8  0x000000c0000001a0 
0x00007ffee3a908f8:  0x000000010c1d3089 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffee3a90908:  0x000000010da578e0  0x000000010e9acae0 
0x00007ffee3a90918:  0x00007ffee3a90960  0x000000010c1d2f85 <runtime.mstart+0x0000000000000005> 
0x00007ffee3a90928:  0x000000010c1d2f3d <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
syscall.syscall(0x10c29ac60, 0x0, 0x40487413, 0xc0000580f0)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc00061fda0 sp=0xc00061fd80 pc=0x10c1d1b3b
syscall.syscall(0x10c17d247, 0x48, 0x10d97a380, 0x1)
	<autogenerated>:1 +0x26 fp=0xc00061fde8 sp=0xc00061fda0 pc=0x10c1d78e6
github.com/docker/cli/vendor/golang.org/x/sys/unix.ioctl(0x10d461cc0, 0x14, 0xc000258708)
	/go/src/github.com/docker/cli/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:689 +0x39 fp=0xc00061fe18 sp=0xc00061fde8 pc=0x10c29a579
github.com/docker/cli/vendor/golang.org/x/sys/unix.IoctlGetTermios(...)
	/go/src/github.com/docker/cli/vendor/golang.org/x/sys/unix/ioctl.go:72
github.com/docker/cli/vendor/github.com/moby/term.tcget(0xc00010f930)
	/go/src/github.com/docker/cli/vendor/github.com/moby/term/tc.go:10 +0x3c fp=0xc00061fe50 sp=0xc00061fe18 pc=0x10c6247dc
github.com/docker/cli/vendor/github.com/moby/term.IsTerminal(...)
	/go/src/github.com/docker/cli/vendor/github.com/moby/term/term.go:53
github.com/docker/cli/vendor/github.com/moby/term.GetFdInfo({0x10da1ae00, 0xc0001b0000})
	/go/src/github.com/docker/cli/vendor/github.com/moby/term/term.go:46 +0x6f fp=0xc00061fe78 sp=0xc00061fe50 pc=0x10c62488f
github.com/docker/cli/cli/streams.NewIn(...)
	/go/src/github.com/docker/cli/cli/streams/in.go:54
github.com/docker/cli/cli/command.NewDockerCli({0x0, 0x0, 0xc0000001a0})
	/go/src/github.com/docker/cli/cli/command/cli.go:475 +0x1c6 fp=0xc00061ff08 sp=0xc00061fe78 pc=0x10c6f10c6
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:291 +0x25 fp=0xc00061ff80 sp=0xc00061ff08 pc=0x10d441de5
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc00061ffe0 sp=0xc00061ff80 pc=0x10c1a6ae7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00061ffe8 sp=0xc00061ffe0 pc=0x10c1d5261

goroutine 50 [chan receive]:
github.com/docker/cli/vendor/k8s.io/klog.(*loggingT).flushDaemon(0xc00012c000)
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:1010 +0x6a
created by github.com/docker/cli/vendor/k8s.io/klog.init.0
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:411 +0xf4

**Steps to reproduce the issue:**
1. Download the 20.10.15 release of docker cli for macOS 11.x x86_64
2. Try running any docker command
3. watch it crash

**Describe the results you received:**

segmentation violation

**Describe the results you expected:**

At least the equivalent of 20.10.14 + whatever changes are in 20.10.15
without crashing

kristamari-w1:/usr/local/bin>./docker-test2 version
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:49:20 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
kristamari-w1:/usr/local/bin>./docker-test version
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2062bc9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2062bc9e
stack: frame={sp:0x7ffee2856828, fp:0x7ffee2856878} stack=[0x7ffee27d78c8,0x7ffee2856930)
0x00007ffee2856728:  0x01007ffee2856748  0x0000000100000004 
0x00007ffee2856738:  0x000000000000001f  0x00007fff2062bc9e 
0x00007ffee2856748:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffee2856758:  0x000000010d3de451 <runtime.throw+0x0000000000000071>  0x00007ffee28567f8 
0x00007ffee2856768:  0x000000010e6b1b71  0x00007ffee28567b0 
0x00007ffee2856778:  0x000000010d3de708 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000010fbe6ae0 
0x00007ffee2856788:  0x0000000000000001  0x0000000000000001 
0x00007ffee2856798:  0x00007ffee28567f8  0x000000010d3de451 <runtime.throw+0x0000000000000071> 
0x00007ffee28567a8:  0x000000010fbe6ae0  0x00007ffee28567e8 
0x00007ffee28567b8:  0x000000010d3de690 <runtime.fatalthrow+0x0000000000000050>  0x00007ffee28567c8 
0x00007ffee28567c8:  0x000000010d3de6c0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000010fbe6ae0 
0x00007ffee28567d8:  0x000000010d3de451 <runtime.throw+0x0000000000000071>  0x00007ffee28567f8 
0x00007ffee28567e8:  0x00007ffee2856818  0x000000010d3de451 <runtime.throw+0x0000000000000071> 
0x00007ffee28567f8:  0x00007ffee2856800  0x000000010d3de480 <runtime.throw.func1+0x0000000000000000> 
0x00007ffee2856808:  0x000000010e6cbe40  0x000000000000002a 
0x00007ffee2856818:  0x00007ffee2856868  0x000000010d3f3fd6 <runtime.sigpanic+0x0000000000000396> 
0x00007ffee2856828: <0x000000010e6cbe40  0x000000010fbe6ae0 
0x00007ffee2856838:  0x00007ffee28568a8  0x000000010d3d0546 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffee2856848:  0x000000010fc006c0  0x0000000000000003 
0x00007ffee2856858:  0x000000c00061f6f8  0x0000000000000000 
0x00007ffee2856868:  0x00007ffee28568b0 !0x00007fff2062bc9e 
0x00007ffee2856878: >0x00007ffee28568b0  0x000000010fb31028 
0x00007ffee2856888:  0x00000000000004dd  0x000000010d4d4c65 <github.com/docker/cli/vendor/golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffee2856898:  0x000000010d41111f <runtime.syscall+0x000000000000001f>  0x000000c00061fda0 
0x00007ffee28568a8:  0x00007ffee28568f0  0x000000c00061fd70 
0x00007ffee28568b8:  0x000000010d40ef70 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffee28568c8:  0x000000010d3b5800 <runtime.notetsleep_internal+0x00000000000001a0>  0x5800000000001018 
0x00007ffee28568d8:  0x0000000000000000  0x000000010fc1c1b8 
0x00007ffee28568e8:  0x00000000000002b8  0x000000c0000001a0 
0x00007ffee28568f8:  0x000000010d40d089 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffee2856908:  0x000000010ec918e0  0x000000010fbe6ae0 
0x00007ffee2856918:  0x00007ffee2856960  0x000000010d40cf85 <runtime.mstart+0x0000000000000005> 
0x00007ffee2856928:  0x000000010d40cf3d <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x10e6cbe40, 0x10fbe6ae0})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2062bc9e
stack: frame={sp:0x7ffee2856828, fp:0x7ffee2856878} stack=[0x7ffee27d78c8,0x7ffee2856930)
0x00007ffee2856728:  0x01007ffee2856748  0x0000000100000004 
0x00007ffee2856738:  0x000000000000001f  0x00007fff2062bc9e 
0x00007ffee2856748:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffee2856758:  0x000000010d3de451 <runtime.throw+0x0000000000000071>  0x00007ffee28567f8 
0x00007ffee2856768:  0x000000010e6b1b71  0x00007ffee28567b0 
0x00007ffee2856778:  0x000000010d3de708 <runtime.fatalthrow.func1+0x0000000000000048>  0x000000010fbe6ae0 
0x00007ffee2856788:  0x0000000000000001  0x0000000000000001 
0x00007ffee2856798:  0x00007ffee28567f8  0x000000010d3de451 <runtime.throw+0x0000000000000071> 
0x00007ffee28567a8:  0x000000010fbe6ae0  0x00007ffee28567e8 
0x00007ffee28567b8:  0x000000010d3de690 <runtime.fatalthrow+0x0000000000000050>  0x00007ffee28567c8 
0x00007ffee28567c8:  0x000000010d3de6c0 <runtime.fatalthrow.func1+0x0000000000000000>  0x000000010fbe6ae0 
0x00007ffee28567d8:  0x000000010d3de451 <runtime.throw+0x0000000000000071>  0x00007ffee28567f8 
0x00007ffee28567e8:  0x00007ffee2856818  0x000000010d3de451 <runtime.throw+0x0000000000000071> 
0x00007ffee28567f8:  0x00007ffee2856800  0x000000010d3de480 <runtime.throw.func1+0x0000000000000000> 
0x00007ffee2856808:  0x000000010e6cbe40  0x000000000000002a 
0x00007ffee2856818:  0x00007ffee2856868  0x000000010d3f3fd6 <runtime.sigpanic+0x0000000000000396> 
0x00007ffee2856828: <0x000000010e6cbe40  0x000000010fbe6ae0 
0x00007ffee2856838:  0x00007ffee28568a8  0x000000010d3d0546 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffee2856848:  0x000000010fc006c0  0x0000000000000003 
0x00007ffee2856858:  0x000000c00061f6f8  0x0000000000000000 
0x00007ffee2856868:  0x00007ffee28568b0 !0x00007fff2062bc9e 
0x00007ffee2856878: >0x00007ffee28568b0  0x000000010fb31028 
0x00007ffee2856888:  0x00000000000004dd  0x000000010d4d4c65 <github.com/docker/cli/vendor/golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffee2856898:  0x000000010d41111f <runtime.syscall+0x000000000000001f>  0x000000c00061fda0 
0x00007ffee28568a8:  0x00007ffee28568f0  0x000000c00061fd70 
0x00007ffee28568b8:  0x000000010d40ef70 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffee28568c8:  0x000000010d3b5800 <runtime.notetsleep_internal+0x00000000000001a0>  0x5800000000001018 
0x00007ffee28568d8:  0x0000000000000000  0x000000010fc1c1b8 
0x00007ffee28568e8:  0x00000000000002b8  0x000000c0000001a0 
0x00007ffee28568f8:  0x000000010d40d089 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffee2856908:  0x000000010ec918e0  0x000000010fbe6ae0 
0x00007ffee2856918:  0x00007ffee2856960  0x000000010d40cf85 <runtime.mstart+0x0000000000000005> 
0x00007ffee2856928:  0x000000010d40cf3d <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
syscall.syscall(0x10d4d4c60, 0x0, 0x40487413, 0xc000158140)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc00061fda0 sp=0xc00061fd80 pc=0x10d40bb3b
syscall.syscall(0x10d3b7247, 0x48, 0x10ebb4380, 0x1)
	<autogenerated>:1 +0x26 fp=0xc00061fde8 sp=0xc00061fda0 pc=0x10d4118e6
github.com/docker/cli/vendor/golang.org/x/sys/unix.ioctl(0x10e69bcc0, 0x14, 0xc000815008)
	/go/src/github.com/docker/cli/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:689 +0x39 fp=0xc00061fe18 sp=0xc00061fde8 pc=0x10d4d4579
github.com/docker/cli/vendor/golang.org/x/sys/unix.IoctlGetTermios(...)
	/go/src/github.com/docker/cli/vendor/golang.org/x/sys/unix/ioctl.go:72
github.com/docker/cli/vendor/github.com/moby/term.tcget(0xc00048da00)
	/go/src/github.com/docker/cli/vendor/github.com/moby/term/tc.go:10 +0x3c fp=0xc00061fe50 sp=0xc00061fe18 pc=0x10d85e7dc
github.com/docker/cli/vendor/github.com/moby/term.IsTerminal(...)
	/go/src/github.com/docker/cli/vendor/github.com/moby/term/term.go:53
github.com/docker/cli/vendor/github.com/moby/term.GetFdInfo({0x10ec54e00, 0xc00012e000})
	/go/src/github.com/docker/cli/vendor/github.com/moby/term/term.go:46 +0x6f fp=0xc00061fe78 sp=0xc00061fe50 pc=0x10d85e88f
github.com/docker/cli/cli/streams.NewIn(...)
	/go/src/github.com/docker/cli/cli/streams/in.go:54
github.com/docker/cli/cli/command.NewDockerCli({0x0, 0x0, 0xc0000001a0})
	/go/src/github.com/docker/cli/cli/command/cli.go:475 +0x1c6 fp=0xc00061ff08 sp=0xc00061fe78 pc=0x10d92b0c6
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:291 +0x25 fp=0xc00061ff80 sp=0xc00061ff08 pc=0x10e67bde5
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc00061ffe0 sp=0xc00061ff80 pc=0x10d3e0ae7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00061ffe8 sp=0xc00061ffe0 pc=0x10d40f261

goroutine 6 [chan receive]:
github.com/docker/cli/vendor/k8s.io/klog.(*loggingT).flushDaemon(0xc0000a4060)
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:1010 +0x6a
created by github.com/docker/cli/vendor/k8s.io/klog.init.0
	/go/src/github.com/docker/cli/vendor/k8s.io/klog/klog.go:411 +0xf4
```

**Output of `docker info`:**

```
See above seg fault.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2022-05-10 09:09
Thanks for reporting! Yes, we found out there's a regression in the 20.10.15 binaries for macOS (other platforms don't have this issue), and a fix was merged in https://github.com/docker/cli/pull/3592 to address this.

We'll be doing a follow-up patch release (20.10.16) with this fix included (we actually already built packages, but were waiting for another fix to land in the daemon code).

In the meantime, you can continue using the 20.10.14 version of the cli (there were no significant fixes in the CLI code for 20.10.15).

I'll close this ticket, because the fix for this has been merged (and our issue tracker tracks the source code, not releases), but feel free to continue the conversation.

I'll also open a PR to add a note in the release notes at docs.docker.com 👍

**Closed by thaJeztah** 2022-05-10 09:09 UTC
Labels: kind/bug, version/20.10
