### ISSUE TITLE
Python ------ docker build error in docker file "RUN pip install shioaji"

### ISSUE THREAD

**Issue by superdavid0816** [docker/cli#4227] opened 2023-04-25 04:06 UTC
### Description

Hi, thanks for your help.
I have a python file. I want to build it into image.

I use Mac M2, use pipenv switch to Python 3.7.16, and switch to arch=x86_64
I can user "pip install shioaji" in terminal.
But during docker build, in dockerfile "RUN pip install shioaji" got error
```
------                                                                          
#9 8.279 ERROR: Could not find a version that satisfies the requirement shioaji (from versions: none)
#9 8.280 ERROR: No matching distribution found for shioaji           
------
```

shioaji is here
https://pypi.org/project/shioaji/

Why would this happen and How to pass this?

here is the docker file

```dockerfile
FROM python:3.7-slim

WORKDIR /app

ADD . /app

RUN pip install --upgrade pip

RUN pip install Flask==2.2.3
RUN pip install flask-cors==3.0.10
RUN pip install python-dateutil
RUN pip install shioaji


COPY . .

EXPOSE 80

CMD [ "python3", "qryShioaji.py" ]
```

Thank you.

**Comment by akerouanton** [comment] 2023-04-25 10:21
Hi @superdavid0816, I'm not sure to get what you mean here:

> switch to arch=x86_64

What does your `docker build` command looks like? Are you setting the `--platform` flag? I think pip can't find the dependency due to the platform mismatch.

Also, note that this Python dependency is available as an image on DockerHub (see [here](https://hub.docker.com/r/sinotrade/shioaji)). This image seems to be available only for `linux/amd64`. You can rewrite your Dockerfile to use that base image.

By the way, I see that you use both `ADD` and `COPY` to copy your source code into your image, that's not needed. It's also a good practice to install dependencies _before_ copying source code, use a single `RUN` instruction to tie together related dependencies, and finally remove cache at the end of each `RUN` instruction.

```dockerfile
FROM sinotrade/shioaji:1.1.2

RUN pip install --upgrade pip && \
    pip install Flask==2.2.3 && \
    pip install flask-cors==3.0.10 && \
    pip install python-dateutil && \
    rm -rf ~/.cache/pip

WORKDIR /app
COPY . .

EXPOSE 80

CMD [ "python3", "qryShioaji.py" ]
```

You can read more about cache management [here](https://docs.docker.com/build/cache/).

**Comment by superdavid0816** [comment] 2023-04-26 01:50
@akerouanton 
Thanks for your answer and suggestions. 
I didn't use --platform, I will try it.
Thanks for modify the dockerfile.

Thank you very much. I will try it.

**Comment by sam-thibault** [comment] 2023-04-28 09:49
I will close this issue since this is not a bug.  I hope the added information helps you solve your issue.  Thanks @akerouanton !

**Closed by sam-thibault** 2023-04-28 09:49 UTC
Labels: kind/question, status/0-triage
