### ISSUE TITLE
Entrypoint no such file error message is misleading

### ISSUE THREAD

**Issue by GopherJ** [docker/cli#3993] opened 2023-01-30 10:48 UTC
### Description

I have the following Dockerfile

```
FROM ghcr.io/foundry-rs/foundry:nightly-31f945c09f464487d139833c668d856ef43d58cc

WORKDIR /test

COPY . /test

# https://docs.docker.com/config/containers/multi-service_container/
RUN echo '#!/bin/sh\nset -m\necho 1' > .entrypoint.sh
RUN chmod u+x .entrypoint.sh

ENTRYPOINT ["/test/.entrypoint.sh"]
```

I spent the whole afternoon debugging it:) but it's still saying `/test/.entrypoint.sh no such file`, if I run `ls` on the file it does exist. I came across https://stackoverflow.com/questions/38905135/why-wont-my-docker-entrypoint-sh-execute as well but it didn't solve anything....

### Reproduce

1. docker build  -t test:latest  .
2. docker run test:latest -d

### Expected behavior

dont output no such file

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:36:25 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:34:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.10.0-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 33
  Running: 4
  Paused: 0
  Stopped: 29
 Images: 447
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-28-generic
 Operating System: Linux Mint 21
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 31.08GiB
 Name: cj
 ID: 6VTW:KQTE:4SMP:EOGD:HYJL:XDKF:55TZ:7UE5:KEQ4:O5SM:I7ES:KQ3Q
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

nothing else

**Comment by thaJeztah** [comment] 2023-01-30 10:56
```dockerfile
RUN echo '#!/bin/sh\nset -m\necho 1' > .entrypoint.sh
```

The _cause_ of the issue probably is because `echo` does not expand newlines (`\n`); in order for it to expand the `\n` newlines, you need to use `echo -e`, or alternatively, include the actual script in your source files, and `COPY` the script into the image.


w.r.t. the error message; that looks like a duplicate of https://github.com/moby/moby/issues/29420. However, it's a difficult problem to solve, as this is the error that the kernel returns (docker itself has no real way to detect if the entrypoint script (or binary)) is valid for the container, which means that the error cannot be detected until it's executed by the runtime / kernel (`runc`).

**Comment by GopherJ** [comment] 2023-01-31 03:35
hi @thaJeztah I tried to use echo -e instead but it's still the same and finally I found the issue to be:

alphine doesn't have make & bash by default

if I use sh & install make it worked

**Closed** 2023-01-31 04:07 UTC
Labels: kind/bug, status/0-triage
