### ISSUE TITLE
Docker Push Does Not Enforce Signing Requirement

### ISSUE THREAD

**Issue by awood45** [docker/cli#2721] opened 2020-09-15 16:51 UTC
**Description**

If I run the `docker push` command, and signing fails for whatever reason, the image is successfully pushed and left unsigned. As far as my parsing of the documentation and other issues can find, there is no way to enforce a requirement that images must be successfully signed for `docker push` to complete. Even if the default behavior is to allow the unsigned push and to resolve it later, it seems to be an issue that I cannot, even through optional arguments, require that a push be signed or fail to push at all.

As a corollary issue, I really wish there was a way for me to provide a signing key passphrase through means other than STDIN for automation purposes. If this is possible, neither the documentation nor a Google search indicates any way to do this.

**Steps to reproduce the issue:**
1. Run a command like `DOCKER_CONTENT_TRUST=1 docker push $IMAGE` and intentionally enter a wrong password, or have the necessary signing root certificate not present in the trust store.

**Describe the results you received:**

The image was pushed, but not signed.

**Describe the results you expected:**

If I am setting options to require an image to be signed, push should either by default or via an opt-in option fail if signing fails, rather than silently succeeding.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 19.03.6-ce, build 369ce74
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 39
 Server Version: 19.03.6-ce
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.186-146.268.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.69GiB
 Name: REDACTED
 ID: YS5K:GHLN:5OYC:2RHB:AO4Y:ADCR:2GY5:OQ5L:NTIJ:OCXQ:KW5Y:IHTB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: REDACTED
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on AWS EC2/CodeBuild for the examples I found, but this does not seem to vary on OSX for example.

**Comment by cpuguy83** [comment] 2020-09-15 19:40
That's because the way content trust works is that the image is never directly signed.
Content trust is more saying that the image reference should point to a certain SHA, and that SHA is trusted because the signer says so.

**Comment by cpuguy83** [comment] 2020-09-15 19:41
And that data is pushed to a "trust server".

**Comment by awood45** [comment] 2020-09-15 19:47
What would be the proper way to try and achieve this behavior then? Is there a separate “sign only” command that I’m missing?

**Comment by cpuguy83** [comment] 2020-09-15 19:47
/cc @justincormack to make sure I have this straight.

Closing as this is by design.

**Comment by awood45** [comment] 2020-09-15 19:47
Essentially, I want to programmatically ensure that I’m only pushing signed images, or at least that I can programmatically recognize a signing failure and address it through another code branch.

**Comment by cpuguy83** [comment] 2020-09-15 19:48
@awood45 Docker Desktop comes with a tool called `notary` that can be used for interacting with trust data.

**Closed by cpuguy83** 2020-09-15 19:47 UTC

**Comment by cpuguy83** [comment] 2020-09-15 19:48
Oh and I forgot... the docker CLI has a subcommand for this `docker trust`

**Comment by awood45** [comment] 2020-09-15 19:59
Acknowledged that the inability to require signing for pushing images is by design. As long as I'm here, is there any way other than STDIN for scripts to provide signing key passphrases? I hate to admit and won't bore with details but this has caused far more automation headaches than I'd like to admit and I haven't found any documented alternative.

**Comment by cpuguy83** [comment] 2020-09-15 20:19
I'm not aware of how this is handled.
