### ISSUE TITLE
Another "Error starting daemon: Devices cgroup isn't mounted" but its on alpine

### ISSUE THREAD

**Issue by Geruays** [docker/cli#3285] opened 2021-09-03 13:49 UTC
I Was installing Docker

#``apk add Docker
``
#``dockerd``

And the final output its

``Error starting daemon: Devices cgroup isn't mounted``

I also tried the following command

#``docker pull hello-world``

And its say

``Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?``

**Comment by thaJeztah** [comment] 2021-09-07 06:57
The alpine packages available through apk are built and packaged by the Alpine linux distro maintainers. From the error, it looks like you may need additional packages to be installed, or to change a configuration on your system.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/cli/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

For alpine linux, you may also try the Alpine Linux community; https://alpinelinux.org/community/


I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-09-07 06:57 UTC
