### ISSUE TITLE
Find the original "docker run ..." command which created a container

### ISSUE THREAD

**Issue by shouhong** [docker/cli#1062] opened 2018-05-16 08:15 UTC
I have a docker container running in environment A. Now I need to create a new container with the same configuration in environment B. But I don't know the exact "docker run ..." command parameters I need to use.

Is there anyway to use the docker CLI to find the original "docker run ..." command which created a container? So I can use the same command to create a new container in environment B. Thanks!

**Comment by thaJeztah** [comment] 2018-05-16 16:56
No there's no such command to get the flags/options back that you used to start the container.

In general, if a container needs specific options set to run, I would recommend using a docker-compose file to start the container. That way you can define which options have to be set to start your service / container.

Having said the above, all options that are set on the container can be seen with `docker container inspect`, and you would be able to determin which flags to set to get the same configuration.

There are some projects that do this, and you can find some in an older discussion here: https://github.com/moby/moby/issues/15725 (for example, https://github.com/lavie/runlike, and https://github.com/v2tec/watchtower).

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-05-16 16:56 UTC

**Comment by tonymet** [comment] 2021-08-29 20:01
I found a tool that will re-run containers using original image & CLI options https://github.com/jdevelop/repull

**Comment by arcanemachine** [comment] 2023-05-01 08:30
There is a project (not made by me) designed to do exactly this: https://github.com/lavie/runlike
