### ISSUE TITLE
Unable to `chown` after `ADD` or `COPY` any files.

### ISSUE THREAD

**Issue by xiahualiu** [docker/cli#4498] opened 2023-08-14 18:02 UTC
### Description

In the Dockerfile, if I run `chown` after `ADD` or `COPY`, all files are still owned by `root` or `0:0`, `chown` has no effect.

### Reproduce

Create a tar ball with files:

```bash
$ touch test_file
$ tar -zcf test_file.tgz test_file
```

Create a docker file:

```Dockerfile
FROM ubuntu:16.04
RUN useradd -m -u 1001 -d /home/new_user new_user
ADD test_file.tgz /opt/
COPY test_file.tgz /etc/
RUN chown -R 1001:1001 /opt/
RUN chown 1001:1001 /etc/test_file.tgz
USER new_user
WORKDIR /home/new_user
CMD bash
```

Build the container
```bash
$ docker build -t chown-test -f Dockerfile .
```

Run the container
```bash
$ docker run --rm -it chown-test
```

Check the owners for the two files:
```bash
$ ls -al /opt/test_file
-rw-r--r-- 1 root root 0 Aug 14 17:42 /opt/test_file
$ ls -al /etc/test_file.tgz
-rw-r--r-- 1 root root 121 Aug 14 17:42 /etc/test_file.tgz
```

They are still owned by root.

### Expected behavior

The copied and added files should be owned by the user specified in the `chown` command.

### docker version

```bash
Client:
 Version:           20.10.25
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.25-0ubuntu1~22.04.1
 Built:             Fri Jul 14 21:58:09 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.25-0ubuntu1~22.04.1
  Built:            Thu Jun 29 21:21:05 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:
 runc:
  Version:          1.1.7-0ubuntu1~22.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 60
 Server Version: 20.10.25
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 5.674GiB
 Name: MLBLAPPF4B55Ek
 ID: HXB2:UEWI:XYTO:S4OD:EII6:VJ7D:7I5Y:VPZZ:FBS5:GGVX:7VIZ:KWMW
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Additional Info

Host system is Ubuntu 22.04 LTS on WSL2, Windows 10. 

The user in the reproduce step has docker group so it doesn't need `sudo` when running docker commands.

**Comment by thaJeztah** [comment] 2023-08-14 19:45
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/46161, and https://github.com/docker/cli/issues/4481

It's a bug in the packages that are built by the Canonical / Ubuntu packagers; see https://github.com/moby/moby/issues/46161#issuecomment-1667255217 and https://bugs.launchpad.net/ubuntu/+source/docker.io-app/+bug/2029523

> Bug reported in https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/2029564
> 
> You can revert to previous release of docker.io on Ubuntu 22.04. You can also `apt-mark hold` this package to prevent any update to occur until it is fixed.


Note that Docker 20.10 is quite an old version of the Engine, and Docker no longer does releases for 20.10. If you don't have a specific reason to run an older version, I would recommend installing Docker from the official packages at download.docker.com (installation instructions for ubuntu can be found in https://docs.docker.com/engine/install/ubuntu/)


I'm closing this issue as a duplicate, and because this is not a bug in the source code maintained in this repository, but feel free to continue the conversation.

I should also mention that images built with that version of Docker will have the wrong permissions in them, so you may want to re-build images built with the faulty version.

**Closed by thaJeztah** 2023-08-14 19:45 UTC
Labels: kind/bug, area/builder, version/20.10, area/packaging

**Comment by xiahualiu** [comment] 2023-08-14 20:47
Thank you Jeztah for your help. This bug appeared recently so that must be it. I will install docker from the Docker apt source and rebuild the image.
