### ISSUE TITLE
docker load and import breaking containers

### ISSUE THREAD

**Issue by crimson-med** [docker/cli#2891] opened 2020-12-17 03:53 UTC
**Description**

We have a project using docker containers through a docker-compose file. I'm trying to automate the backup and restoration of the current container state. I have tried using volumes in `docker-compose` but some of the files are not migrated.

**Steps to reproduce the issue:**

1.

```bash
docker save nodered/node-red > nodered_image.tar
docker export app_nodered_1 > nodered_container.tar
```

2.

```bash
docker rmi nodered/node-red
docker load < nodered_image.tar
cat nodered_container.tar | docker import - nodered/node-red
```

**Describe the results you received:**

I then try to up the containers with either `docker-compose up`.

> ERROR: for app_nodered_1 Cannot create container for service nodered: No command specified

**Describe the results you expected:**

For the docker container to be restored properly.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have also tried to import with the following command:

```bash
cat nodered_container.tar | docker import --change 'CMD ["npm --no-update-notifier --no-fund start --cache /data/.npm -- --userDir /data --privileged"]' - nodered/node-red
```

And it gives me the following:

> ERROR: for app_nodered_1 Cannot start service nodered: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "npm --no-update-notifier --no-fund start --cache /data/.npm --

This error happens with my three containers (nodered, grafana, vsftpd)

**Output of `docker version`:**

```
Client:
 Version:           19.03.13-ce
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Mon Oct 12 18:51:20 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Mon Oct 12 18:51:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.1
  GitCommit:        c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 19.03.13-ce
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c623d1b36f09f8ef6536a057bd658b3aa8632828
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0 (expected: fec3683)
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.203-156.332.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 957.1MiB
 Name: ip-10-0-1-140.eu-west-3.compute.internal
 ID: FJK5:UDNM:KEBE:SWII:CQFX:WQU6:EVHT:QBBL:5IX3:OKO2:BSGN:GHTZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

deployed on an EC2 instance.

**Comment by cpuguy83** [comment] 2020-12-17 18:41
`docker export` exports the container's filesystem as a flat rootfs.
`docker import` imports that flat rootfs as an image.

Volumes are not part of the container fs and are not saved on export.

If you want to take a snapshot of the container and use it somewhere else you need to use `docker commit ... && docker save ...`, then you can `docker load` it on the new machine... but again volumes will not be saved.

**Comment by crimson-med** [comment] 2020-12-18 02:34
@cpuguy83 Volumes that are mapped to the real system are backed up and restored already by themselves. 

Will `docker commit` stop the `CMD` initiation breaking?

**Comment by cpuguy83** [comment] 2020-12-18 02:35
No.

**Comment by cpuguy83** [comment] 2020-12-18 02:36
Errr... sorry read that wrong.
Commit keeps the cmd and everything.

**Comment by crimson-med** [comment] 2020-12-18 03:31
@cpuguy83 From the looks of the doc the docker load commands makes use of repository. There is no way to do this as a local file?

**Comment by cpuguy83** [comment] 2020-12-18 04:04
"docker load" loads the exact thing that "docker save" exports.

**Comment by crimson-med** [comment] 2020-12-18 04:21
> "docker load" loads the exact thing that "docker save" exports.

@cpuguy83 but it doesn't load all the commands that make the container work right?

**Comment by cpuguy83** [comment] 2020-12-18 05:31
"docker commit" persists a container as an image. This includes the command used to run the container, the file system, and all the non-host specific stuff (host specific being port bindings, bind mounts, etc).

"docker save" saves an image, along with names/tags to a tarball.

"docker load" loads the output from "docker save".

**Comment by thaJeztah** [comment] 2021-01-06 13:28
I think this is working as intended, so I'll close this ticket, but feel free to continue the conversation

**Closed by thaJeztah** 2021-01-06 13:28 UTC
Labels: kind/question
