### ISSUE TITLE
Failed to run hello-world in chroot environment

### ISSUE THREAD

**Issue by russell-islam** [docker/cli#2294] opened 2020-01-28 02:53 UTC
**Description**

**Steps to reproduce the issue:**
1. use a custom rooffs
2. create mount and cgroup mounts
3. chroot to the new root
4. start docker 
5. test hello-world

**Describe the results you received:**

```bash
# docker run hello-world --rm
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mountpoint for devices not found\"": unknown.
```

**Describe the results you expected:**
The correct output from hello-world container

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens all the time
**Output of `docker version`:**
```
# docker version
Client:
 Version:           18.06.2
 API version:       1.38
 Go version:        go1.10.7
 Git commit:        6d37f41
 Built:             Sun Jan  5 10:44:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.7
  Git commit:       6d37f41
  Built:            Sun Jan  5 10:47:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
```

```bash
docker run hello-world --rm
docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mountpoint for devices not found\"": unknown.

```

**Comment by russell-islam** [comment] 2020-01-28 02:54
These are the commands I used:
mkdir -p /mnt/custom-centos
mount --bind /root/myroot/  /mnt/custom-centos

mkdir -p /mnt/custom-centos/dev
mount --bind /dev /mnt/custom-centos/dev


mkdir -p /mnt/custom-centos/proc
mount --bind /proc /mnt/custom-centos/proc

mkdir -p /mnt/custom-centos/sys/fs/cgroup/devices
mount -n -t cgroup -o none,name=devices cgroup /mnt/custom-centos/sys/fs/cgroup/devices

mkdir -p /mnt/custom-centos/sys/fs/cgroup/systemd
mount -n -t cgroup -o none,name=systemd cgroup /mnt/custom-centos/sys/fs/cgroup/systemd

mkdir -p /mnt/custom-centos/sys/fs/cgroup/cpu
mount -n -t cgroup -o none,name=cpu cgroup /mnt/custom-centos/sys/fs/cgroup/cpu

mkdir -p /mnt/custom-centos/sys/fs/cgroup/blkio
mount -n -t cgroup -o none,name=blkio cgroup /mnt/custom-centos/sys/fs/cgroup/blkio

mkdir -p /mnt/custom-centos/sys/fs/cgroup/cpuset
mount -n -t cgroup -o none,name=cpuset cgroup /mnt/custom-centos/sys/fs/cgroup/cpuset

mkdir -p /mnt/custom-centos/sys/fs/cgroup/pid
mount -n -t cgroup -o none,name=pid cgroup /root/myroot/sys/fs/cgroup/pid


chroot /mnt/custom-centos /bin/bash --init-file /root/custom-centos-bash-init.sh
dockerd -D --iptables="false"


# Create a new window
chroot /mnt/mariner /bin/bash
docker run hello-world --rm

**Comment by russell-islam** [comment] 2020-01-28 02:55
mkdir -p /mnt/custom-centos
mount --bind /root/myroot/  /mnt/custom-centos

mkdir -p /mnt/custom-centos/dev
mount --bind /dev /mnt/custom-centos/dev


mkdir -p /mnt/custom-centos/proc
mount --bind /proc /mnt/custom-centos/proc

mkdir -p /mnt/custom-centos/sys/fs/cgroup/devices
mount -n -t cgroup -o none,name=devices cgroup /mnt/custom-centos/sys/fs/cgroup/devices

mkdir -p /mnt/custom-centos/sys/fs/cgroup/systemd
mount -n -t cgroup -o none,name=systemd cgroup /mnt/custom-centos/sys/fs/cgroup/systemd

mkdir -p /mnt/custom-centos/sys/fs/cgroup/cpu
mount -n -t cgroup -o none,name=cpu cgroup /mnt/custom-centos/sys/fs/cgroup/cpu

mkdir -p /mnt/custom-centos/sys/fs/cgroup/blkio
mount -n -t cgroup -o none,name=blkio cgroup /mnt/custom-centos/sys/fs/cgroup/blkio

mkdir -p /mnt/custom-centos/sys/fs/cgroup/cpuset
mount -n -t cgroup -o none,name=cpuset cgroup /mnt/custom-centos/sys/fs/cgroup/cpuset

mkdir -p /mnt/custom-centos/sys/fs/cgroup/pid
mount -n -t cgroup -o none,name=pid cgroup /root/myroot/sys/fs/cgroup/pid


chroot /mnt/custom-centos /bin/bash --init-file /root/custom-centos-bash-init.sh
dockerd -D --iptables="false"


# Create a new window
chroot /mnt/custom-centos /bin/bash
docker run hello-world --rm

**Comment by thaJeztah** [comment] 2020-01-28 11:59
This is not really a setup that's tested or supported. Also note that Docker 18.06 reached EOL last year, so is no longer maintained.

If you want to run docker in a separate environment, you could consider running `docker-in-docker`, running docker in "rootless" mode (https://docs.docker.com/engine/security/rootless/), or perhaps running it inside LXC.

You can also use the `check-config.sh` script to check what's possibly missing/misconfigured in the environment: https://github.com/moby/moby/blob/master/contrib/check-config.sh

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-01-28 11:59 UTC
