### ISSUE TITLE
Auth credentials aren't saved to config unless the config file is empty in WSL

### ISSUE THREAD

**Issue by lonetwin** [docker/cli#3947] opened 2023-01-05 10:41 UTC
### Description

Using docker on WSL2 with docker-desktop, the `docker login` command stores the auth credentials to `~/.docker/config.json` only if the file doesn't exist or is empty. Otherwise it creates an empty entry without the credentials under the `auths` key, within the file.

### Reproduce

On running the following command:
```
echo "<github PAT>" | docker login ghcr.io -u <username> --password-stdin
```

the expectation, if the auth is successful, is that the credentials would be stored in `~/.docker/config.json`. If this file is empty or does not exist, we see the expected result. However if this file has something like:

```json
{
    "credsStore": "desktop.exe"
}
```
On successful auth the file would be updated to something like this:
```
{
  "auths": {
    "ghcr.io": {
    }
  },
  "credsStore": "desktop.exe"
}
```

### Expected behavior

`docker login` should store the auth credentials to `~/.docker/config.json` on successful auth.

### docker version

```bash
Client: Docker Engine - Community
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:28 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 6
  Running: 3
  Paused: 0
  Stopped: 3
 Images: 9
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 9.72GiB
 Name: docker-desktop
 ID: 2NUX:6TN7:KWAY:BV3N:7GB5:42X4:O6ZO:YANK:VNQK:D6II:NAZN:ANC4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### Additional Info
![image](https://user-images.githubusercontent.com/101819/210763821-63548137-425f-45fd-be1a-c37304e038c9.png)

_No response_

**Comment by bsousaa** [comment] 2023-01-10 11:44
Docker Desktop uses a credential helper (keychain in MacOS and Credential Manager on Windows), hence credentials aren't stored in the config file. See more details in the docs https://docs.docker.com/engine/reference/commandline/login/#credentials-store.

**Comment by sam-thibault** [comment] 2023-01-13 11:25
Does @bsousaa 's response above answer your question?

**Comment by lonetwin** [comment] 2023-01-16 12:51
@sam-thibault @bsousaa thanks ! Although, while that sounds logical, in practice I can't seem to get docker cli to access a protected resource on `ghcr.io` after doing a `docker login ghcr.io` within WSL. I'm happy to close this bug and open a new one if required.

**Comment by laurazard** [comment] 2023-02-02 15:34
@lonetwin, I've tried to replicate this but haven't been able to. On Windows, you should be able to check Credential Manager and search for `ghcr`, or `Docker Credentials`, to see if you find the appropriate credentials there. On macOS, the same can be done by looking in `Keychain Access`.

I've ran into this also when logging into ghcr with a PAT that didn't have enough permissions, so I'd check that too (packages:read is necessary, not sure if more are).

**Comment by sam-thibault** [comment] 2023-02-16 11:16
I will close this for now since we are not able to reproduce this issue.  Please comment if you have more details that might help us to investigate further.

**Closed by sam-thibault** 2023-02-16 11:16 UTC
Labels: kind/bug, status/0-triage, status/more-info-needed
