### ISSUE TITLE
docker build failing with wget: unable to resolve host address

### ISSUE THREAD

**Issue by sibman** [docker/cli#2437] opened 2020-04-10 23:38 UTC
I have tried to build the docker-rust-nightly image and all of the images failing with similar error.
Here is my docker information:
docker version
```
Client:
Version: 19.03.6
API version: 1.40
Go version: go1.12.17
Git commit: 369ce74a3c
Built: Fri Feb 28 23:45:43 2020
OS/Arch: linux/amd64
Experimental: false

Server:
Engine:
Version: 19.03.6
API version: 1.40 (minimum version 1.12)
Go version: go1.12.17
Git commit: 369ce74a3c
Built: Wed Feb 19 01:06:16 2020
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.3.3-0ubuntu1~18.04.2
GitCommit:
runc:
Version: spec: 1.0.1-dev
GitCommit:
docker-init:
Version: 0.18.0
GitCommit:
```

Here I'm attaching couple of build logs.

```
docker build -t rust:nightly nightly
Sending build context to Docker daemon 3.584kB
Step 1/3 : FROM buildpack-deps:stretch
---> 545bd80faf41
Step 2/3 : ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo PATH=/usr/local/cargo/bin:$PATH
---> Using cache
---> 23cc7f4ddf02
Step 3/3 : RUN set -eux; url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; wget "$url"; chmod +x rustup-init; ./rustup-init -y --no-modify-path --default-toolchain nightly; rm rustup-init; chmod -R a+w $RUSTUP_HOME $CARGO_HOME; rustup --version; cargo --version; rustc --version;
---> Running in 9dbc12104676

url=https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
--2020-04-10 10:47:25-- https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
Resolving static.rust-lang.org (static.rust-lang.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'static.rust-lang.org'
The command '/bin/sh -c set -eux; url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; wget "$url"; chmod +x rustup-init; ./rustup-init -y --no-modify-path --default-toolchain nightly; rm rustup-init; chmod -R a+w $RUSTUP_HOME $CARGO_HOME; rustup --version; cargo --version; rustc --version;' returned a non-zero code: 4
docker build -t rust:nightly nightly
Sending build context to Docker daemon 3.584kB
Step 1/3 : FROM buildpack-deps:buster
buster: Pulling from library/buildpack-deps
f15005b0235f: Pull complete
41ebfd3d2fd0: Pull complete
b998346ba308: Pull complete
f01ec562c947: Pull complete
2447a2c11907: Pull complete
Digest: sha256:4af1d565ec5928711ff3df178868160b5bb12d698ebb439c0eb2ca7457642a91
Status: Downloaded newer image for buildpack-deps:buster
---> af5c385d7e88
Step 2/3 : ENV RUSTUP_HOME=/usr/local/rustup CARGO_HOME=/usr/local/cargo PATH=/usr/local/cargo/bin:$PATH
---> Running in 60a2cf6056b9
Removing intermediate container 60a2cf6056b9
---> fc62dbeeb45b
Step 3/3 : RUN set -eux; url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; wget "$url"; chmod +x rustup-init; ./rustup-init -y --no-modify-path --default-toolchain nightly; rm rustup-init; chmod -R a+w $RUSTUP_HOME $CARGO_HOME; rustup --version; cargo --version; rustc --version;
---> Running in 99e7d6651564

url=https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
--2020-04-10 10:59:07-- https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
Resolving static.rust-lang.org (static.rust-lang.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'static.rust-lang.org'
The command '/bin/sh -c set -eux; url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; wget "$url"; chmod +x rustup-init; ./rustup-init -y --no-modify-path --default-toolchain nightly; rm rustup-init; chmod -R a+w $RUSTUP_HOME $CARGO_HOME; rustup --version; cargo --version; rustc --version;' returned a non-zero code: 4
```

I could execute the commands which listed in docker file with out any issues from the host os, but when I attaching to container terminal of buildpack-deps:stretch image and trying to run wget command from a container I'm getting identical results as I presented in logs. Here I'm attaching the steps to replicate the issue.

```
docker run -it buildpack-deps:stretch /bin/bash
root@27e7b911e0d3:/# wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
--2020-04-10 14:04:19-- https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
Resolving static.rust-lang.org (static.rust-lang.org)... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'static.rust-lang.org'
root@27e7b911e0d3:/#
```

**Comment by thaJeztah** [comment] 2020-06-05 15:20
I'm not able to reproduce this issue;

```bash
docker run -it --rm buildpack-deps:stretch /bin/bash -c 'wget https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init'
Unable to find image 'buildpack-deps:stretch' locally

stretch: Pulling from library/buildpack-deps
1c6172af85ee: Pull complete
b194b0e3c928: Pull complete
1f5ec00f35d5: Pull complete
93b1353672b6: Pull complete
3d7f38db3cca: Pull complete
Digest: sha256:dee4275fc056551e1f83c5a3ea024510ca63f03ceedd9a1c29cbab70644b046b
Status: Downloaded newer image for buildpack-deps:stretch

--2020-06-05 15:19:12--  https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
Resolving static.rust-lang.org (static.rust-lang.org)... 143.204.169.108, 143.204.169.12, 143.204.169.84, ...
Connecting to static.rust-lang.org (static.rust-lang.org)|143.204.169.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12245112 (12M) [binary/octet-stream]
Saving to: 'rustup-init'

rustup-init                                                                                   100%[==============================================================================================================================================================================================================================================>]  11.68M  --.-KB/s    in 0.08s

2020-06-05 15:19:12 (154 MB/s) - 'rustup-init' saved [12245112/12245112]
```

Tested on;

```
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-66-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.947GiB
 Name: ubuntu-s-1vcpu-2gb-ams3-01
 ID: HFPJ:LFW7:WQBE:FZFZ:4O3Q:NUSH:ELXW:B6JK:XKJL:7VKA:XBN7:CV6Y
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 21
  Goroutines: 35
  System Time: 2020-06-05T15:19:56.286116551Z
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by thaJeztah** [comment] 2020-06-05 15:23
I do notice you're running a version of docker that's likely built by the Ubuntu package maintainers. Those packages are not maintained by us, use different versions of dependencies, and have at times caused problems.

Are you able to reproduce the problem when installing the official docker package? https://docs.docker.com/engine/install/ubuntu/

If you cannot install the official packages, I'd recommend opening a ticket in the Ubuntu/Canonical issue tracker.

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-05 15:23 UTC
