### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by lucaspompeun** [docker/cli#2345] opened 2020-02-18 17:24 UTC
I had this problem today
```
2020-02-18 16:11:47 INFO: [GenomePreparation 85022035748] Simulating reads finished
2020-02-18 16:19:10 INFO: [MetagenomeSimulationPipeline] Generate gold standard assembly
2020-02-18 16:19:10 INFO: [MetadataReader 6137628860] Reading file: '/output/internal/genome_locations.tsv'
2020-02-18 16:19:10 ERROR: [MetagenomeSimulationPipeline] [Errno 28] No space left on device: '/tmp/tmpcE2Ssk/tmpFnPHny' in line 106
2020-02-18 16:19:10 INFO: [MetagenomeSimulationPipeline] Metagenome simulation aborted
Exception AttributeError: "'GoldStandardAssembly' object has no attribute 'temp_merges_bam_directory'" in <bound method GoldStandardAssembly.del_ of <scripts.GoldStandar
dAssembly.goldstandardassembly.GoldStandardAssembly object at 0x7f86db3d9110>> ignored
```

help

**Comment by thaJeztah** [comment] 2020-02-18 22:29
Please provide more information as requested in the [issue-template](https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md) that was shown when you opened this issue.

- provide the output of `docker version`
- provide the output of `docker info`
- provide the exact steps to reproduce. If the steps to reproduce require custom images, or source code, provide a _minimal_ test-case to reproduce. Keep in mind that we don't have access to your private images or source code. Without steps to reproduce, or a reproducible case it's unlikely that your issue can be resolved.

I'm closing this issue, because there's not enough information to act on.

**Closed by thaJeztah** 2020-02-18 22:29 UTC
