### ISSUE TITLE
mount denied on Mac

### ISSUE THREAD

**Issue by wise-Kaas** [docker/cli#2879] opened 2020-12-11 08:23 UTC
**Description**

Just upgraded Docker Desktop to version 3.0.0 on Mac and unable to mount directories on host that are inside Desktop or Documents (I suspect this goes further, I just didn't keep checking). First found it out while running `docker-compose` with volume option, later checked with regular `docker run -v` - same result. Looks like something got messed up with permissions. In `Preferences->Resources->File Sharing` still have that `/Users` path, while adding exact path as I pass it to command didn't help either. Everything works fine in home or any other custom directories not inside Desktop or Documents.

**Steps to reproduce the issue:**
1. cd ~/Desktop
2. mkdir somedir
3. docker run -v $PWD:/app python:3.8

**Describe the results you received:**
```
docker: Error response from daemon: Mounts denied: approving /Users/u18199653/Desktop/somedir: file does not exist
```

**Describe the results you expected:**
successful start of container with mounted directory on host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 8
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: KRBM:BOWC:VQZP:TPHT:JM57:AE25:QM3O:4NGA:TYWK:UFLU:LAIK:AQAV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2020-12-11 19:15
Thanks for reporting; this issue is specific to Docker Desktop for Mac, and a duplicate of https://github.com/docker/for-mac/issues/5115

An updated version of Docker Desktop for Mac was released (3.0.1 or 3.0.2), with a fix for this.

Let me close this ticket as this should be fixed, but feel free to continue the conversation.

**Closed by thaJeztah** 2020-12-11 19:15 UTC
