### ISSUE TITLE
Negative filters don't work

### ISSUE THREAD

**Issue by ayarosh** [docker/cli#3617] opened 2022-05-17 13:30 UTC
**Description**
The negative filters don't work.
The issue has reproduced on a multiple environments.

**Steps to reproduce the issue:**
1. Open a terminal
2. Run a command: `docker image prune --filter="dangling=true" --filter="reference!=portainer/*"`

**Describe the results you received:**
```
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Error response from daemon: Invalid filter 'reference!'
```

**Describe the results you expected:**
All untagged images should be pruned except _portainer/*_.

**Output of `docker version`:**

```
Client:
 Cloud integration: v1.0.22
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:08:44 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.6.1 (76265)
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:06:05 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 11
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.774GiB
 Name: docker-desktop
 ID: VRMP:5PJM:QLCS:GLO5:HZLS:REJ3:BW3X:C3W5:L3EX:DBH5:BKXI:OXWV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Same behaviour is observed in Ubuntu environment
OS: Ubuntu 20.04.1 LTS
Docker: 19.03.8

**Comment by thaJeztah** [comment] 2022-05-17 15:29
`docker image prune` currently only supports filtering on `until` and `label`; see https://docs.docker.com/engine/reference/commandline/image_prune/#filtering

Other filters _may_ be added at some point, but the `prune` commands are also used to perform `docker system prune`, and for that to function, the list of available filters needs to be the "common denominator" between all `prune` commands; see https://github.com/docker/cli/issues/625 for more details.

I'm closing this ticket as duplicate of https://github.com/docker/cli/issues/625 to prevent the conversation from diverging.

**Closed by thaJeztah** 2022-05-17 15:29 UTC
