### ISSUE TITLE
‘docker pull’ should cache the layer it downloaded and verified

### ISSUE THREAD

**Issue by vipcxj** [docker/cli#3818] opened 2022-10-17 14:28 UTC
### Description

Many images are very huge. They can be as large as a few G, or even tens of G. I don't expect docker to support resumable breakpoints when pulling images. At least people derserve the ability to cache the layers that have been successfully downloaded and verified by checksum. This will not only put a smile on the user's face, but also greatly reduce the stress on the server.

**Comment by bsousaa** [comment] 2022-11-24 12:06
Looks like a duplicate of https://github.com/moby/moby/issues/20862. I will close this issue in favour of 20862.

**Closed by bsousaa** 2022-11-24 12:06 UTC
Labels: kind/feature
