### ISSUE TITLE
docker "exec" does not forward signals to container process.

### ISSUE THREAD

**Issue by q53** [docker/cli#5309] opened 2024-07-30 14:37 UTC
### Description

subj.

### Reproduce

```
[16:57:37 dt]$ cat test.sh 
#!/bin/bash

CID=`docker run --name test -d --rm alpine sleep 3000`

docker exec -i test sleep 300 & # First job

sleep 30 & # Second job

sleep 3

kill -- -$$ # Terminate all jobs

[16:57:41 dt]$ ./test.sh 
Terminated
[16:57:47 dt]$ ps # are there any jos left?
    PID TTY          TIME CMD
 174332 pts/20   00:00:00 bash
 177628 pts/20   00:00:00 ps
[16:57:50 dt]$ docker exec -ti test ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 3000
    7 root      0:00 sleep 300
   13 root      0:00 ps aux
[16:57:55 dt]$ 

```

### Expected behavior

The last command shouldn't show `7 root      0:00 sleep 300 ` line

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:34:39 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:34 2024
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.32
  GitCommit:        8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 10
  Running: 2
  Paused: 0
  Stopped: 8
 Images: 21
 Server Version: 26.1.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8b3b7ca2e5ce38e8f31a34f35b2b68ceb8470d89
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-553.8.1.el8_10.x86_64
 Operating System: AlmaLinux 8.10 (Cerulean Leopard)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 17.27GiB
 Name: n03
 ID: 83a369a6-cf0a-4b50-acac-9d12021b3b66
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2024-07-30 17:08
This looks to be a duplicate of https://github.com/docker/cli/issues/2607 and https://github.com/moby/moby/issues/9098

https://github.com/docker/cli/pull/1841 fixed this situation for `docker run`, but `docker exec` needs additional changes (some outlined in https://github.com/moby/moby/issues/9098)

Let me close this one to prevent the conversation from diverging.

**Closed** 2024-07-30 17:09 UTC
Labels: kind/bug, status/0-triage, version/26.1
