### ISSUE TITLE
[BUG] platform argument ignored when running docker import on different arch

### ISSUE THREAD

**Issue by fabolhak** [docker/cli#3408] opened 2022-01-25 10:34 UTC
**Description**

When I try to import an arm64 image on my amd64 providing the argument "--platform linux/arm64" the resulting image still has amd64 set as architecture.

**Steps to reproduce the issue:**
1. `docker pull --platform linux/arm64 busybox`
2. `docker save busybox -o /tmp/busybox.tar`
3. `docker import --platform linux/arm64 /tmp/busybox.tar busybox:imported`
4. `docker image inspect busybox:latest | grep "Architecture"`
5. `docker image inspect busybox:imported | grep "Architecture"`

**Describe the results you received:**
```
$ docker image inspect busybox:latest | grep "Architecture"
        "Architecture": "arm64",
```
and
```
$ docker image inspect busybox:imported | grep "Architecture"
        "Architecture": "amd64",
```

**Describe the results you expected:**
I would expect that the imported image has the architecture provided by the platform command. If this feature is not supported when running on a different platform I don't see the benefit in having the argument at all or it should at least show a warning instead of silently using a different architecture.

Optimally the result should look like:
```
$ docker image inspect busybox:imported | grep "Architecture"
        "Architecture": "arm64",
```

**Output of `docker version`:**

```
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.5
 Git commit:        e91ed5707e
 Built:             Mon Dec 13 22:31:40 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.5
  Git commit:       459d0dfbbb
  Built:            Mon Dec 13 22:30:43 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.9
  GitCommit:        1407cab509ff0d96baa4f0eb6ff9980270e6e620.m
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., 2.2.3)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1407cab509ff0d96baa4f0eb6ff9980270e6e620.m
 runc version: v1.0.3-0-gf46b6ba2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.84-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 38.89GiB
 Name: notebook
 ID: V42C:OAWZ:MKAH:YCPI:4WMG:GDY2:2MWI:LJOT:UPFI:7FKG:EB4R:BEST
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment] 2022-01-27 00:20
Thanks for reporting; this is a duplicate of https://github.com/moby/moby/issues/42813 (which also has some details https://github.com/moby/moby/issues/42813#issuecomment-999542272), and has been implemented in https://github.com/moby/moby/pull/43103 (which will be in the next release).

I'll go ahead and close this, but feel free to continue the conversation.

**Closed by thaJeztah** 2022-01-27 00:20 UTC

**Comment by thaJeztah** [comment] 2022-01-27 00:27
oh! I just noticed you're combining `docker save` with `docker import`.

If your intent is to save an existing image, and load it, then use `docker load` instead of `docker import`.


`docker import` creates a new image from a `rootfs`, but does not preserve the image's metadata / configuration, whereas `docker load` loads the exported image (including metadata);

```bash
docker pull --platform linux/arm64 busybox
# Using default tag: latest
# latest: Pulling from library/busybox
# a01966dde7f8: Pull complete
# Digest: sha256:5acba83a746c7608ed544dc1533b87c737a0b0fb730301639a0179f9344b1678
# Status: Downloaded newer image for busybox:latest
# docker.io/library/busybox:latest

docker save busybox -o busybox.tar
docker image rm busybox
# Untagged: busybox:latest
# Deleted: sha256:71a676dd070f4b701c3272e566d84951362f1326ea07d5bbad119d1c4f6b3d02
# Deleted: sha256:468ad4d964cd60bde6271569ed2459b3cd52ee8a5a621f3f5fae86efa37e390c

docker load -i busybox.tar
# 468ad4d964cd: Loading layer [==================================================>]  1.631MB/1.631MB
# Loaded image: busybox:latest
# Loaded image ID: sha256:71a676dd070f4b701c3272e566d84951362f1326ea07d5bbad119d1c4f6b3d02
# Loaded image ID: sha256:c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18
# Loaded image ID: sha256:beae173ccac6ad749f76713cf4440fe3d21d1043fe616dfbe30775815d1d0f6a
# Loaded image ID: sha256:16ea53ea7c652456803632d67517b78a4f9075a10bfdc4fc6b7b4cbf2bc98497

docker image inspect busybox | grep "Architecture"
#       "Architecture": "arm64",
```

**Comment by fabolhak** [comment] 2022-01-27 10:17
Thank you for the quick reply :). Sorry I wasn't aware of https://github.com/moby/moby/issues/42813 and it did not appear on my various searches. 

The combination of `docker save` and `docker import` was just for demonstrating the problem. In my real use case I actually have a similar setup as described https://github.com/moby/moby/issues/42813 

Is there by chance an easy way to change the architecture of an image manually which I can use until the next release is available? :)

**Comment by thaJeztah** [comment] 2022-01-27 11:11
Hmm.. _perhaps_ it's possible to edit the image config, but I would avoid doing so (generally, files within `/var/lib/docker` are designed to be exclusively accessed by the `dockerd` daemon; modifying the files can lead to unexpected behavior (_perhaps_ it works when editing the file while the daemon isn't running, but it's possible there's state stored in memory or other locations).

Instead of `docker import`, you could create the image using `docker build` (which is the usual approach to build a base-image from a rootfs (see, e.g. the Dockerfile for one of the official `busybox` images: https://github.com/docker-library/busybox/blob/ecf0f5ecd9697ac16b9662679511bd5e011d34b4/stable/uclibc/Dockerfile)


Just for illustration; (pull, and) create an arm64 busybox container, and export it to get the rootfs:

```bash
docker container create --name=temp --platform=linux/arm64 busybox
docker container export -o busybox-rootfs.tar temp
docker container rm temp
docker image rm busybox
```

Build a base image (`FROM scratch` image with the rootfs), and set the platform of the image to `linux/arm64`:

```bash
echo -e 'FROM scratch\nADD busybox-rootfs.tar /\nCMD ["sh"]' | docker build -t busy --platform=linux/arm64 -f- .
```

Check that the Architecture is correct:

```bash
docker image inspect --format='{{.Architecture}}' busy
arm64

docker run --platform=linux/arm64 --rm busy uname -m
aarch64
```

**Comment by fabolhak** [comment] 2022-01-27 19:39
Ok perfect. Yes that actually worked for my use case. Thank you very much :)
