### ISSUE TITLE
Can not pull from private registry using version 17.06.0-ce

### ISSUE THREAD

**Issue by tenjohokwen** [docker/cli#275] opened 2017-06-30 17:22 UTC
**Steps to reproduce the issue:**
1. create private registry and push an image to it (preferably with a version prior to 17.06.0-ce). 
2. Install docker version 17.06.0-ce (on the mac)
3. pull the image

**Describe the results you received:**
```
Error response from daemon: error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 404 - /v2/.......
<u>The requested resource is not available.</u></p><HR size=\"1\" noshade=\"noshade\"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>"
```
**Describe the results you expected:**
* I expected the image

**Additional information you deem important (e.g. issue happens only occasionally):**
* Works on version 17.03.0-ce (my previous version)
* When using version 17.06.0-ce , my docker machines which use client and server versions 17.03.0-ce can pull the images but the host running 17.06.0-ce cannot.

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: pending
 NodeID: uyocih5koz83j5uxkjflqm99r
 Error: rpc error: code = 2 desc = The swarm does not have a leader. It's possible that too few managers are online. Make sure more than half of the managers are online.
 Is Manager: true
 Node Address: 192.168.99.100
 Manager Addresses:
  0.0.0.0:2377
  192.168.99.100:2377
  192.168.99.101:2377
  192.168.99.102:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.31-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: 2CV7:73AP:MIVZ:XM5L:RXTX:BFAT:P56Y:RYX3:GT5H:77ET:C4TR:6D3L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 83
 System Time: 2017-06-30T17:11:20.297681728Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Using docker on mac
* Reverting to the host to version 17.03.0-ce solves the issue

**Comment by thaJeztah** [comment] 2017-07-01 05:40
HTTP Status 404 - /v2/

It looks like you are running a legacy (V1) registry; the V1 registry protocol is deprecated, and communication with V1 registries is disabled by default in Docker 17.06. See the release notes;
https://github.com/docker/docker-ce/releases/tag/v17.06.0-ce

> **NOTE:** Docker 17.06 by default disables communication with legacy (v1) registries. If you
require interaction with registries that have not yet migrated to the v2 protocol, set the
`--disable-legacy-registry=false` daemon option. Interaction with v1 registries will be removed
in Docker 17.12.

On Docker for Mac you can change this setting using [a `daemon.json` configuration](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file) in the "daemon -> advanced" panel in the preferences, for example:

```json
{
  "debug" : true,
  "experimental" : true,
  "disable-legacy-registry" : false
}
```

I highly recommend upgrading to a v2 registry, as the v1 format is insecure, and (as mentioned) won't be supported in future.

I'm closing this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-07-01 05:40 UTC
Labels: version/17.06
