### ISSUE TITLE
Args parsed error when docker command with sudo

### ISSUE THREAD

**Issue by sunzhaochang** [docker/cli#3401] opened 2022-01-05 12:22 UTC
**Description**

When I use `docker commit` command with sudo, the args parsed error in some scenarios.

**Steps to reproduce the issue:**
1.  `sudo docker run -d nginx`
2. `sudo docker commit -m "test commit" 349909050ca9 nginx:test`

**Describe the results you received:**
```
"docker commit" requires at least 1 and at most 2 arguments.
See 'docker commit --help'.

Usage:  docker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]

Create a new image from a container's changes
```

**Describe the results you expected:**

the `docker commit` command returns success. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 73
  Running: 35
  Paused: 0
  Stopped: 38
 Images: 353
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.9.70-040970-generic
 Operating System: Ubuntu 16.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 96
 Total Memory: 1007GiB
 Name: xxx
 ID: FTJD:TBEU:AXG5:DT2R:4GYF:JSW4:LX5U:MXIX:5CCF:OWYZ:G5IK:H5UM
 Docker Root Dir: /data1/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by thaJeztah** [comment] 2022-01-05 20:15
I'm not able to reproduce this (tested on docker 20.10.11); are you still able to reproduce this on a current version of Docker?

Note that Ubuntu 16.04 reached EOL, and we no longer release updates for Docker for that version of Ubuntu (last docker release was 20.10.7)


```bash
docker run -d nginx
c5ad091a91133f544f6cd3ba896085b81463f173ed27cd6c417301caa2111dd7
```

Without `sudo`:

```bash
docker commit -m "test commit" c5ad091a9113 nginx:test
sha256:4a3d2c35a8460bbf0ed29a3ee2bdf32a224fd1c274dae3c3c4b10504d881c9e2
```

With `sudo`:

```bash
sudo docker commit -m "test commit" c5ad091a9113 nginx:test
Password:
sha256:6cfae504e22bad09ec4a8f94c5a8aa5d170d4f7d25cdeaa797eb37d0d605e4ff
```

**Comment by sunzhaochang** [comment] 2022-01-07 12:09
@thaJeztah Thanks for your reply. I can reproduce this with docker client 20.10.7 on Ubuntu 16.04 and I found that the `docker commit` command can be executed successfully in some cases.

```
$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

With one-word message, it success: 
```
$ sudo docker commit -m "test" 7864fd5b5b31 nginx:test
sha256:4bb2441b6020600a7b29204ff4ec8e968c7e1fa137cdeb4f619f6780ebb1b266
```

With multi-word message, it failed: 
```
$ sudo docker commit -m "test commit" 7864fd5b5b31 nginx:test
"docker commit" requires at least 1 and at most 2 arguments.
See 'docker commit --help'.

Usage:  docker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]

Create a new image from a container's changes
```

Without sudo, it success: 
```
$ echo "docker commit -m \"test commit\" 7864fd5b5b31 nginx:test" > run.sh
$ sudo sh run.sh
sha256:2dfd944742518e9e0a1979e2c059f1cf56054742e53629ccd43aca7a2f4256a6
```

NOTE: 
1. I have no other system(higher than 16.04) to test the problem currently, so may be it will work right on others.
2. I can only apply for sudo privilege to use the machine and have no password of root directly, mine username is added to sudoers. I'm not sure if it effects.

**Comment by thaJeztah** [comment] 2022-01-07 12:32
I suspect this may be caused by string splitting to happen in the shell, or your version of `sudo` to not priorly handle that; does it work if you (e.g.) run it like this?

```bash
sudo sh -c 'docker commit -m "test commit" 7864fd5b5b31 nginx:test'
```

**Comment by sunzhaochang** [comment] 2022-01-07 13:05
@thaJeztah It not work as follows: 
```
$ sudo sh -c 'docker commit -m "test commit" 7864fd5b5b31 nginx:test'

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers
......
```
and another test case: 
```
$ sh -c 'echo "hello world"'
hello world
$ sudo sh -c 'echo "hello world"'

```

So it may be caused by sudo as you mentioned. Thanks for your time.

**Comment by thaJeztah** [comment] 2022-01-07 13:10
Hm... interesting. `sudo sh -c 'echo "hello world"'` should just work, so yes, looks like something weird with `sudo`. Just to be sure, you may want to check if `sudo` and/or`docker` are aliases (I know some installs have a `docker` alias set that's a wrapper script, e.g.)

```bash
$ command -v sudo
/usr/bin/sudo
$ command -v docker
/usr/bin/docker
```


Depending on your use-case, you may also consider adding your user to the `docker` group (which would give it access to the Docker socket (`/var/run/docker.sock`) without using `sudo`; https://docs.docker.com/engine/install/linux-postinstall/

**Comment by sunzhaochang** [comment] 2022-01-07 13:23
@thaJeztah It looks like nothing weird with `sudo`
```
$ command -v sudo
/usr/bin/sudo
$ command -v docker
/usr/bin/docker
```
I added my user to the `docker` group and it can work without `sudo` now.
```
$ docker commit -m "test commit" 7864fd5b5b31 nginx:test
sha256:6e46dcb6f746f1aeb4e9338636e35b1fc9b435a88f53ed0c527fec0fa39fa5bd
```

**Comment by thaJeztah** [comment] 2022-01-07 14:30
> I added my user to the docker group and it can work without sudo now.

Good to hear that worked!

Based on the discussion above, I doubt this is a bug in docker itself (but could possibly be an issue with specific versions of `sudo` 🤷‍♂️). Let me close this ticket because of that, but feel free to continue the conversation

**Closed by thaJeztah** 2022-01-07 14:30 UTC
Labels: status/more-info-needed, version/19.03
