### ISSUE TITLE
Docker run bash -c "hello" getting stdout

### ISSUE THREAD

**Issue by peterfeifanchen** [docker/cli#2644] opened 2020-07-23 01:48 UTC
This isn't a bug or issue or anything but more general usage question for the `docker run` CLI.

If I can run `bash --init-file <(echo [cmd])` to start a bash terminal and get it to run an initial command while remaining in the shell.

However when I do `docker run -it --entrypoint bash [IMAGE] --init-file <(echo [cmd])`, I do not see the output of [cmd]. Also for example if I do `docker run -it --entrypoint bash [IMAGE] -c echo "hello"`, I do not see "hello".

I feel while I am attaching to the stdout of docker, maybe the `bash` is on a different stdout? Is there a way to get the output there? Just curious.

**Comment by thaJeztah** [comment] 2020-07-27 15:23
In the second example, you probably want to add (single) quotes to `echo "hello"`, otherwise they're split. When adding quotes, this looks to work;

```bash
docker run -it --entrypoint bash ubuntu -c 'echo "hello"'
hello
```

I assume the same applies to the second one (to prevent the local shell from capturing it)

**Comment by thaJeztah** [comment] 2020-07-27 15:23
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2020-07-27 15:23 UTC
Labels: kind/question
