### ISSUE TITLE
docker build login shell

### ISSUE THREAD

**Issue by tonycody** [docker/cli#3296] opened 2021-09-12 12:18 UTC
How to make 'RUN' use /bin/bash --login in Dockerfile? Because I want to load ~/.bashrc

**Comment by thaJeztah** [comment] 2021-09-16 17:50
You can use the `SHELL` instruction to set a custom shell to use for the build steps; I don't know if / how well it works for this specific option though, but you can try https://docs.docker.com/engine/reference/builder/#shell

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com
- the `docker` tags on [StackOverflow](https://stackoverflow.com/questions/tagged/docker*)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-09-16 17:50 UTC
