### ISSUE TITLE
docker deploy behaves differently than stack deploy

### ISSUE THREAD

**Issue by userzimmermann** [docker/cli#527] opened 2017-09-12 17:59 UTC
Here @ https://www.meetup.com/preview/Docker-Bamberg/events/242039360 @Govinda-Fichtner and I just realized that `docker deploy` only works w/experimental mode while `docker stack deploy` just works. Is this different behavior intended?

```
Docker version 17.07.0-ce, build 8784753
```

`> docker deploy`

```
docker deploy is only supported on a Docker daemon with experimental features enabled
```

`> docker stack deploy`

```
"docker stack deploy" requires exactly 1 argument(s).
See 'docker stack deploy --help'.

Usage:  docker stack deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack
```

**Comment by dnephin** [comment] 2017-09-12 18:09
Yes, that is the intended behaviour. We might want to change `docker deploy` in the future, so it is still experimental.

**Comment by thaJeztah** [comment] 2017-09-12 18:09
I think this was intended; `docker deploy` was introduced as an experimental feature (using the bundles format); with the change to group the subcommands per object type (`docker _stack_ deploy`, `docker _container_ run` etc.), it was (if I remember correctly) decided to keep the top-level `deploy` as experimental in case it would be deprecated in favor of `docker stack deploy`

**Comment by thaJeztah** [comment] 2017-09-12 18:10
Oh, lol, @dnephin beat me to it 😂

**Comment by thaJeztah** [comment] 2017-09-12 18:10
Let me close this one as it's not a bug, but feel free to continue the discussion

**Closed by thaJeztah** 2017-09-12 18:10 UTC
Labels: kind/question

**Comment by userzimmermann** [comment] 2017-09-12 18:36
Thanks @dnephin and @thaJeztah for explaining! :)

**Comment by schmunk42** [comment] 2017-09-22 12:41
> it was (if I remember correctly) decided to keep the top-level deploy as experimental in case it would be deprecated in favor of docker stack deploy

That's somehow strange in my use-case since I use a Docker CLI on my machine working against a remote machine with swarm mode, which can't directly be changed.

So not executing the command `deploy` (locally) and telling me that I need experimental on the daemon makes no sense, regarding that `stack deploy` just works.

It would be fine if the CLI says that the *command is deprecated*, but it has nothing to do with the daemon as far as I can see it. Or is there also an `experimental` mode for the CLI itself?
