### ISSUE TITLE
runc version: N/A

### ISSUE THREAD

**Issue by Christian-L** [docker/cli#3201] opened 2021-07-22 04:16 UTC
recently, i‘m working on install Docker Engine from binaries. And the machine is a arm64 linux.
i could not run a image
-------error msg------------
[root@jzsp-cs-001 kkfile]# docker run -it -p 8012:8012 keking/kkfileview
INFO[2021-07-22T11:02:03.055093460+08:00] Container create done(Name: /quirky_stonebraker ID: d7e9195c1c570830838da9ba0021bef866526627d20ff884a443e63ce9dfed9e) 
INFO[2021-07-22T11:02:05.187180910+08:00] shim containerd-shim started                  address="/containerd-shim/moby/d7e9195c1c570830838da9ba0021bef866526627d20ff884a443e63ce9dfed9e/shim.sock" debug=false pid=211621
       ERRO[2021-07-22T11:02:06.269174890+08:00] revert: kill shim error=no status provided on response  error="no status provided on response: unknown"
                                                                                                                                                        ERRO[2021-07-22T11:02:06.269362900+08:00] revert: delete bundle error=<nil>             error="no status provided on response: unknown"
                                                                             ERRO[2021-07-22T11:02:06.269648850+08:00] stream copy error: read /proc/self/fd/24: file already closed 
                                                                                                                                                                                     ERRO[2021-07-22T11:02:08.979081040+08:00] d7e9195c1c570830838da9ba0021bef866526627d20ff884a443e63ce9dfed9e cleanup: failed to delete container from containerd: no such container 
ERRO[2021-07-22T11:02:08.979130970+08:00] Handler for POST /v1.39/containers/d7e9195c1c570830838da9ba0021bef866526627d20ff884a443e63ce9dfed9e/start returned error: no status provided on response: unknown 
docker: Error response from daemon: no status provided on response: unknown.
ERRO[0008] error waiting for container: context canceled 
---------------end---------------------------

i typed the "docker system info" command
![image](https://user-images.githubusercontent.com/8042746/126588970-bc768a4f-7cbf-4dd6-887f-4c099095618f.png)
as you see,the runc version: N/A.

**Comment by thaJeztah** [comment] 2021-07-26 12:26
The `runc version N/A` either means that runc was compiled with incorrect options, and didn't return the version in an expected format, or the daemon was unable to connect with runc.

I see you're trying to run a very old version of docker that has reached EOL. I'd recommend trying to install a more current version of docker, but there won't be official packages for Kylin linux (not sure what it's currently based on; if it's based on (e.g.) Ubuntu or Debian, you may be able to install a package for one of those that most closely matches the version it's based on. https://docs.docker.com/engine/install/


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-07-26 12:26 UTC
Labels: kind/question, version/18.09

**Comment by Christian-L** [comment] 2021-07-26 13:05
Since the server machine can't connect the internet ,i have to install the docker from binaries. 
I got the guidance from this website  [https://docs.docker.com/engine/install/binaries/](https://docs.docker.com/engine/install/binaries/)
And get the 'docker-20.10.7.tgz ' from [https://download.docker.com/linux/static/stable/aarch64/]( https://download.docker.com/linux/static/stable/aarch64/)
After the installation,i can see the docker client version is 20.10.7,but the server version is 18.09.0.
I dont know why the server version was that old. I will try to install the docker with the rpm packages.
Thanks a lot!

**Comment by Christian-L** [comment] 2021-07-26 13:06
> The `runc version N/A` either means that runc was compiled with incorrect options, and didn't return the version in an expected format, or the daemon was unable to connect with runc.
> 
> I see you're trying to run a very old version of docker that has reached EOL. I'd recommend trying to install a more current version of docker, but there won't be official packages for Kylin linux (not sure what it's currently based on; if it's based on (e.g.) Ubuntu or Debian, you may be able to install a package for one of those that most closely matches the version it's based on. https://docs.docker.com/engine/install/
> 
> Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
> but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;
> 
> * the Docker Support Forums - https://forums.docker.com
> * the [Docker community Slack channel](http://dockr.ly/slack)
> 
> I'm closing this issue because this is not a bug, but feel free to continue the conversation

Since the server machine can't connect the internet ,i have to install the docker from binaries. 
I got the guidance from this website  [https://docs.docker.com/engine/install/binaries/](https://docs.docker.com/engine/install/binaries/)
And get the 'docker-20.10.7.tgz ' from [https://download.docker.com/linux/static/stable/aarch64/]( https://download.docker.com/linux/static/stable/aarch64/)
After the installation,i can see the docker client version is 20.10.7,but the server version is 18.09.0.
I dont know why the server version was that old. I will try to install the docker with the rpm packages.
Thanks a lot!
