### ISSUE TITLE
Prevent downloading the same layer multiple times

### ISSUE THREAD

**Issue by hellodword** [docker/cli#5322] opened 2024-08-07 02:48 UTC
### Description

Occasionally, when pulling an image in a poor network environment, the process fails.

I frequently encounter this issue:

```
$ bash -c 'while ! docker pull messense/cargo-zigbuild; do (sleep 1s; echo;) done'
Using default tag: latest
latest: Pulling from messense/cargo-zigbuild
e9aef93137af: Already exists 
58b365fa3e8d: Already exists 
3dbed71fc544: Already exists 
ae70830af8b6: Already exists 
3143032220b6: Pull complete 
59ff22de6c6a: Pull complete 
f83562c5d442: Pull complete 
d778658c7f51: Pull complete 
8e13f2cc0a44: Downloading [==================================================>]  204.1MB/204.1MB
ed2e5aeccae6: Download complete 
unexpected EOF

Using default tag: latest
latest: Pulling from messense/cargo-zigbuild
e9aef93137af: Already exists 
58b365fa3e8d: Already exists 
3dbed71fc544: Already exists 
ae70830af8b6: Already exists 
3143032220b6: Downloading [========>                                          ]  16.64MB/92.92MB
```

The command will continue retrying until it eventually succeeds. Take the layer `3143032220b6` as an example; it will be downloaded repeatedly until the entire image is successfully pulled.

Is this necessary? Using a cache mechanism could improve the experience.

What do you think?

**Comment by vvoland** [comment] 2024-08-07 08:22
This works exactly like you described with the [containerd image store integration](https://docs.docker.com/storage/containerd/).

However, it's a double edge sword for now, as currently unfinished pulls are kept indefinitely (see https://github.com/docker/cli/issues/5315). The issue is on our radar though and should be fixed in future.

There are no plans to cache unfinished pulls in the graphdriver image store from our side, so we encourage you to try out the containerd image store integration.

**Closed by vvoland** 2024-08-07 08:22 UTC
Labels: kind/feature, status/0-triage
