### ISSUE TITLE
docker push no progress/quiet

### ISSUE THREAD

**Issue by nodesocket** [docker/cli#1930] opened 2019-06-07 05:31 UTC
When invoking `docker push` is it possible to prevent/silence progress output? We are running docker push via ci and the progress output is just noise:

```
[1A[1K[K
d891acc392cb: Preparing 
[1B
[1A[1K[K
b3e99984a4b0: Preparing 
[1B
[1A[1K[K
64dba8c34558: Preparing 
[1B
[1A[1K[K
33cb11d21cf8: Preparing 
[1B
[1A[1K[K
fb3d46525aec: Preparing 
[1B
[1A[1K[K
5b2786e728c6: Preparing 
[1B
[1A[1K[K
c428e44c182b: Preparing 
[1B
[1A[1K[K
bcd3b4a20235: Preparing 
[1B
[1A[1K[K
8770bed95480: Preparing 
[1B
[1A[1K[K
170acf861335: Preparing 
[1B
[1A[1K[K
62863de74578: Preparing 
[1B
[1A[1K[K
185f70eb62d5: Preparing 
[1B
[1A[1K[K
48ca928810cc: Preparing 
[1B
[1A[1K[K
ab6593fdb1dd: Preparing 
[1B
[1A[1K[K
3eda779c089e: Preparing 
[1B
[1A[1K[K
29dd3628a93e: Preparing 
[1B
[1A[1K[K
9558cd871e1a: Preparing 
[1B
[1A[1K[K
511a759fb701: Preparing 
[1B
[1A[1K[K
895802b60b42: Preparing 
[1B
[1A[1K[K
061fa9f2c26d: Preparing 
[1B
[1A[1K[K
fe0d1f11d16f: Preparing 
[1B
[1A[1K[K
cd713262a02b: Preparing 
[1B
[1A[1K[K
d42da8e0c3e4: Preparing 
[1B
[1A[1K[K
6270adb5794c: Preparing 
[1B[19A[1K[K
5b2786e728c6: Waiting 
[19B[18A[1K[K
c428e44c182b: Waiting 
[18B[17A[1K[K
bcd3b4a20235: Waiting 
[17B[16A[1K[K
8770bed95480: Waiting 
[16B[15A[1K[K
170acf861335: Waiting 
[15B[14A[1K[K
62863de74578: Waiting 
[14B[13A[1K[K
185f70eb62d5: Waiting 
[13B[12A[1K[K
48ca928810cc: Waiting 
[12B[11A[1K[K
ab6593fdb1dd: Waiting 
[11B[10A[1K[K
3eda779c089e: Waiting 
[10B[9A[1K[K
29dd3628a93e: Waiting 
[9B[8A[1K[K
9558cd871e1a: Waiting 
[8B[7A[1K[K
511a759fb701: Waiting 
[7B[6A[1K[K
895802b60b42: Waiting 
[6B[5A[1K[K
061fa9f2c26d: Waiting 
[5B[4A[1K[K
fe0d1f11d16f: Waiting 
[4B[3A[1K[K
cd713262a02b: Waiting 
[3B[2A[1K[K
d42da8e0c3e4: Waiting 
[2B[1A[1K[K
6270adb5794c: Waiting 
[1B[20A[1K[K
fb3d46525aec: Layer already exists 
[20B[21A[1K[K
33cb11d21cf8: Layer already exists 
[21B[22A[1K[K
64dba8c34558: Layer already exists 
[22B[19A[1K[K
5b2786e728c6: Layer already exists 
[19B[18A[1K[K
c428e44c182b: Layer already exists 
[18B[24A[1K[K
d891acc392cb: Pushing     512B/6.628kB
[24B[17A[1K[K
bcd3b4a20235: Layer already exists 
[17B[16A[1K[K
8770bed95480: Layer already exists 
[16B[24A[1K[K
d891acc392cb: Pushing  11.26kB
[24B[23A[1K[K
b3e99984a4b0: Pushing  551.4kB/379.7MB
[23B[15A[1K[K
170acf861335: Layer already exists 
[15B[14A[1K[K
62863de74578: Layer already exists 
[14B[13A[1K[K
185f70eb62d5: Layer already exists 
[13B[12A[1K[K
48ca928810cc: Layer already exists 
[12B[11A[1K[K
ab6593fdb1dd: Layer already exists 
[11B[10A[1K[K
3eda779c089e: Layer already exists 
[10B[23A[1K[K
b3e99984a4b0: Pushing  3.187MB/379.7MB
[23B[9A[1K[K
29dd3628a93e: Layer already exists 
[9B[8A[1K[K
9558cd871e1a: Layer already exists 
[8B[7A[1K[K
511a759fb701: Layer already exists 
[7B[6A[1K[K
895802b60b42: Layer already exists 
[6B[5A[1K[K
061fa9f2c26d: Layer already exists 
[5B[4A[1K[K
fe0d1f11d16f: Layer already exists 
[4B[23A[1K[K
b3e99984a4b0: Pushing  5.875MB/379.7MB
[23B[3A[1K[K
cd713262a02b: Layer already exists 
[3B[2A[1K[K
d42da8e0c3e4: Layer already exists 
[2B[1A[1K[K
6270adb5794c: Layer already exists 
[1B[23A[1K[K
b3e99984a4b0: Pushing  9.129MB/379.7MB
[23B[24A[1K[K
d891acc392cb: Pushed 
[24B[23A[1K[K
b3e99984a4b0: Pushing  11.91MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  15.76MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  18.45MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  21.15MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  23.82MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing   26.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  29.22MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  31.93MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  34.61MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  37.33MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  39.56MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  41.23MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  43.46MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  45.69MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing   47.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  50.68MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  53.46MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  56.25MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  59.03MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  61.82MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing   64.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  67.39MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  70.17MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  72.89MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  75.61MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing   78.3MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  80.98MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  83.74MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  86.49MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  89.78MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing   93.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  96.29MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  98.95MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  102.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  105.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  108.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  110.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  113.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  116.3MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  119.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  122.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  124.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  128.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  130.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  133.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  136.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  138.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  141.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  144.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  146.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  149.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  155.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    159MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  161.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  164.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  167.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  169.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  172.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  175.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  177.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  180.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  183.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  185.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  188.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  191.3MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    194MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  196.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  199.3MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  202.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  204.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  207.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  210.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  212.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  216.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  218.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  221.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  224.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  227.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  230.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  233.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  236.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  238.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    242MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  244.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  247.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  250.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  252.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    256MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  258.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  261.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  265.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  268.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  271.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  274.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  277.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  280.3MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    283MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  285.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  288.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  291.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  293.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  296.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  299.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  302.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  305.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    308MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  310.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  313.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  317.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  320.3MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    323MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  325.7MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  328.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  330.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  332.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  336.5MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  341.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  345.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  348.3MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  350.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  353.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  355.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  357.4MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  359.6MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  362.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  364.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing    367MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  370.2MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  372.9MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  376.1MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  378.8MB/379.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  381.4MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  384.1MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  386.2MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  388.8MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  391.5MB
[23B[23A[1K[K
b3e99984a4b0: Pushing  392.7MB
[23B[23A[1K[K
b3e99984a4b0: Pushed 
[23Ba4c2d86009.1559885258: digest: sha256:45a5eef0c4a0512733116ff93e23f49d6f09fd40464af44dcfd52da3328ed140 size: 534
```

**Comment by thaJeztah** [comment] 2019-06-24 16:17
looks like a duplicate of https://github.com/docker/cli/issues/958, and being worked on in https://github.com/docker/cli/pull/1221

**Closed by thaJeztah** 2019-06-24 16:17 UTC
Labels: area/distribution
