### ISSUE TITLE
docker login on windows has trouble escaping spaces embedded in a pem cert

### ISSUE THREAD

**Issue by red8888** [docker/cli#650] opened 2017-10-29 18:27 UTC
**Description**
docker login on windows has trouble escaping spaces embedded in a pem cert

**Steps to reproduce the issue:**
1. Following the steps here: https://cloud.google.com/container-registry/docs/advanced-authentication
2. Generate a json key for you GCP service account
3. Use docker login with username _json_key and pass in the key as text
4 Example: docker login -u _json_key -p $(cat my_service_account_key.json) https://gcr.io

**Describe the results you received:**
I have received this error:
`Error response from daemon: Get https://gcr.io/v2/: unknown: Unable to parse json key.`
I have also received an error complaining about the number of arguments I believe this is because its tokenizing the spaces in "-----BEGIN PRIVATE KEY-----". I have tried removing new lines, escaping the spaces in the BEGIN and END key statements but this never works.

**Describe the results you expected:**
Running the same command with the same key in a bash terminal succeeds. 

**Additional information you deem important (e.g. issue happens only occasionally):**
I think there is something wrong with how the docker cli in powershell is reading arguments. I have tried manipulating the json text is just about every way possible but it still doesn't work.

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: JJYR:LLO4:FPWH:OQPB:CAFP:DVCH:DNV2:VLJJ:K22S:HYCY:SZBD:7G7Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 25
 System Time: 2017-10-29T18:26:09.0534691Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2017-10-29 19:11
From the linked Google documentation, you'll have to put quotes around ` $(cat my_service_account_key.json)`, thus:

```bash
docker login -u _json_key -p "$(cat my_service_account_key.json)" https://gcr.io
```

From those docs:

<img width="871" alt="screen shot 2017-10-29 at 20 09 30" src="https://user-images.githubusercontent.com/1804568/32147296-4ab48b08-bce5-11e7-9605-bce9f080f052.png">

<img width="874" alt="screen shot 2017-10-29 at 20 09 24" src="https://user-images.githubusercontent.com/1804568/32147297-4aca58e8-bce5-11e7-921c-9d19d7259ce2.png">

If you're still running into issues, I'd recommend contacting Google support

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-10-29 19:11 UTC
Labels: area/distribution, version/17.09

**Comment by felberto** [comment] 2018-12-08 19:04
I work with windows and have followed this guide. Unfortunately, I still get this error message.
Does anyone have a solution?

**Comment by claude-uceda** [comment] 2020-02-28 14:11
Hello, I had it working on powershell using :
`cat my_service_account_key.json | docker login https://gcr.io -u _json_key --password-stdin`

I hope it helps

Cheers

**Comment by xucian** [comment] 2022-11-27 15:23
Tried solutions presented here. No luck. Any more guidelines?
The json file is in standard format:

```
{
  type: service_account,
  project_id: ...,
  etc.
}
```

The service account has read access to the repo
