### ISSUE TITLE
"docker service ps <service_name>" not showing all containers

### ISSUE THREAD

**Issue by uuid0** [docker/cli#3964] opened 2023-01-12 13:59 UTC
### Description

I hope, that this is not a duplicate. I've searched for the issue, but couldn't find anything.
Also there is a fair chance that I just missed a feature switch or something.
It might also be an issue with a different component of docker. If this is the case, please point me to it :)

`docker service ps <service_name>` is not showing containers that are still running after scaling down a service to 0 via `service update --replicas`.

It would also be good if `docker service ls` could show replicas "N/0" instead of "0/0" with N being the number of running containers.

Perhaps a word about my motivation: I have a swarm cluster with several nodes with a service, whose tasks take some time to shut down. I want to be able to stop these tasks and automatically detect when shutdown is done for all. 
I could connect to each host and use `docker ps`, but that would only be a workaround. 

### Reproduce

Hopefully anyone can reproduce my issue.

Preparation: Create any image that takes some time to shut down. E.g. catch SIGTERM and wait for a while before actually shutting down. Build that image and name it "test-image:latest".

1. `docker service create --mode replicated --replicas 3 --name test-service test-image:latest`
2. Ensure containers are showing with `docker service ps test-service`
3. `docker service update -d --replicas 0 --stop-grace-period 10m test-service`
4. After 30 seconds `docker service ps test-service`

### Expected behavior

I expect two things:
1. `docker service ps <service_name>` shows all containers that are still running as replicas of this service.
2. `docker service ls` shows "N/0" with N = number of containers still running.

### docker version

```bash
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12
  GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.2)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 16
  Running: 13
  Paused: 0
  Stopped: 3
 Images: 41
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: loki
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: <redacted>
  Is Manager: true
  ClusterID: <redacted>
  Managers: 1
  Nodes: 2
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: <redacted>
  Manager Addresses: <redacted>
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a05d175400b1145e5e6a735a6710579d181e7fb0
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.7GiB
 Name: <redacted>
 ID: <redacted>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

The `docker version` and `docker info` are pulled from a leader of a small cluster. All servers have the same hardware specs and employ the same software versions.

**Comment by sam-thibault** [comment] 2023-01-13 10:56
@neersighted @dperny can you comment if this is expected?

**Comment by uuid0** [comment] 2023-01-13 12:13
Another thing I just found out: `docker node ps` also doesn't show the containers after downscaling to 0, too.

**Comment by thaJeztah** [comment] 2023-01-13 13:32
I'd have to check the implementation (but perhaps @dperny or @neersighted know from the top of their head); it's possible the the swarm commands here show / use the swarm _task_, not the _container_, and in case of downscaling the task already being "gone" (while the reconciler is working in the background to reconcile state (i.e., removing/killing the container).

**Comment by dperny** [comment] 2023-01-13 18:50
I know the problem. You're scaling down and adjusting the stop grace period in the same operation, which is not counting the new stop grace period as part of stopping the current containers.

For my reproduction, I started with this image (thanks @neersighted):

```Dockerfile
FROM alpine:latest
COPY --from=kubernetes/pause:latest /pause /pause
ENTRYPOINT ["sh", "-c", "trap 'echo \"caught signal\"; /pause' INT TERM; /pause"]
```

Built it (ignore that it's tagged `:v2`, I whiffed my first build):

```
$ docker build -t test-pause:v2 .
```

Then, the output of my shell:

```
$ docker service create --name test1 --replicas 3 --stop-grace-period 10m test-pause:v2
image test-pause:v2 could not be accessed on a registry to record
its digest. Each node will access test-pause:v2 independently,
possibly leading to different nodes running different
versions of the image.

46hekhdpa1gjonn1ziw6npp0d
overall progress: 3 out of 3 tasks
1/3: running   [==================================================>]
2/3: running   [==================================================>]
3/3: running   [==================================================>]
verify: Waiting 5 seconds to verify that tasks are stable...

$ docker service ps test1
ID             NAME      IMAGE           NODE             DESIRED STATE   CURRENT STATE           ERROR     PORTS
7ov9x0h8gf2v   test1.1   test-pause:v2   docker-desktop   Running         Running 8 seconds ago
zgq26u1l1ate   test1.2   test-pause:v2   docker-desktop   Running         Running 8 seconds ago
30xfxeqlmisy   test1.3   test-pause:v2   docker-desktop   Running         Running 8 seconds ago
$ docker service update --replicas 0 test1
test1
overall progress: 0 out of 0 tasks
verify: Waiting 5 seconds to verify that tasks are stable...
$ docker service ps test1
ID             NAME      IMAGE           NODE             DESIRED STATE   CURRENT STATE           ERROR     PORTS
7ov9x0h8gf2v   test1.1   test-pause:v2   docker-desktop   Remove          Running 2 seconds ago
zgq26u1l1ate   test1.2   test-pause:v2   docker-desktop   Remove          Running 2 seconds ago
30xfxeqlmisy   test1.3   test-pause:v2   docker-desktop   Remove          Running 2 seconds ago
$ docker service create -d --name test2 --replicas 3 test-pause:v2
image test-pause:v2 could not be accessed on a registry to record
its digest. Each node will access test-pause:v2 independently,
possibly leading to different nodes running different
versions of the image.

pgy0uu7uywj75kc3v0v1k9vvf
$ docker service update --stop-grace-period 10m --replicas 0 test2
test2
overall progress: 0 out of 0 tasks
verify: Waiting 4 seconds to verify that tasks are stable...
$ docker service ls
ID             NAME      MODE         REPLICAS   IMAGE           PORTS
46hekhdpa1gj   test1     replicated   3/0        test-pause:v2
pgy0uu7uywj7   test2     replicated   0/0        test-pause:v2
$ docker service ps test2
ID        NAME      IMAGE     NODE      DESIRED STATE   CURRENT STATE   ERROR     PORTS
```

As you can see, starting the service (or, not pictured, first updating the service) with `--stop-grace-period 10m` causes the task turnover to respect the stop grace period. Scaling and updating the stop period in the same operation does not.

But, observe something else:

```
$ docker service create -d --name test4 --replicas 3 test-pause:v2
test4
$ docker service update -d --stop-grace-period 10m test4
test4
```

Then wait a moment (default stop grace period has to elapse first), and observe:

```
$ docker service ps test4
ID             NAME          IMAGE           NODE             DESIRED STATE   CURRENT STATE                 ERROR     PORTS
54bdsgzj256w   test4.1       test-pause:v2   docker-desktop   Running         Running about a minute ago
k5gnb29l7inr    \_ test4.1   test-pause:v2   docker-desktop   Shutdown        Shutdown about a minute ago
qrrii60prwdn   test4.2       test-pause:v2   docker-desktop   Running         Running about a minute ago
tf7z16t7yowq    \_ test4.2   test-pause:v2   docker-desktop   Shutdown        Shutdown about a minute ago
3c9neo1xzxmc   test4.3       test-pause:v2   docker-desktop   Running         Running about a minute ago
vjdlijbm4ku5    \_ test4.3   test-pause:v2   docker-desktop   Shutdown        Shutdown about a minute ago
 ```
 
The `stop-grace-period` option cannot be updated without also updating and turning over the tasks. So, when you're running the update with both the scaling and the `stop-grace-period` change in the same command, Swarm is scaling the task down, then creating the desired number of new tasks (zero) with the new spec. If you run two updates in very close order to each other (as in the example below), you observe the same behavior of the tasks shutting down without the grace period, because Swarm hasn't yet started the new tasks and so kills them before they start, instant shutdown.

```
$ docker service update -d --stop-grace-period 10m test3 && docker service update --replicas 0 test3
```

Hope this clears things up!

**Comment by uuid0** [comment] 2023-01-24 15:36
@dperny Thank you very much. With that information I was able to work around my issue!

I'm not sure if this is still a bug or if it is just behavior, that is not so intuitive, but expected.

**Comment by neersighted** [comment] 2023-01-24 15:47
I think it ultimately is the more straightforward implementation and avoids a special case that would feel quite gross, but it does violate the principle of least surprise. Swarm never really updates objects as I understand it; instead they are created and destroyed. So it makes sense that trying to change two things at once won't have an effect on the transition state to me, but only after internalizing the prior observation.

**Comment by thaJeztah** [comment] 2023-01-25 13:30
>  Swarm never really updates objects as I understand it

Yes, swarm task states can only move in one direction (create -> run -> die -> (retention limit) -> removed). Updating a service means that new tasks are created to replace the old ones, and the old ones are kept around for "retention limit".

**Comment by dperny** [comment] 2023-01-25 15:41
@thaJeztah We can close this issue.

**Closed** 2023-01-31 23:45 UTC
Labels: kind/bug, status/0-triage, area/swarm
