### ISSUE TITLE
TTY emulator broken for 17.06-rc2 on Windows

### ISSUE THREAD

**Issue by jefflill** [docker/cli#179] opened 2017-06-11 17:28 UTC
**Description**

I just switched from the stable **17.03** community release to edge **17.06-rc2** on Windows,  The TTY emulator doesn't appear to be converting LFs from the container into CR-LFs on the Windows side.

This seems like a critical problem that will break a lot of things.

**Steps to reproduce the issue:**
1. Install **17.06-rc2** on Windows
2. Start a container: `docker run -it --rm alpine sh`
3. Press the ENTER key a few times.

**Describe the results you received:**

Note how the Linux prompt is indented after each.

```
C:\src\NeonForge\Images\neon-cli>docker run -it --rm alpine sh
/ #
    / #
        / #
            / #
                / #
                    / #
                        / #
                            / #
```

**Describe the results you expected:**

Expected to see CRLFs so each new line starts at column 0 in my window.,

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce-rc2
 API version:  1.30
 Go version:   go1.8.1
 Git commit:   402dd4a
 Built:        Wed Jun  7 10:01:32 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce-rc2
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   402dd4a
 Built:        Wed Jun  7 10:02:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 153
Server Version: 17.06.0-ce-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 167
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 992a5be178a62e026f4069f443c6164912adbf09
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.30-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: UQXS:6ZYI:NP6F:3IN5:AKMV:KUAF:FJDX:B3BS:P2PQ:PFWT:OPDQ:6OFQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by dnephin** [comment] 2017-06-11 21:32
Thanks for the bug report. This was an incompatibility caused by a change in runc. it will be fixed in rc3.

**Comment by thaJeztah** [comment] 2017-06-13 13:45
Yes, this was resolved by https://github.com/moby/moby/pull/33577 which will be in rc3 as mentioned above (which will be available probably tomorrow).

I'll close this issue, but thanks again for reporting, and feel free to comment 👍

**Closed by thaJeztah** 2017-06-13 13:45 UTC
Labels: version/17.06
