### ISSUE TITLE
docker volume prune keeps dangling volumes

### ISSUE THREAD

**Issue by CTaeumel** [docker/cli#4015] opened 2023-02-09 08:22 UTC
### Description

System: Ubuntu Server 20.04/22.04 - tested on fresh install as well as old systems with current package updates

When running docker volume prune, it deletes no volumes.

### Reproduce

1. docker volume create test
2. docker volume prune
--> test-volume is not deleted

### Expected behavior

test-volume is deleted

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:49:08 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:49:08 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-137-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.771GiB
 Name: sandbox-ubuntu-2004
 ID: b646fedd-c911-41ec-991d-152dc0ed73ff
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by manuelmaurer** [comment] 2023-02-09 10:49
Same problem here. 

Source seems to be the change introduced in API v1.42 with the new all-Filter for the prune command: https://docs.docker.com/engine/api/v1.42/#tag/Volume/operation/VolumePrune (last point in the changelog here: https://docs.docker.com/engine/api/version-history/) which changes the default behaviour.


Passing the filter to the cli will switch to the old behaviour. 
`docker volume prune --filter "all=true"`

**Comment by bsousaa** [comment] 2023-02-09 11:24
Related discussion: https://github.com/docker/desktop-linux/issues/119

**Comment by neersighted** [comment] 2023-02-10 05:05
Indeed, not a bug, but a place where the CLI needs to improve. It's unfortunate that the discussion happened on the other issue tracker, as it would have been nice to have it all in one place ehre.

**Comment by thaJeztah** [comment] 2023-02-14 11:05
I transferred the other ticket to this repository; let me close this one in favour of https://github.com/docker/cli/issues/4028 to prevent the conversation from diverging.

**Closed by thaJeztah** 2023-02-14 11:05 UTC
Labels: kind/docs, status/0-triage, area/volumes, area/ux, version/23.0
