### ISSUE TITLE
docker service update more than 1 hour

### ISSUE THREAD

**Issue by slzzz** [docker/cli#2867] opened 2020-12-07 06:27 UTC
* [x] This is a bug report

### Actual behavior
When running `sudo docker service update --with-registry-auth --force --image=image service_name., return `overall progress: 1 out of 2 tasks` more than 1 hour

### Steps to reproduce the behavior
```
+ sudo docker service update --with-registry-auth --force --image=image proxy_nginx
proxy_nginx
overall progress: 0 out of 2 tasks
1/2:  
2/2:  
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
overall progress: 0 out of 2 tasks
...
```

**Output of `docker version`:**

```
Server Version: 18.06.0-ce
```

**Output of `docker info`:**

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 53
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rexray
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: active
 NodeID: uxms452xkliih7drgh5c5qr2p
 Is Manager: true
 ClusterID: ukieu44l1z5qwlh9witqmhvqj
 Managers: 2
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.31.14.182
 Manager Addresses:
  172.31.14.182:2377
  172.31.6.29:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-139-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.857GiB
Name: ip-172-31-14-182
ID: 7AUS:AEQR:VHBB:ASIK:3QUA:4COA:MJ6T:NNGZ:PH3A:IS6V:LRKN:KUT2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
 https://lihw.m.daocloud.io/
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.)**
aws ec2

**Comment by thaJeztah** [comment] 2020-12-07 11:20
looks like a duplicate of https://github.com/docker/cli/issues/2866

**Closed by thaJeztah** 2020-12-07 11:20 UTC
