### ISSUE TITLE
ARG before FROM is unassigned after the FROM

### ISSUE THREAD

**Issue by dsanchezseco** [docker/cli#1153] opened 2018-06-28 10:17 UTC
Using ARG before the FROM makes the ARG available just for the FROM, afterwards its unassigned and needs to be declared again

Dockerfile
```
  ARG FOO
  
  FROM alpine
  
  ARG BAR
  RUN echo $FOO $BAR
```

running `docker build --build-arg FOO=foo --build-arg BAR=bar .` returns:

```Sending build context to Docker daemon  2.048kB
Step 1/4 : ARG FOO
Step 2/4 : FROM alpine
 ---> 3fd9065eaf02
Step 3/4 : ARG BAR
 ---> Using cache
 ---> 9c7e110a0dbc
Step 4/4 : RUN echo $FOO $BAR
 ---> Running in 7e2dca5b21b2
bar                                                    # notice the missing 'foo'
Removing intermediate container 7e2dca5b21b2
 ---> e410f94fe307
Successfully built e410f94fe307
```

**Describe the results you expected:**

``` Sending build context to Docker daemon  2.048kB
Step 1/4 : ARG FOO
Step 2/4 : FROM alpine
 ---> 3fd9065eaf02
Step 3/4 : ARG BAR
 ---> Using cache
 ---> 9c7e110a0dbc
Step 4/4 : RUN echo $FOO $BAR
 ---> Running in 7e2dca5b21b2
foo bar                                                    # "foo" is returned along "bar"
Removing intermediate container 7e2dca5b21b2
 ---> e410f94fe307
Successfully built e410f94fe307
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false


```

**Output of `docker info`:**

```Containers: 89
 Running: 0
 Paused: 0
 Stopped: 89
Images: 260
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.6.7-040607-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55GiB
Name: lich
ID: 6DJ2:WSYQ:4MMC:5ZFW:YVFE:Z6RS:RA3Q:IHTJ:3HD5:EXUA:7ZQW:KOMU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support


```

**Comment by thaJeztah** [comment] 2018-06-28 11:31
Yes, this is by design; each build-stage (a build-stage starts after the `FROM`) is a new "scope" inside this scope, only `ARG`'s that are declared inside that build-stage will be available. "Global" (declared before the first `FROM`) `ARG` can be used to assign a default value, but the `ARG` will not automatically be available in all build-stages, and must be explicitly defined/declared in each stage.


Let me close this issue, because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2018-06-28 11:31 UTC
Labels: area/builder

**Comment by dsanchezseco** [comment] 2018-06-28 11:39
Ok, i supposed it.

What about a GLOBAL(or similar) tag that is a true global ARG that is available in all the build stages? I think in some cases it could be useful.
