### ISSUE TITLE
ADD/COPY ../.gn(parent folder container dot prefix file) failed

### ISSUE THREAD

**Issue by pedia** [docker/cli#3102] opened 2021-05-21 04:18 UTC
```
ADD/COPY ../.gn failed.
```

**Steps to reproduce the issue:**
1. `touch .gn`
2. `mkdir src1`
3. 
 
```bash
cat > src1/Dockerfile \
FROM ubuntu:20.10 \
ADD .. . \
RUN test -e .gn
```
4 `docker build src1`

**Describe the results you received:**
```
 => [internal] load build definition from Dockerfile                                                                                    0.0s
 => => transferring dockerfile: 36B                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                       0.0s
 => => transferring context: 2B                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.10                                                                         0.0s
 => [internal] load build context                                                                                                       0.0s
 => => transferring context: 31B                                                                                                        0.0s
 => [1/3] FROM docker.io/library/ubuntu:20.10                                                                                           0.0s
 => CACHED [2/3] ADD .. .                                                                                                               0.0s
 => ERROR [3/3] RUN test -e .gn                                                                                                         0.3s
------
 > [3/3] RUN test -e .gn:
------
executor failed running [/bin/sh -c test -e .gn]: exit code: 1
```

And code below failed too:
```
COPY .. .
ADD ../.gn .
```

**Describe the results you expected:**
ADD/COPY .. parent folder

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 48
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 9.732GiB
 Name: docker-desktop
 ID: EGBE:ZRWU:KOCS:5N46:HYC6:HSRA:3CHX:2X6O:573V:KYEO:EK5I:IV2X
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.mirrors.ustc.edu.cn/
 Live Restore Enabled: false```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2021-05-21 15:48
Thanks! So this is both "expected", and it looks like there's a bug (and improvements to be made) in BuildKit.

When you build a Dockerfile, the last argument of the `docker build` command specifies the "build context". The Dockerfile only has access to files within that context (which is by design). Dockerfiles cannot reference files outside of the context, so `COPY ../../somefile .` therefore fails.

The "classic builder" prints an error in this case:

```
COPY failed: forbidden path outside the build context: .. ()
```

But unfortunately, BuildKit (not yet) has an equally useful error (some issues arround that are tracked in https://github.com/moby/buildkit/issues/1647)

If (in your case), you want to build using files from the local directory, specify that directory as build-context, and make sure that all "source" (`COPY <source> <dest>`) paths within the Dockerfile are relative to that directory. You can use a Dockerfile that's in a different location (using the `-f` option), but `<source>` paths within the Dockerfile always are relative to the context directory.

For example, your `src/Dockerfile would use:

```dockerfile
FROM ubuntu:20.10
ADD .gn ,
RUN test -e .gn
```

And to build:

```bash
docker build -f src/Dockerfile .
```

Where

- `-f` specifies the path of the Dockerfile
- `.` specifies the path of the Build context to use (current directory)


However, it looks like there's also a bug in BuildKit; my triage of that issue below (I'll open a ticket in BuildKit as well)


Setup:

```bash
mkdir test && cd test
mkdir src
touch somefile
```

We should now have:

```bash
tree
.
├── somefile
└── src
    └── Dockerfile

1 directory, 2 files
```

### case 1 - copying parent directory

```bash
cat > src/Dockerfile <<EOF
FROM busybox
COPY .. .
RUN test -e somefile
EOF
```

With BuildKit

```bash
DOCKER_BUILDKIT=1 docker build src
[+] Building 0.5s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.1s
 => => transferring dockerfile: 86B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/busybox:latest                                                                                                                                      0.0s
 => [internal] load build context                                                                                                                                                                      0.0s
 => => transferring context: 81B                                                                                                                                                                       0.0s
 => CACHED [1/3] FROM docker.io/library/busybox                                                                                                                                                        0.0s
 => [2/3] COPY .. .                                                                                                                                                                                    0.1s
 => ERROR [3/3] RUN test -e somefile                                                                                                                                                                   0.3s
------
 > [3/3] RUN test -e somefile:
------
executor failed running [/bin/sh -c test -e somefile]: exit code: 1
```

Without BuildKit:

```bash
DOCKER_BUILDKIT=0 docker build src
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM busybox
 ---> 388056c9a683
Step 2/3 : COPY .. .
COPY failed: forbidden path outside the build context: .. ()
```

### case 2 - copying file from parent directory

```bash
cat > src/Dockerfile <<EOF
FROM busybox
COPY ../somefile .
RUN test -e somefile
EOF
```

With BuildKit

```bash
DOCKER_BUILDKIT=1 docker build src
[+] Building 0.2s (6/7)
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 95B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/busybox:latest                                                                                                                                      0.0s
 => [internal] load build context                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => CACHED [1/3] FROM docker.io/library/busybox                                                                                                                                                        0.0s
 => ERROR [2/3] COPY ../somefile .                                                                                                                                                                     0.0s
------
 > [2/3] COPY ../somefile .:
------
failed to compute cache key: "/somefile" not found: not found
```

Without BuildKit

```bash
DOCKER_BUILDKIT=0 docker build src
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM busybox
 ---> 388056c9a683
Step 2/3 : COPY ../somefile .
COPY failed: forbidden path outside the build context: ../somefile ()
```

## Bug: BuildKit converts path to "absolute"

For "case 1", what appears to happen is that BuildKit converts the path to an absolute path. In the `..` case, this results in `..` to be converted to `.`.

To verify this, use the following dockerfile:


```bash
cat > src/Dockerfile <<EOF
FROM busybox
COPY .. .
RUN test -e Dockerfile
EOF
```

Building the Dockerfile completes succesfully:

```bash
DOCKER_BUILDKIT=1 docker build src
[+] Building 0.5s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 88B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/busybox:latest                                                                                                                                      0.0s
 => [internal] load build context                                                                                                                                                                      0.0s
 => => transferring context: 83B                                                                                                                                                                       0.0s
 => CACHED [1/3] FROM docker.io/library/busybox                                                                                                                                                        0.0s
 => [2/3] COPY .. .                                                                                                                                                                                    0.0s
 => [3/3] RUN test -e Dockerfile                                                                                                                                                                       0.3s
 => exporting to image                                                                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                                                                0.0s
 => => writing image sha256:28228b0cbcba144d527ee6114f14bf06689a1b0d7eb45f8211b04433b7104897                                                                                                           0.0s
```

Same with this:


```bash
cat > src/Dockerfile <<EOF
FROM busybox
COPY ../Dockerfile .
RUN test -e Dockerfile
EOF
```

```bash
[+] Building 0.5s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 99B                                                                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/busybox:latest                                                                                                                                      0.0s
 => CACHED [1/3] FROM docker.io/library/busybox                                                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                                                      0.0s
 => => transferring context: 94B                                                                                                                                                                       0.0s
 => [2/3] COPY ../Dockerfile .                                                                                                                                                                         0.0s
 => [3/3] RUN test -e Dockerfile                                                                                                                                                                       0.3s
 => exporting to image                                                                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                                                                0.0s
 => => writing image sha256:497f3eccd98edf6403d41ed5671bd0530022539602d317d38d7b5401ebde9172                                                                                                           0.0s
```

It _should_ fail, as `Dockerfile` is not within `../`, but because BuildKit converts `../` (outside of the `src/` build-context) to `.`, it now copies `src/Dockerfile`, which definitely looks like a bug.

**Comment by thaJeztah** [comment] 2021-05-21 15:53
I opened https://github.com/moby/buildkit/issues/2130 and https://github.com/moby/buildkit/issues/2131

Given that the "problem" is expected, and the bugs are related to BuildKit, I'll close this ticket in favour of the ones linked, but I hope my answer helps, and feel free to continue the conversation after I closed 👍

**Closed by thaJeztah** 2021-05-21 15:53 UTC
Labels: area/builder

**Comment by pedia** [comment] 2021-05-22 06:39
This is very helpful. Thank you.
