### ISSUE TITLE
RUN chown command does not work as expected

### ISSUE THREAD

**Issue by vibinvismi** [docker/cli#4481] opened 2023-08-04 10:31 UTC
### Description

RUN chown command does not change ownership of files and folders as expected. We noticed this issue on docker version 20.10.25, build 20.10.25-0ubuntu1~22.04.1
Files and folder ownership is still root even after the chown step in Dockerfile

### Reproduce

COPY . ${test-folder}
RUN chown -R ${test-user}:${test-user}
USER ${test-user}
RUN ls -la ${test-folder}

### Expected behavior

chown command works and ownership of files and folders are set as instructed in the Dockerfile

### docker version

```bash
Client:
 Version:           20.10.25
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.25-0ubuntu1~22.04.1
 Built:             Fri Jul 14 21:58:09 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 83
  Running: 0
  Paused: 0
  Stopped: 83
 Images: 189
 Server Version: 20.10.25
```

**Comment by vvoland** [comment] 2023-08-04 11:26
Please provide a complete working Dockerfile and the exact command you use to build it.

**Comment by stomsin-econolite** [comment] 2023-08-04 13:53
The following now fails
```
cd $(mktemp -d);

cat > Dockerfile << "END"
FROM ubuntu:22.04

ARG user=ubuntu
RUN useradd -U -m $user && [ "$(stat --format '%U' /home/$user)" = "$user" ]
RUN ls -al /home

USER ubuntu
WORKDIR /home/ubuntu
RUN stat "$(realpath .)"; [ "$(stat --format '%U' .)" = "$user" ]
END

docker build --force-rm .
```
Doesn't work with
Docker version 20.10.25, build 20.10.25-0ubuntu1~22.04.1

Does work with
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.3
![Screenshot from 2023-08-04 01-58-09](https://github.com/docker/cli/assets/141427202/668b7272-4415-44b6-b33e-141bfbde0c84)

**Comment by stomsin-econolite** [comment] 2023-08-04 16:03
I appreciate the quick investigation; I created https://bugs.launchpad.net/ubuntu/+source/docker.io-app/+bug/2029893

**Comment by thaJeztah** [comment] 2023-08-07 10:24
This looks like a duplicate of https://github.com/moby/moby/issues/46161

In that ticket, someone else also opened a ticket in the Ubuntu issue tracker; https://github.com/moby/moby/issues/46161#issuecomment-1667255217

> Bug reported in https://bugs.launchpad.net/ubuntu/+source/docker.io/+bug/2029564
> 
> You can revert to previous release of docker.io on Ubuntu 22.04. You can also `apt-mark hold` this package to prevent any update to occur until it is fixed.


Let me close this ticket, as this looks to be a packaging issue with Ubuntu's packages, but feel free to continue the conversation.

**Closed by thaJeztah** 2023-08-07 10:24 UTC
Labels: kind/bug, area/builder, status/more-info-needed, version/20.10
