### ISSUE TITLE
First line in .dockerignore is ignored if file is saved in encoding "UTF-8 with BOM"

### ISSUE THREAD

**Issue by robertsynoradzki** [docker/cli#4269] opened 2023-05-08 12:21 UTC
### Description

The Byte Order Mark in **UTF-8 with BOM** encoding causes the first line of `.dockerignore` to be invalid. Seems like the first three magic bytes (`0xEF 0xBB 0xBF`) are interpreted as part of a real path, which subsequently cannot be found, and is copied to build context instead of being skipped.

### Reproduce

1. Go to any of your git repositories that already contains code that can be built via Docker.
2. Build Docker image and observe how many files are copied to build context (100 in my case).
3. Create a `.dockerignore` with content `**`.
4. Save as **UTF-8** (without BOM)!
5. Build image and observe that very few files are copied into the build context (3 in my case).
6. Now re-save the `.dockerignore` file using **UTF-8 with BOM** encoding.
7. Build image and observe that all the files, again, are copied to build context (100 in my case).
8. Add another line to `.dockerignore` with the same value `**` (now you should have two lines, both equal to `**`).
9. Build image and observe that few files are copied to the context again (3 in my case).

### Expected behavior

If the file is saved in **UTF-8 with BOM** encoding, first three magic bytes `0xEF 0xBB 0xBF` should be ignored and the first line in the file should correctly apply a path ignoring rule.

In other words, Docker should support **UTF-8 with BOM** encoding, just like it supports plain **UTF-8**.

### docker version

```bash
Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:20:14 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.46GiB
 Name: docker-desktop
 ID: 69496906-cffa-4f24-9adc-f89cd25a9b3b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by thaJeztah** [comment] 2023-05-11 13:54
Looks like the classic (non-buildkit) builder had code to strip it from `.dockerignore`, and that's probably not implemented in BuildKit; https://github.com/moby/moby/blob/d922f94d9395f9554570c2d45b7f94ddb327be23/integration-cli/docker_cli_build_test.go#L5160-L5175 or at least there's a test for that;

```go
// Test case for UTF-8 BOM in .dockerignore, related to #23221
func (s *DockerCLIBuildSuite) TestBuildWithUTF8BOMDockerignore(c *testing.T) {
	name := "test-with-utf8-bom-dockerignore"
	dockerfile := `
        FROM busybox
		ADD . /tmp/
		RUN ls -la /tmp
		RUN sh -c "! ls /tmp/Dockerfile"
		RUN ls /tmp/.dockerignore`
	dockerignore := []byte("./Dockerfile\n")
	bomDockerignore := append([]byte{0xEF, 0xBB, 0xBF}, dockerignore...)
	buildImageSuccessfully(c, name, build.WithBuildContext(c,
		build.WithFile("Dockerfile", dockerfile),
		build.WithFile(".dockerignore", string(bomDockerignore)),
	))
}
```

**Comment by thaJeztah** [comment] 2023-05-11 13:54
@crazy-max @jedevc can you have a look?

**Comment by jedevc** [comment] 2023-05-11 14:39
:thinking:

https://github.com/moby/buildkit/blob/81d19ad945cdbf921d182c50fc91169b1375b44d/frontend/dockerfile/dockerignore/dockerignore.go#L25-L31

We definitely seem to have a check for it.

**Comment by jedevc** [comment] 2023-05-11 14:41
@robertsynoradzki could you share your `.dockerignore`? Ideally as a hexdump or similar:

```bash
$ xxd .dockerignore
00000000: 6269 6e0a 2e63 6572 7473 0a2e 746d 700a  bin..certs..tmp.
```

**Comment by robertsynoradzki** [comment] 2023-05-19 08:26
```
$ xxd .dockerignore
00000000: efbb bf2a 2a                             ...**
```
- `EF BB BF` is the UTF-8 BOM
- `2A 2A` is `**`, the "exclude all" pattern

**Comment by robertsynoradzki** [comment] 2023-05-21 10:24
My build command's working directory is repository root and its two arguments are `-f PATH\Dockerfile .`, where `-f` points to `Dockerfile` in subdirectory but `.` sets the build context back to repository root, where you can also find my `.dockerignore`.

My `.dockerignore` is in location other than `Dockerfile` because it gets ignored if it's not found directly in the root of build context, and AFAIK there is no build argument to provide path to it.

**Comment by jedevc** [comment] 2023-05-22 09:50
@robertsynoradzki can you provide a github repo or gist or something so I can try on exactly what you're doing? I still can't manage to reproduce this.

FYI, if you want to put the dockerignore file into the same directory as the Dockerfile, you can, by naming the dockerignore file `Dockerfile.dockerignore`.

**Comment by robertsynoradzki** [comment] 2023-05-23 11:24
I've been trying to prepare a sample repository with the reproduction for you and I also couldn't do it. Seems like running `docker build` from the console works correctly, while I am using Docker via JetBrains Rider, which seems to have a pipe established to Docker Desktop:

![image](https://github.com/docker/cli/assets/19998579/eee9a204-7741-475c-98f8-f60fcf8f79e8)

The problem must lie somewhere there then - I'm deeply sorry for causing confusion (I was confused myself), I guess the root cause is not in the CLI, but I don't know where it is, so I guess I will have to live with it.

P.S.
That `Dockerfile.dockerignore` trick unfortunately does not work with BuildKit disabled.

**Comment by bsousaa** [comment] 2023-05-26 13:48
Thanks for letting us know. I will close the issue.

**Closed by bsousaa** 2023-05-26 13:48 UTC
Labels: kind/bug, status/0-triage, area/builder, status/more-info-needed, version/23.0
