### ISSUE TITLE
Filebeat service does not run inside container with systemd during docker run

### ISSUE THREAD

**Issue by venkat-koppisetti** [docker/cli#1150] opened 2018-06-27 13:02 UTC
**Description**

I want to create a container with systemd init process as PID 1 and filebeat service should be run as a child to PID 1. The filebeat service is starting through python script and that would be executed by docker ENTRYPOINT.
The container is running with /usr/sbin/init process as PID 1 but it is unable to start the filebeat service, but if i execute the same python script manually inside the container, filebeat service is running

**Steps to reproduce the issue:**
1. docker build -t filebeat_img .
2. docker run -itd --privileged --name filebeat_cont filebeat_img
3. docker exec -it filebeat_cont bash
4. ps -ef

**Describe the results you received:**
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 12:55 ?        00:00:00 /usr/sbin/init
root        49     1  0 12:55 ?        00:00:00 /usr/lib/systemd/systemd-journald
root        61     1  1 12:55 ?        00:00:00 /usr/lib/systemd/systemd-udevd
dbus        88     1  0 12:55 ?        00:00:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root        89     1  0 12:55 ?        00:00:00 /usr/lib/systemd/systemd-logind
root        93     1  0 12:55 tty1     00:00:00 /sbin/agetty --noclear tty1 linux
root        94     1  0 12:55 console  00:00:00 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
root       108     0  0 12:55 pts/1    00:00:00 bash
root       122   108  0 12:55 pts/1    00:00:00 ps -ef

**Describe the results you expected:**
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 12:55 ?        00:00:00 /usr/sbin/init
root        49     1  0 12:55 ?        00:00:00 /usr/lib/systemd/systemd-journald
root        61     1  0 12:55 ?        00:00:00 /usr/lib/systemd/systemd-udevd
dbus        88     1  0 12:55 ?        00:00:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root        89     1  0 12:55 ?        00:00:00 /usr/lib/systemd/systemd-logind
root        93     1  0 12:55 tty1     00:00:00 /sbin/agetty --noclear tty1 linux
root        94     1  0 12:55 console  00:00:00 /sbin/agetty --noclear --keep-baud console 115200 38400 9600 linux
root       108     0  0 12:55 pts/1    00:00:00 bash
root       142     1  0 12:56 ?        00:00:00 /usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat
root       149   108  0 12:56 pts/1    00:00:00 ps -ef

**Output of `docker version`:**

[root@localhost filebeat_test]# docker -v
Docker version 18.03.0-ce, build 0520e24

**Output of `docker info`:**

[root@localhost filebeat_test]# docker info
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 483
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-693.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: localhost.localdomain
ID: QSFU:ODKS:LJGZ:GC34:KXTP:6B7Y:5UMB:Q7WT:V2X3:4K6M:DFLQ:I7WS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running Docker in a VirtualBox
[filebeat_test.zip](https://github.com/docker/cli/files/2141281/filebeat_test.zip)

**Comment by cpuguy83** [comment] 2018-06-27 17:36
Have you checked to see if systemd even tried to start it?

Did you check journald for failures?

From Docker's perspective it started systemd and is done, from there it's up to what's in the container to do what it needs.

**Comment by venkat-koppisetti** [comment] 2018-06-28 10:16
Plz find the attached file for journalctl logs.
[journalctl.log](https://github.com/docker/cli/files/2144822/journalctl.log)


i have tried with --init option in docker run command, but  i found through docker logs that the filebeat service is starting 

[root@localhost filebeat_test]# docker logs filebeat
Failed to get D-Bus connection: Operation not permitted
Starting filebeat: 2018-06-28T10:21:12.084Z     INFO    instance/beat.go:468    Home path: [/usr/share/filebeat] Config path: [/etc/filebeat] Data path: [/var/lib/filebeat] Logs path: [/var/log/filebeat]
2018-06-28T10:21:12.085Z        INFO    instance/beat.go:475    Beat UUID: 43a21248-71a6-4727-afda-350d1ee73a8f
2018-06-28T10:21:12.085Z        INFO    instance/beat.go:213    Setup Beat: filebeat; Version: 6.2.3
2018-06-28T10:21:12.085Z        INFO    pipeline/module.go:76   Beat name: 75dbe4786930
Config OK
                                                           [  OK  ]
[root@localhost filebeat_test]#

**Comment by thaJeztah** [comment] 2018-06-28 13:34
```
Failed to get D-Bus connection: Operation not permitted
```

This seems to indicate systemd didn't start properly; you can find some existing discussions in the Moby repository; https://github.com/moby/moby/issues?utf8=✓&q=is%3Aissue+%22Failed+to+get+D-Bus+connection%22+, and you can find various examples there on how to run systemd in the container. Here's one example I wrote up; https://github.com/moby/moby/issues/2296#issuecomment-238530205


> The filebeat service is starting through python script and that would be executed by docker ENTRYPOINT.

I'm not sure I understand this part of your description; shouldn't the filebeat service be started by systemd? If you're overriding the entrypoint, either systemd won't be started, or systemd ends up running as PID2

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/cli/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2018-06-28 13:34 UTC
Labels: area/builder
