### ISSUE TITLE
In docker,  how to decide the num of file handler?

### ISSUE THREAD

**Issue by bobo200128docker** [docker/cli#703] opened 2017-11-18 05:49 UTC
I am using ubuntu 14.04 and 16.04 as the host.

in the file /etc/init.d/docker，I saw this description。
ulimit -n 1048576
                if [ "$BASH" ]; then
                        ulimit -u 1048576
                else
                        ulimit -p 1048576
                fi

but when I run cmd ulimit -a on the docker,the num is not same to the expect(1048576)
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2062339
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) **524288**
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 524288
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

I donnot know where can I ask this question and first of all I ask here.
Can you help me?

**Comment by thaJeztah** [comment] 2017-11-21 15:48
How did you start the daemon; was it started through `sysvinit` or was the daemon manually started? Note that on Ubuntu 16.04, systemd is the default init manager, in which case the `/etc/init.d/docker` configuration is not used, but the configuration as is set in the systemd unit; https://github.com/docker/docker-ce-packaging/blob/master/deb/systemd/docker.service#L15.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2017-11-21 15:48 UTC
