### ISSUE TITLE
container_linux.go:247: starting container process caused "open /proc/self/fd: no such file or directory" oci runtime error: container_linux.go:247: starting container process caused "open /proc/self/fd: no such file or directory"

### ISSUE THREAD

**Issue by yangwliu** [docker/cli#1799] opened 2019-04-03 05:30 UTC
**Description**
I have a problem, when running docker run command. I have can run some docker images successfully on centos, but sometimes, it throw the exception when i run a docker images base on node. I have run three container on the same service(python, redis and mysql). However the node can not run successfully. I run the node docker images successfully several times, but most time it failed and withe the above exception.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.13.1, build b2f74b2/1.13.1
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 17
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: df5c38a9167e87f53a9894d77c0950e178a745e7 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-693.21.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 3.702 GiB
Name: ebs-65300
ID: ZJWZ:CLIH:UC26:DMMO:BKFZ:J5BA:TSHN:NNQ4:LXKH:52XB:AJBC:5PWB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment] 2019-04-03 08:51
It looks like you're running the Red Hat fork of Docker https://github.com/projectatomic/docker/commit/b2f74b2, which has a large number of modifications in the codebase https://github.com/moby/moby/compare/v1.13.1..projectatomic:b2f74b2 that are not in the official Docker codebase, and have known to cause problems many times in the past.

Unfortunately, we can't provide support for that version.

Note that Docker 1.13 reached EOL in March 2017, and is no longer maintained. Are you still able to reproduce this with the current version of the official packages? https://docs.docker.com/install/linux/docker-ce/centos/


Note that your version of CentOS also seems to be a bit behind (kernel 3.10.0-693; current version of the CentOS kernel is `3.10.0-957.1.3`), and I'd recommend updating that as well.


I'm closing this because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2019-04-03 08:51 UTC
Labels: version/1.13
