### ISSUE TITLE
Please add a `--cache` option to `docker pull`

### ISSUE THREAD

**Issue by auwsom** [docker/cli#3362] opened 2021-11-11 18:55 UTC
Hello, could we add a `--cache` option to `docker pull` so that if people run out of disk space right at the end of a several GB container download, they don't have to start downloading from scratch? I know most devs are bandwidth constrained, but a lot of home users are. Thank you

If there is one, I missed it and didn't see the option in `docker pull --help`.

**Comment by thaJeztah** [comment] 2021-11-12 14:59
Thanks for opening this ticket; this is something that would have to be supported by the daemon (which does the actual pull); there's an existing ticket tracking this, but it's (unfortunately) somewhat complicated, and has not yet been implemented; https://github.com/moby/moby/issues/26146


Let me close this ticket as duplicate of https://github.com/moby/moby/issues/26146, but feel free to continue the conversation.

**Closed by thaJeztah** 2021-11-12 14:59 UTC
Labels: kind/enhancement, area/distribution
