### ISSUE TITLE
Allow rootless Docker to keep host UID/GID

### ISSUE THREAD

**Issue by Tyrubias** [docker/cli#3086] opened 2021-05-08 10:54 UTC
It's common for certain images (for example, [the LinuxServer group](https://www.linuxserver.io/)'s images to start the container as a user with the same UID to avoid permission issues. However, with the user namespace remap in rootless Docker, this no longer works. For example, if I attempt to start a container as a user with UID `1000`, it is remapped to `10099`.

Currently, Podman [provides a feature](http://docs.podman.io/en/latest/markdown/podman-create.1.html?highlight=userns#userns-mode) which allows a rootless container's user to have the same UID/GID as the user starting the container. Would it be possible to implement this for rootless Docker?

A concrete example: When I map a folder from my host into a Docker container, I have to run as root in the container (which I'm not comfortable with) in order to create any files inside the mapped folder. This feature would solve that issue.

**Comment by AkihiroSuda** [comment] 2021-05-24 07:04
Duplicate of https://github.com/moby/moby/issues/41497

**Closed by AkihiroSuda** 2021-05-24 07:04 UTC
