### ISSUE TITLE
[19.03] “docker images [name]” not listing the images as expected

### ISSUE THREAD

**Issue by TusharParasrampuria** [docker/cli#2597] opened 2020-06-22 13:23 UTC
**Description**
In docker 19.03 the `docker images [name]` command is not working as expected. It should have listed images with matching names but instead it gives empty result.

**Steps to reproduce the issue:**
1.Give command `docker images [name]` on docker 19.03

**Describe the results you received:**
```
# docker images test
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```
**Describe the results you expected:**
```
# docker images test
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
test                ab                  1c35c4412082        2 weeks ago         1.22MB
```

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue was not present in docker 17.06 (which i tested).

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.1-ol
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        ead9442
 Built:             Wed Sep 11 06:40:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1-ol
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       ead9442
  Built:            Wed Sep 11 06:38:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
  Default Registry: docker.io
 containerd:
  Version:          v1.2.0-rc.0-108-gc444666
  GitCommit:        c4446665cb9c30056f4998ed953e6d4ff22c7c39
 runc:
  Version:          1.0.0-rc5+dev
  GitCommit:        4bb1fe4ace1a32d3676bb98f5d3b6a4e32bf6c58
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: oracle linux 7

**Comment by cpuguy83** [comment] 2020-06-22 23:30
I cannot reproduce this on Docker4Mac.

```terminal
$ docker images debian
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
debian              bullseye            71fb2e4eb29a        5 weeks ago         117MB
debian              buster              3de0e2c97e5c        2 months ago        114MB
$
```

```terminal
$ docker images debian:buster
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
debian              buster              3de0e2c97e5c        2 months ago        114MB
$
```

I see your engine version is ` 19.03.1-ol`. Where does this come from?

**Comment by TusharParasrampuria** [comment] 2020-06-23 05:46
This docker version is for oracle linux. I am using **Oracle Linux 7** as mentioned.
Which version you tried it on?? Because it is working fine on docker `17.06.1-ol` but not on docker `19.03.1-ol` for oracle linux.

**Comment by thaJeztah** [comment] 2020-06-23 13:53
Wondered if it was a bug in 19.03.1 (which is a very old version of 19.03.x), but not able to reproduce this on the official docker 19.03.1 cli;

```bash
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker:19.03.1 sh -c 'docker images foo'
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
foo                 latest              281654ed41c4        5 days ago          26.2MB
```

The oracle linux Docker package is a fork of the official codebase with various modifications/patches that are not upstream, and not something we maintain (or support); I suggest opening a support ticket with Oracle.

I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-23 13:53 UTC
