### ISSUE TITLE
docker uses /root/.docker/config.json instead of $HOME/.docker/config.json under sudo

### ISSUE THREAD

**Issue by duanqn** [docker/cli#2873] opened 2020-12-08 09:39 UTC
**Description**

I interact with several docker commands (`docker login`, `docker pull`, `docker push`) in my daily usage. The online document of `docker login` says docker stores the credential (un-encrypted) in $HOME/.docker/config.json . However, I noticed that my `docker` client always uses /root/.docker/config.json.

I am running these docker commands with `sudo`. The behaviour is different for some other people -- their credentials are stored in their $HOME/.docker even if they use `sudo`.

**Steps to reproduce the issue:**
1. `sudo apt-get install docker-ce` (which should install docker 19.03.14 on Ubuntu 20.04)
2. `sudo docker login www.example.com`
3. Note that the credential is stored in /root/.docker/config.json (instead of ~/.docker/config.json).
4. Run `sudo mv /root/.docker/config.json ~/.docker/config.json` to manually move the config to $HOME/.docker
5. `sudo docker push www.example.com/my/docker/repo:my-tag` now throws an authentication failure.

**Describe the results you received:**
See above

**Describe the results you expected:**
I expect docker to use $HOME/.docker/config.json even under `sudo`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-1032-azure
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.36GiB
 Name: ********  (<-- I erased this)
 ID: RYVG:BRU7:ENQ3:SYLC:Y3UJ:7XVP:VPXC:2DNE:YGQP:W3W6:3NXV:IGGW
 Docker Root Dir: /disks/data/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 20.04 on Azure VM

**Comment by duanqn** [comment] 2020-12-08 09:46
(Obviously) I am not root and my $HOME is not /root

**Comment by tlex** [comment] 2020-12-09 06:46
Unless you use `sudo -E` to preserve environment variables, this is the expected behavior:
```
$ sudo bash -c 'echo $HOME'
/root
$ sudo -E bash -c 'echo $HOME'
/home/tlex
```

**Comment by duanqn** [comment] 2020-12-09 07:41
@tlex I understand your example, but everyone around me is getting the same, consistent behaviour -- their credentials are stored in $HOME/.docker/config.json. Given this I think my case is exceptional.

Does your `docker` use /root/.docker/config.json too?

**Comment by tlex** [comment] 2020-12-09 09:24
I, for one, added my user to the `docker` group and don't need to use `sudo`. But, what I am saying is: this behavior doesn't seem to be something related to docker, but to the way the `$HOME` variable is set by your shell.

**Comment by thaJeztah** [comment] 2020-12-09 13:10
Yes, this is expected when using `sudo`, as others mentioned above, by default, `sudo` will not preserve your current environment variables (and, depending on the setup) also not inherit `PATH`.

You can add the user to the `docker` group to grant it access to the docker socket (but be aware that having access to the Docker API is equivalent to having `root` access on the host where the docker daemon runs);

see [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) in the documentation.

Let me close this ticket, because it's not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-12-09 13:10 UTC
