### ISSUE TITLE
docker purge removes intermediate build images

### ISSUE THREAD

**Issue by aigarius** [docker/cli#2248] opened 2020-01-09 11:29 UTC
**Description**

Docker purge command is commonly used to occasionally remove old, unreferenced images from the local filesystem. However, whenever it is used, the next builds start from scratch.

**Steps to reproduce the issue:**
1. Run "docker build -t somename ."
2. Run "docker purge"
3. Run same "docker build -t somename ." again

**Describe the results you received:**

Docker build in step 3 runs all steps without the benefit of cached results from step 1.

**Describe the results you expected:**

I would expect the intermediate build containers created during step 1 to be still linked to the resulting tagged image and thus not be purged by "docker purge" so that the repeated build in step 3 should complete instantly, just like if the step 2 was not run.

**Comment by cpuguy83** [comment] 2020-01-23 03:35
There is no linking between images, they are totally independent.
Wouldn't the purpose of running prune like this be to specifically clean up unused things like cache data?

If you use buildkit instead of the classic builder there are finer grained controls for managing build cache. I would recommend using that instead.

**Comment by aigarius** [comment] 2020-01-23 08:55
I would expect there to be a linking and default prune not removing intermediate images that lead to images that are currently tagged. Aren't intermediates still in the layer stack of the final image? Once I build a new image and a particular intermediate is no longer in the cache chain, then I would expect it to be pruned. There might be a separate option like "prune intermediate" to be used in production environments where building new images is not expected, but by default prune should not have any negative performance effects.

**Comment by cpuguy83** [comment] 2020-01-23 14:34
There is no linking between images. Images can reference the same layers, but an image itself is self-contained.
I would recommend you give the buildkit builder a try.
You can do this by setting "DOCKER_BUILDKIT=1" when invoking the build command.

**Comment by cpuguy83** [comment] 2020-02-10 23:22
I'm going to close this since it is working as intended.
Image layers as a build cache as a build cache was never a great idea due to this exact reason.
Buildkit, which is the next gen builder resolves this by handling caching separate from the image store.

**Closed by cpuguy83** 2020-02-10 23:22 UTC
Labels: area/builder
