### ISSUE TITLE
permission denied on mounting volume with active user isolation

### ISSUE THREAD

**Issue by Joerg-L** [docker/cli#3406] opened 2022-01-14 10:55 UTC
**Description**
We have enabled the user isolation on the daemon by configuring the daemon.json like following
```
{
"insecure-registries":[ "..."
  ],
"registry-mirrors": ["..."],
"userns-remap": "bamboo"
}
```
restart of docker daemon were executed.
The linux user exists
```
# id
uid=1024(bamboo) gid=1024(bamboo) groups=1024(bamboo),10(wheel),992(docker)
```
Also SUB-IDs are there
/etc/subgid -> bamboo:165536:65536
/etc/subuid -> bamboo:165536:65536

on /var/lib/docker/ we see also
`drwx--x--- 13 root 165536  167 Jan 14 11:43 165536.165536`

`docker run hello-world` works fine.

I have created in the user home folder a subfolder "test" and trys to mount it into a container.
`docker run --rm -it -v "$(pwd)/test:/test/" -it busybox`

the error I receive is
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/bamboo/test" to rootfs at "/test" caused: stat /home/bamboo/test: permission denied: unknown`

**Additional environment details**
Virtual Machine with CentOs 7.7
Client: Docker Engine - Community
 Version:           20.10.8
Server: Docker Engine - Community
 Engine:
  Version:          20.10.12

**Comment by thaJeztah** [comment] 2022-01-18 09:08
Thanks for opening this ticket.

So, effectively, this is what user-namespaces are meant to do; prevent a container process from making changes on the host in the event the container manages to get access to file paths outside of its sandbox (the container filesystem). 

When running containers with user-namespaces, users "inside" the container (which may be `root` inside the container) correspond to non-privileged users on the host. To allow the non-privileged user to have access to files on the host, those files / directories need to have their ownership/permissions set correspondingly to grant the container access.


A slightly more in-depth conversation about this can be found in https://github.com/moby/moby/issues/42134, and issues linked from that ticket.


Let me close this ticket as a duplicate of https://github.com/moby/moby/issues/42134, but feel free to continue the conversation.

**Closed by thaJeztah** 2022-01-18 09:08 UTC
