### ISSUE TITLE
docker devicemapper full

### ISSUE THREAD

**Issue by razvdana** [docker/cli#2495] opened 2020-05-05 12:02 UTC
Can someone please explain why my devicemapper has almost no available data space left ? It is a k8s node and I cannot deploy any further pods on it because it runs out of storage space. 

Results of du -sh /var/lib/docker:
`15G	/var/lib/docker`

Results of docker system df:
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              4                   4                   276.8MB             4.023MB (1%)
Containers          5                   5                   0B                  0B
Local Volumes       0                   0                   0B                  0B
Build Cache         0                   0                   0B                  0B

Results of docker info:
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.06.2-ce
Storage Driver: devicemapper
 Pool Name: docker-253:1-34025556-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 390.6MB
 Data Space Total: 107.4GB
 Data Space Available: 3.965GB
 Metadata Space Used: 17.9MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.13GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.149-RHEL7 (2018-07-20)
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.21.3.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.92GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

RHEL version 7.6

The few things I know about the devicemapper is that it creates virtual blocks of data for each container/image/volume right ? Once a container is removed and the volumes are unmounted shouldn't the space be reclaimed ? It appears it isn't happening here. The output is after a system prune by the way. Any insight could be helpful as to how can I fix the issue without a clean docker install (if possible) and how to make sure this doesn't happen again in the future.

Thanks

**Comment by thaJeztah** [comment] 2020-05-28 16:50
I think it may be restricted by

```
Base Device Size: 10.74GB
```

More details about the device mapper storage driver can be found in https://docs.docker.com/storage/storagedriver/device-mapper-driver/

That said; I notice that

- you're running device mapper in `loop-lvm` mode, which severely impacts performance, and can have limitations with cleaning up resources, and therefore not really suitable for production us (instead, `direct-lvm` is recommended, but requires preparations; https://docs.docker.com/storage/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production)
- you're running Docker 18.06  which reached EOL two years ago
- overall, the device mapper driver has been deprecated (but not yet removed), in favour of the default `overlay2` storage driver, which is supported on current versions of the RHEL/CentOS kernel, provides better performance, and doesn't require setup.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-05-28 16:50 UTC
