### ISSUE TITLE
docker history expose build arg

### ISSUE THREAD

**Issue by andreacassioli** [docker/cli#2473] opened 2020-04-28 20:14 UTC
Hi Team, 
I am not sure whether this is a bug or can be seen as a feature request. It is an issue for sure and it seems to be widely documented on the Internet.

Here it is:

* build a docker image that requires some build arguments
* the build arguments are accessible in clear running `docker history` on the freshly build image.

For instance
```
FROM alpine as build

ARG myarg

RUN apk update

FROM build as middle

RUN echo "Hello!"
# -- 
FROM python:3-slim as final
RUN apt-get update

CMD python3 -v
```

Build the three targets:
```
$ docker build --build-arg myarg=zzz -t test-final .
$ docker build --build-arg myarg=zzz -t test-middle --target middle  .
$ docker build --build-arg myarg=zzz  -t test-build --target build  . 
```

And run history on the build image you get the following (extract..);

```
22:09 $ docker history test-build:latest 
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
223523d31bf0        24 hours ago        |1 myarg=zzz /bin/sh -c apk update              1.58MB              
```

While on the other image the args are not exposed.

I can see that args are converted in env vars while executing `RUN`, and that is why their values are printed in clear I guess.

Would it be possible to obscure that argument when printing the history? Or maybe you could create and source a temporary file instead of relying on variable list.

Cheers,
Andrea

**Comment by cpuguy83** [comment] 2020-04-28 21:42
> While on the other image the args are not exposed.

Not sure what this means. Can you explain?

---

This is working as intended and was a conscious decision to not obscure args.
If you are looking to inject secrets into a build then please use buildkit which has support for secrets. https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information

**Comment by andreacassioli** [comment] 2020-04-29 14:42
I mean that if I inspect the history of the `test-middle` and `test-final` images, the args are not exposed.

**Comment by cpuguy83** [comment] 2020-04-29 14:56
Also yes this is expected since the `ARG` is not exposed in the final build.

**Comment by andreacassioli** [comment] 2020-04-29 19:24
@cpuguy83 well then it's the way it is. I guess I just don't see the use case of exposing the build arguments as part of history. 

I see how secret works, pretty much like a similar concept in kubernetes, but it quite overkilling in this case. And it seems still in a preview state. I would have liked a maybe a `SECRET` keyword that works like `ARG` but it obscure the value in the history.

And btw, there is no mention about `ARG` being exposed by `history` in the official documentation https://docs.docker.com/engine/reference/commandline/history/#examples

**Comment by thaJeztah** [comment] 2020-04-29 20:31
> I guess I just don't see the use case of exposing the build arguments as part of history.

Part of that information is used as cache-key for the build-cache; even if obscured, the key used must have a relation with the value that was passed, which would give a false sense of security.

While buildkit is not yet the _default_ builder, it can definitely be used as a default; the main reason for it not being the default yet is that there's some functionality missing around debugging failed builds (which is more difficult with buildkit), and no support yet for builds for Windows images.

If you cannot use buildkit/secrets, but are building on trusted nodes, you _can_ use build-args in intermediate stages as long as those stages are not pushed to a registry (as, as you outlined, the final stage does not show the history of intermediate stages if they're not in the "parent" chain)

> And btw, there is no mention about ARG being exposed by history in the official documentation

It's called out in the documentation for  `ARG`; https://docs.docker.com/engine/reference/builder/#arg

> **Warning:**
>
> It is not recommended to use build-time variables for passing secrets like
> github keys, user credentials etc. Build-time variable values are visible to
> any user of the image with the `docker history` command.
> 
> Refer to the ["build images with BuildKit"](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information)
> section to learn about secure ways to use secrets when building images.


I'm a bit in doubt if it would make sense to describe it in the `history` documentation 🤔

**Comment by thaJeztah** [comment] 2020-06-05 15:03
closing this for now

**Closed by thaJeztah** 2020-06-05 15:03 UTC

**Comment by malthe** [comment] 2020-12-01 07:39
> Part of that information is used as cache-key for the build-cache; even if obscured, the key used must have a relation with the value that was passed, which would give a false sense of security.

Why not just cryptographically hash the build arguments? That's not providing a false sense of security then – it provides actual security.

When I'm inspecting the build history, I see that build arguments are prepended to the command string. It would seem that those environment variables could be made available in a way that wouldn't expose them directly.
