### ISSUE TITLE
How to create a IPV6/IPV4 macvlan?

### ISSUE THREAD

**Issue by SoraKasvgano** [docker/cli#3143] opened 2021-06-17 02:31 UTC
hi everyone, i want to use a openwrt docker image on my rpi as my sencondary router......

it needs a macvlan network....

i view examples from official doc is 

docker network  create  -d macvlan \
    --subnet=192.168.216.0/24 \
    --gateway=192.168.216.1 \
    --subnet=2001:db8:abc8::/64 --gateway=2001:db8:abc8::10 \
     -o parent=eth0.218 \
     -o macvlan_mode=bridge macvlan216

but my IPV6 is dynamic offered by ASUS router IPV6 native method,like 240e:345:c1b:a101::/56      it will changed when i restart router.....240e:345:c1b:a201::/56   240e:345:c11:a000::/56
so how to create a macvlan with both IPV4 and IPV6?

**Comment by thaJeztah** [comment] 2021-06-23 16:46
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/docker/cli/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the [Docker community Slack channel](http://dockr.ly/slack)
- the Docker Support Forums - https://forums.docker.com

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-06-23 16:46 UTC
Labels: area/networking, kind/question
