### ISSUE TITLE
/.dockerenv is not cleaned up

### ISSUE THREAD

**Issue by dkjii-g** [docker/cli#3037] opened 2021-04-02 00:23 UTC
**Description**

/.dockerenv is not removed on docker export

**Steps to reproduce the issue:**
1. docker create busybox
2. docker export 7dcad6d6bbce2b8b6796295b4d2cd0b4a2b84eb7c6e0f35c8e91466f7cd1794d -o export.tar

**Describe the results you received:**

tar -xf export.tar && stat .dockerenv

.dockerenv exists

**Describe the results you expected:**

.dockerenv doesn't exist

**Additional information you deem important (e.g. issue happens only occasionally):**

Some software (such as systemd and openrc) use /.dockerenv to figure out if running inside a container. This means that exporting an image and using it in a VM or real machine will not function properly. /.dockerenv should be cleaned up either on shutdown or on export.

The issue remains if you remove the dockerenv, import and export again.

**Output of `docker version`:**

```
Client:
 Version:           20.10.0-dev
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        55c4c88966
 Built:             Mon Mar 29 15:01:37 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       363e9a88a1
  Built:            Mon Mar 29 15:03:57 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        fec3683b971d9c3ef73f284f176672c44b448662
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: tmpfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: de40ad007797e0dcd8b7126f27bb87401d224240)
 Security Options:
  seccomp
   Profile: default
  userns
 Kernel Version: 5.4.97-gentoo
 Operating System: Gentoo/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 11.43GiB
 Name: dev
 ID: RFHR:HTEI:YMR3:2VIS:X7UD:DXMD:DP5U:GFQ2:2XTF:SHYI:WXT4:GUMC
 Docker Root Dir: /var/lib/docker/1000.1000
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

related bug: https://github.com/OpenRC/openrc/issues/416

**Comment by villelaitila** [comment] 2021-06-08 19:35
Isn't .dockerenv just a regular file, and it is just a convention, cannot be trusted. I think export should also have it, or how you can otherwise use export to check if the image really has .dockernv file or not?

**Comment by thaJeztah** [comment] 2021-06-16 13:01
Yes, I would consider this the expected behavior. `docker export` is meant to export a _container_ filesystem. While (perhaps) `.dockerenv` should've been considered a "special" file (and (e.g.)) mounted inside the container instead of copied, it is not, and changing it would quite likely break users.

```
docker export --help

Usage:  docker export [OPTIONS] CONTAINER

Export a container's filesystem as a tar archive
```

If your intent is to save the container's _image_ to a file, `docker save` / `docker image save` is a better option;

```
Usage:  docker save [OPTIONS] IMAGE [IMAGE...]

Save one or more images to a tar archive (streamed to STDOUT by default)

Options:
  -o, --output string   Write to a file, instead of STDOUT
```


I'm closing this issue because of the above, but feel free to continue the conversation

**Closed by thaJeztah** 2021-06-16 13:01 UTC
