### ISSUE TITLE
Long running exporting layers step when using 'usermod' in Dockerfile with large UID

### ISSUE THREAD

**Issue by pbcromer** [docker/cli#3559] opened 2022-04-14 18:56 UTC
**Description**

When using usermod in a Dockerfile I sometimes run into long build times in the "exporting layers" step and an image with a much larger size than expected. Only happens with some UIDs.

**Steps to reproduce the issue:**
1. Create a Dockerfile
```
FROM ubuntu:20.04
RUN useradd -U dev
RUN usermod -u 1168123471 dev
```
2. Build the image
```
docker build -f Dockerfile -t bugbase .
```

**Describe the results you received:**
The image builds fast, but when exporting the layers for the image it can take a very long time and result in a very large image:
```
[+] Building 172.1s (6/7)                                                                                                                                      
 => [internal] load build definition from Dockerfile.base                                                                                                 0.0s
[+] Building 172.3s (6/7)                                                                                                                                      
[+] Building 174.2s (6/7)                                                                                                                                      
[+] Building 174.4s (6/7)                                                                                                                                      
[+] Building 174.7s (6/7)                                                                                                                                      
 => [internal] load build definition from Dockerfile.base                                                                                                 0.0s
 => => transferring dockerfile: 115B                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                          17.1s
 => [1/3] FROM docker.io/library/ubuntu:20.04@sha256:9101220a875cee98b016668342c489ff0674f247f6ca20dfc91b91c0f28581ae                                     3.2s
 => => resolve docker.io/library/ubuntu:20.04@sha256:9101220a875cee98b016668342c489ff0674f247f6ca20dfc91b91c0f28581ae                                     0.0s
 => => sha256:825d55fb6340083b06e69e02e823a02918f3ffb575ed2a87026d4645a7fd9e1b 1.46kB / 1.46kB                                                            0.0s
 => => sha256:9101220a875cee98b016668342c489ff0674f247f6ca20dfc91b91c0f28581ae 1.42kB / 1.42kB                                                            0.0s
 => => sha256:31cd7bbfd36421dfd338bceb36d803b3663c1bfa87dfe6af7ba764b5bf34de05 529B / 529B                                                                0.0s
 => => sha256:e0b25ef516347a097d75f8aea6bc0f42a4e8e70b057e84d85098d51f96d458f9 28.57MB / 28.57MB                                                          1.5s
 => => extracting sha256:e0b25ef516347a097d75f8aea6bc0f42a4e8e70b057e84d85098d51f96d458f9                                                                 1.6s
 => [2/3] RUN useradd -U dev                                                                                                                              0.6s
 => [3/3] RUN usermod -u 1168123471 dev                                                                                                                   0.6s
 => exporting to image                                                                                                                                  156.3s
 => => exporting layers                                                                                                                                 156.3s
^CERRO[0175] got 3 SIGTERM/SIGINTs, forcing shutdown      
```

**Describe the results you expected:**
If I use a smaller UID, like 5678, the build finishes immediately and the image size is normal.

**Additional information you deem important (e.g. issue happens only occasionally):**
I thought it might be an issue with a UID larger than 16 bits, but at work I have a more complicated example using a UID of 1168 that had the same issue. The test example above seems to handle 1168 fine.

I ended up not needing the solution that led to this issue, but I'm trying to understand what I'm doing wrong or if there's a bug in docker.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:48 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 18
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.18GiB
 Name: docker-desktop
 ID: LLVK:ARO6:5QRF:NGS3:3A3D:MLRV:NP25:XC2M:THHK:TDJJ:4PNN:A2UA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I can run the commands from the Dockerfile in a vanilla Ubuntu 20.04 container without error or issue. I've produced the error on a Linux desktop running docker 20.10.7 at work and my home laptop running Windows and docker 20.10.12 at home.

**Comment by thaJeztah** [comment] 2022-04-14 22:50
thanks for reporting; this looks to be a duplicate of https://github.com/moby/moby/issues/5419 (which has more details on why this happens)

To address this, use the `-l` option on `useradd` (but more details in the ticket I linked)

I'll close this ticket as a duplicate of the above, but feel free to participate in the discussion there.

**Closed by thaJeztah** 2022-04-14 22:50 UTC
