### ISSUE TITLE
Docker Content Trust on base image when `docker build`

### ISSUE THREAD

**Issue by brianluong** [docker/cli#3367] opened 2021-11-23 00:36 UTC
**Description**
When I enabled Docker Content Trust, I expect my base image (`FROM .....`) to be validated for integrity when running `docker build`.

**Steps to reproduce the issue:**
1.  `export DOCKER_CONTENT_TRUST=1 `
2. 
``` 
➜ ~ ✗ docker pull registry-app.net:5001/imported/alpine:3.13
Error: remote trust data does not exist for registry-app.net:5001/imported/alpine: registry-app.net:5001 does not have trust data for registry-app.net:5001/imported/alpine
```
3.
```
 ➜   ✗ docker build -f minimal-image.Dockerfile .
...
 => [internal] load metadata for registry-app.eng.qops.net:5001/imported/alpine:3.13                                                                                                                
 => [1/1] FROM registry-app.eng.qops.net:5001/imported/alpine:3.13@sha256:094aa7e2e1f2dc4298d4688e0105abdd570734c4d87538a8da8cfd225ba40051                                                            0.0s
 => => resolve registry-app.eng.qops.net:5001/imported/alpine:3.13@sha256:094aa7e2e1f2dc4298d4688e0105abdd570734c4d87538a8da8cfd225ba40051                                                            0.0s
 => => sha256:094aa7e2e1f2dc4298d4688e0105abdd570734c4d87538a8da8cfd225ba40051 528B / 528B                                                                                                            ...               
...
# success
```

**Describe the results you received:**
Build succeeded when I expected it to fail when pulling the base image.

**Additional environment details (AWS, VirtualBox, physical, etc.):** Docker Desktop for Mac

**Comment by dyihoon90** [comment] 2022-02-25 02:10
our team is running into a similar issue as well, docker pull fails as expected, but docker build succeeds, which we do no expect.

**Comment by thaJeztah** [comment] 2022-03-04 15:24
Thanks for reporting; this looks to be a duplicate of https://github.com/docker/cli/issues/3217. Let me close this one.

I'll probably move that ticket to the https://github.com/docker/buildx repository though, as that's where the build client is maintained 🤔

**Closed by thaJeztah** 2022-03-04 15:24 UTC
Labels: area/builder, area/trust, area/builder/buildkit
