### ISSUE TITLE
stack deploy with multiple compose files: Cannot override to replicas: 0

### ISSUE THREAD

**Issue by mspiess** [docker/cli#3810] opened 2022-10-11 18:07 UTC
### Description

It is not possible to override `service.deploy.replicas` to `replicas: 0` with a second compose file.
With numbers larger than 0 it works as expected.

### Reproduce

Given the following compose files:
`docker-compose.yml`:
```docker-compose
services:
  nginx:
    image: nginx
    deploy:
      replicas: 3
```

`docker-compose.override.yml`:
```docker-compose
services:
  nginx:
    image: nginx
    deploy:
      replicas: 0
```

Deployed with:
```shell
docker stack deploy -c docker-compose.yml -c docker-compose.override.yml lb
```

Then the command `docker service ls` shows replicas `X/3`.

### Expected behavior

`docker service ls` shows replicas `0/0`.

### docker version

```bash
Client:
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.19.1
 Git commit:        b40c2f6b5d
 Built:             Sat Sep 10 11:31:10 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Comment by thaJeztah** [comment] 2022-10-11 18:56
Thanks for reporting; this looks like a duplicate of https://github.com/docker/cli/issues/3293

Let me close this one 👍

**Closed by thaJeztah** 2022-10-11 18:56 UTC
Labels: kind/bug, status/0-triage
