### ISSUE TITLE
`docker run` `--add-host` option is not parsed if not passed as the first option

### ISSUE THREAD

**Issue by RomanDavlyatshin** [docker/cli#3718] opened 2022-07-25 11:32 UTC
**Description**

`docker run` command execution seems to depend on order of options passed, which does not seem right
particulary, `--add-host` is not parsed, if placed after flags/options from the steps below:

**Steps to reproduce the issue:**
1. Run `docker run -d --name selenoid-ui -p 8081:8080 aerokube/selenoid-ui --selenoid-uri http://my.awesome.network:4444 --add-host=my.awesome.network:host-gateway`
2. Check the logs of the created container

**Describe the results you received:**
The --add-host was not parsed with the respective error present in the log
```
$ docker logs 26ae
flag provided but not defined: -add-host
```

**Describe the results you expected:**
The --add-host must be parsed and service must launch
```
$ docker logs 8c1 # ignore the different container id, it was recreated with "correct" order of options
2022/07/25 11:25:16 [INIT] [Listening on :8080]
```

**Additional information you deem important (e.g. issue happens only occasionally):**
`--add-host` options works if I pass it as the first option
`docker run --add-host=my.awesome.network:host-gateway -d --name selenoid-ui -p 8081:8080 aerokube/selenoid-ui --selenoid-uri http://my.awesome.network:4444`

**Output of `docker version`:**

```
$ docker --version
Docker version 20.10.13, build a224086
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 10
  Running: 1
  Paused: 0
  Stopped: 9
 Images: 57
 Server Version: 20.10.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 25GiB
 Name: docker-desktop
 ID: PJPL:Z3EI:2OKO:REZG:O3TB:AEBB:E7OS:XMBM:EJ43:VGN7:PAJ3:H6GI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: Windows 10 20H2 build 19042.1706

**Comment by thaJeztah** [comment] 2022-07-25 15:26
Thanks for reporting; this is the expected behavior.

When running  container, the _docker_ options must always be passed _before_ the image name (see the `[OPTIONS]` in the `--help` output;


```bash
docker run --help

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```

Anything _after_ the image name is used as command and/or options for the command running _inside_ the container, so in your case, ` --add-host=my.awesome.network:host-gateway` is passed as flag to the command running inside the `aerokube/selenoid-ui` image.


I'm closing this ticket, because this doesn't appear to be a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2022-07-25 15:26 UTC

**Comment by RomanDavlyatshin** [comment] 2022-07-25 16:23
Sounds reasonable. I think it would be helpful to clear that up in the documentation of run command just to make it obvious.
E.g. to quote your response 
> When running container, the _docker_ options must always be passed _before_ the image name (see the `[OPTIONS]` in the `--help` output;

in the [description](https://docs.docker.com/engine/reference/commandline/run/#description)
