### ISSUE TITLE
dockerd: failed to start  daemon: Devices cgroup isn't mounted

### ISSUE THREAD

**Issue by lyndalopez544** [docker/cli#2104] opened 2019-09-24 16:52 UTC
**Description**

The problematic part of <code>dockerd</code>'s output:
<pre><code> 
WARN[2019-09-24T16:38:43.968826308Z] Your kernel does not support cgroup memory limit 
WARN[2019-09-24T16:38:43.968902465Z] Unable to find cpu cgroup in mounts          
WARN[2019-09-24T16:38:43.968935049Z] Unable to find blkio cgroup in mounts        
WARN[2019-09-24T16:38:43.969017890Z] Unable to find cpuset cgroup in mounts       
WARN[2019-09-24T16:38:43.969031008Z] mountpoint for pids not found                
failed to start daemon: Devices cgroup isn't mounted
</code></pre>

Output of <code>cgroupfs-mount</code>:
<pre>
mount: /sys/fs/cgroup/cpu: cgroup already mounted on /sys/fs/cgroup/cpuset.
mount: /sys/fs/cgroup/blkio: cgroup already mounted on /sys/fs/cgroup/cpuset.
mount: /sys/fs/cgroup/memory: cgroup already mounted on /sys/fs/cgroup/cpuset.
mount: /sys/fs/cgroup/pids: cgroup already mounted on /sys/fs/cgroup/cpuset.
</pre>

**Output of `docker version`:**
<pre>
Client: Docker Engine - Community
Version:           19.03.2
API version:       1.40
Go version:        go1.12.8
Git commit:        6a30dfc
Built:             Thu Aug 29 05:29:29 2019
OS/Arch:           linux/amd64
Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
</pre>

**Output of `docker info`:**
<pre>
Client:
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
</pre>

#### Running physically on Debian 10 with kernel 5.3.0-rc5-amd64

**Comment by Swiftyhu** [comment] 2019-09-26 13:57
I have the same issue.
However I found a workaround:

```bash
service docker stop
service containerd stop
cgroupfs-umount
cgroupfs-mount
service containerd start
service docker start
```

Sysinfo:

```bash
Linux vr 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
cgroupfs-mount ver 1.4
```
containerd --version
```
containerd containerd.io 1.2.6 894b81a4b802e4eb2a91d1ce216b8817763c29fb
```

docker version
```
Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfca03
 Built:             Thu Aug 29 05:29:49 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

**Comment by Swiftyhu** [comment] 2019-09-26 15:34
Found the "bug"...

I forgot to mention in my previous comment that I use(d) systemd version 243.
With systemd 242 works everything flawlessly... :)

From the systemd [changelog](https://github.com/systemd/systemd/blob/master/NEWS):
```
        * systemd now defaults to the "unified" cgroup hierarchy setup during
          build-time, i.e. -Ddefault-hierarchy=unified is now the build-time
          default. Previously, -Ddefault-hierarchy=hybrid was the default. This
          change reflects the fact that cgroupsv2 support has matured
          substantially in both systemd and in the kernel, and is clearly the
          way forward. Downstream production distributions might want to
          continue to use -Ddefault-hierarchy=hybrid (or even =legacy) for
          their builds as unfortunately the popular container managers have not
          caught up with the kernel API changes.
```

Sooo... Houston, we have a problem:
1. systemd will (or already did) jump on the cgroupsv2 bandwagon...
2. cgroupfs-mount tools does not work with newer systemd setups.

"Same" issue in [kubernetes](https://github.com/kubernetes/kubeadm/issues/1394)

**Comment by kj54321** [comment] 2019-10-30 13:41
Hi All,

     Seems issue still persist on latest Fedora 31, even with adding extra command __--exec-opt native.cgroupdriver=systemd__

And per [upstream workaround](https://bugzilla.redhat.com/show_bug.cgi?id=1746355), which works temporarily with cgroup v1.

    However, the question lays on how do we address/fix this issue permanently as it's kernel API related.

Thanks

**Comment by moughamir** [comment] 2019-11-14 17:07
@kj54321 
Fixed by the [workaround](https://bugzilla.redhat.com/show_bug.cgi?id=1746355#c12) suggested, just add the argument `systemd.unified_cgroup_hierarchy=0` in grub

**Comment by jnk5y** [comment] 2019-11-14 20:32
I added  the argument but it did not solve the issue on a Fedora 31 install (upgraded from Fedora 30).

Here is my boot command line /proc/cmdline
`BOOT_IMAGE=(hd0,gpt2)/vmlinuz-5.3.11-300.fc31.x86_64 root=/dev/mapper/fedora_localhost--live-root ro resume=/dev/mapper/fedora_localhost--live-swap rd.lvm.lv=fedora_localhost-live/root rd.lvm.lv=fedora_localhost-live/swap rhgb quiet systemd.unified_cgroup_hierarchy=0 `

**Comment by omercsp** [comment] 2019-11-23 12:28
@jnk5y, It **does** work for me on F31. Fresh install though. In the Redhat thread it looks like it worked for other people as well. Did you get the same error?

**Comment by nethershaw** [comment] 2019-12-03 02:44
Obviously docker just has to support cgroupsv2.

**Comment by cpuguy83** [comment] 2019-12-04 17:19
cgroups v2 support is well underway, support first has to be merged into containerd: https://github.com/containerd/containerd/pull/3799

There's also some outstanding PR's on runc it seems.

**Comment by whatboxapp** [comment] 2019-12-07 02:28
`dnf install -y grubby

grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

reboot`

**Comment by narfman0** [comment] 2019-12-10 03:54
Very old fedora install here. I:

1. Added `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"` to `/etc/default/grub`
2. Ran `grub2-mkconfig -o /boot/grub2/grub.cfg`
3. Ran `reboot`

and everything was happy

**Comment by duckinator** [comment] 2020-01-01 15:48
Running this on Fedora 31, after an in-place upgrade from Fedora 30, works:

```
sudo grubby --args='systemd.unified_cgroup_hierarchy=0' --update-kernel /boot/vmlinuz-5.3.16-300.fc31.x86_64
```

See [a specific comment on the Fedora 31 bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1746355#c1) and [the Fedora 31 documentation on using grubby](https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/kernel-module-driver-configuration/Working_with_the_GRUB_2_Boot_Loader/#sec-Making_Persistent_Changes_to_a_GRUB_2_Menu_Using_the_grubby_Tool).

**Comment by arkaitzmugicaislas** [comment] 2020-01-23 21:34
I can't make it work in Fedora 31 Silverblue. I've tried everything to install and config moby-engine. Terminal copy-paste:
docker run hello-world
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.

**Comment by arkaitzmugicaislas** [comment] 2020-01-23 22:27
ok... I've made it run... 
The problem was on the way rpm-ostree works and how to change user groups.
grep -E '^docker:' /usr/lib/group >> /etc/group
and then
usermod -aG docker username
just that :-)

**Comment by RASPWeather** [comment] 2020-02-09 16:34
Following also worked ...

dnf install -y grubby

grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

reboot

**Comment by jboero** [comment] 2020-02-20 11:43
This has been making my Fedora 30->31 upgrades ugly.  Of course Podman works in anti-competitive efforts to push out Docker.  A system-wide kernel boot option shouldn't be required for backwards compatibility with a container engine.  Hmmm

**Comment by jjspace** [comment] 2020-03-23 23:28
@cpuguy83 any update on this? I just ran into the issue on a new install of Fedora 31. Thankfully the workaround mentioned above worked for me. However I noticed that containerd PR was merged so I wanted to check on the progress from Docker's side.

**Comment by cpuguy83** [comment] 2020-03-23 23:48
@jjspace This will not be supported until containerd 1.4 is released. I think we have all the bits we need in dockerd for this right now, but again this depends on containerd 1.4. There are also some outstanding pieces in runc.

We are currently planning the next major release of Docker ("20.03" is the placeholder version). I do not think we will be shipping that with containerd 1.4 since that is not ready yet.... but in theory one containerd 1.4 is out once that's upgraded (along with runc) it should work.

**Comment by Conan-Kudo** [comment] 2020-03-24 01:05
> This has been making my Fedora 30->31 upgrades ugly. Of course Podman works in anti-competitive efforts to push out Docker. A system-wide kernel boot option shouldn't be required for backwards compatibility with a container engine. Hmmm

Seriously? The issue is that Docker has no support for cgroup v2, which is a feature *all* Linux distributions have had for at least _five years_. The fact it's now finally being adopted is pushing everyone to add support for it.

**Comment by cpuguy83** [comment] 2020-03-24 16:48
None of these comments are helpful.
This is a community effort.
Please keep politics out of it.

**Comment by JiangHongTiao** [comment] 2020-04-04 07:23
Is there any update on this? Will it work for upcoming fedora 32 release out of the box?

**Comment by cpuguy83** [comment] 2020-04-04 13:40
I gave an update 12 days ago.

Will it work OOTB on Fedora 32? Not unless Fedora switches back to cgroups v1. 

Support for cgroups v2 in Docker is still being worked on across the stack.

**Comment by ablil** [comment] 2020-06-30 09:27
I've been struggling with this problem myself on fedora 31 for a long time.
I thing you should look at the official website [Fedora project](https://fedoramagazine.org/docker-and-fedora-32/)

The solution suggested by @RASPWeather  worked for me.

**Comment by Rgf11111** [comment] 2020-07-23 03:23
I got another solution.
System is CentOS 6.5.
I installed libcgroup service and started it,docker worked fine.
Detail at [https://www.digitalocean.com/community/tutorials/how-to-limit-resources-using-cgroups-on-centos-6](https://www.digitalocean.com/community/tutorials/how-to-limit-resources-using-cgroups-on-centos-6)

**Comment by True-ps** [comment] 2021-02-22 16:15
> I have the same issue.
> However I found a workaround:
> 
> ```shell
> service docker stop
> service containerd stop
> cgroupfs-umount
> cgroupfs-mount
> service containerd start
> service docker start
> ```
> 
> Sysinfo:
> 
> ```shell
> Linux vr 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
> cgroupfs-mount ver 1.4
> ```
> 
> containerd --version
> 
> ```
> containerd containerd.io 1.2.6 894b81a4b802e4eb2a91d1ce216b8817763c29fb
> ```
> 
> docker version
> 
> ```
> Client: Docker Engine - Community
>  Version:           19.03.2
>  API version:       1.40
>  Go version:        go1.12.8
>  Git commit:        6a30dfca03
>  Built:             Thu Aug 29 05:29:49 2019
>  OS/Arch:           linux/amd64
>  Experimental:      false
> ```

Thanks. That did the trick for me.

**Comment by rajspatel1297** [comment] 2021-07-09 17:19
I'm getting an error in the installation. Here is a complete output. 
`Setting up docker-ce (5:20.10.7~3-0~debian-buster) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2021-07-09 17:16:20 UTC; 42ms ago
     Docs: https://docs.docker.com
  Process: 15953 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 15953 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
I'm using Debian 10 (buster) on armh platform. 

Thanks in advance!

**Comment by curtisgray** [comment] 2021-07-10 17:26
@rajspatel1297, I used the [workaround](https://github.com/docker/cli/issues/2104#issuecomment-535513985) suggested by @Swiftyhu. I suspect this workaround will become obsolete at some point.

**Comment by thenewmantis** [comment] 2022-03-12 03:47
Don't know how helpful this will be to anyone else, but I solved the same problem by recompiling my kernel. Run contrib/check_config.sh (in the source code) to check if your kernel supports what Docker needs, recompile accordingly.

**Comment by ndeloof** [comment] 2022-03-14 08:04
@thaJeztah shall we close this issue? Should be owned by https://github.com/moby/moby anyway

**Closed by ndeloof** 2022-03-14 08:04 UTC

**Comment by phisad** [comment] 2023-06-14 08:57
Came here after an update from Ubuntu 20.04 to 22.04. The workaround from [Swiftyhu](https://github.com/Swiftyhu) helped to start the deamon. Thanks!
```
cgroupfs-umount
cgroupfs-mount
service containerd start
service docker start
```

**Comment by perlun** [comment] 2023-09-01 07:46
Based on https://github.com/docker/cli/issues/2104#issuecomment-563722141, the following worked for me on Ubuntu 22.04 as well (trying to run Docker-in-Docker with an old Docker 18.09.9 version).

* Edited `GRUB_CMDLINE_LINUX` to be `systemd.unified_cgroup_hierarchy=0` in `/etc/default/grub`
* Ran `sudo grub-mkconfig -o /boot/grub/grub.cfg`
* Ran `sudo reboot`
