### ISSUE TITLE
command-line completion does not recognize `-it`

### ISSUE THREAD

**Issue by hussam-qasem** [docker/cli#3359] opened 2021-11-08 07:53 UTC
[Docker CLI completion](https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker) doesn't auto-complete and show the running container names when used with `-it` option
```
docker exec -it [TAB]
```

I have to specify `-i` and `-t` separately:
```
docker exec -i -t [TAB]
```
**Steps to reproduce the issue:**
1. Using `zsh` shipped with MacOS
2. `sudo mkdir -p /usr/local/share/zsh/site-functions/`
3. `sudo ln -s /Applications/Docker.app/Contents/Resources/etc/docker.zsh-completion /usr/local/share/zsh/site-functions/_docker`
4. Restart `zsh`
5. Run:
```
docker exec -it [TAB]
```

**Describe the results you received:**
Nothing happens, as if it doesn't recognize the `-it` option.

**Describe the results you expected:**
Name of running containers would appear, similar to typing:
`docker exec -i -t [TAB]`

**`docker version`:**
```
v20.10.8
```

**Comment by thaJeztah** [comment] 2021-11-10 14:09
This looks to be a duplicate of https://github.com/docker/cli/issues/993

You need to enable "short options stacking" make completion work for combinations of short options; see https://github.com/docker/cli/blob/64b2e952875788b0162b821dc4fe51e6947f9136/contrib/completion/zsh/_docker#L42-L49

The original intent was to enable this by default, but unfortunately, doing so caused various issues (see the discussion on https://github.com/moby/moby/pull/17124), so for that reason, it was disabled by default.

Let me close this ticket, as it's a duplicate of https://github.com/docker/cli/issues/993

**Closed by thaJeztah** 2021-11-10 14:09 UTC
Labels: area/completion
