### ISSUE TITLE
"Entrypoint":/sbin/init, Cmd": [ "/home/dbc_utils/dbc_task.sh"]  Causes the bash command to fail

### ISSUE THREAD

**Issue by deepbraindeveloper** [docker/cli#2643] opened 2020-07-22 06:33 UTC
I wanted to be able to execute systemctl inside the container, so Entrypoint added /sbin/init, but this prevented the CMD entry bash command from executing。

```json
{
    "Hostname": "",
    "user": "",
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "Image": "www.dbctalk.ai:5000/dbc-ai-training:v3.1.2",
    "NetworkDisabled": false,
    "WorkingDir": "",
    "Domainname": "",
    "PortSpecs": [],
    "Env": [
        "NVIDIA_DRIVER_CAPABILITIES=compute,utility",
        "NVIDIA_VISIBLE_DEVICES=0"
    ],
    "Cmd": [
        "/home/dbc_utils/dbc_task.sh",
        "",
        "QmW7xeDshhbJFMiQ1WgtnimUJTd3j3JdfyQdtbdoz9mS6n",
        "run.sh "
    ],
    "Dns": [],
    "Entrypoint": [“/sbin/init”],
    "OnBuild": [],
    "Volumes": {},
    "ExposedPorts": {
        "22/tcp": {},
        "8888/tcp": {},
        "8889/tcp": {}
    },
    "HostConfig": {
        "Binds": [
            "/etc/localtime:/etc/localtime:ro",
            "/etc/timezone:/etc/timezone:ro",
            "/home/dbc/0.3.7.3/dbc_repo/container:/home/dbc_utils:ro"
        ],
        "Devices": [],
        "VolumeDriver": "",
        "Mounts": [
            {
                "Target": "/proc/cpuinfo",
                "Source": "/var/lib/lxcfs/proc/cpuinfo",
                "Type": "bind",
                "Consistency": "consistent",
                "ReadOnly": false
            },
            {
                "Target": "/proc/diskstats",
                "Source": "/var/lib/lxcfs/proc/diskstats",
                "Type": "bind",
                "Consistency": "consistent",
                "ReadOnly": false
            },
            {
                "Target": "/proc/meminfo",
                "Source": "/var/lib/lxcfs/proc/meminfo",
                "Type": "bind",
                "Consistency": "consistent",
                "ReadOnly": false
            }
        ],
        "Links": [],
        "PortBindings": {
            "22/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "55413"
                }
            ],
            "8888/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "55424"
                }
            ],
            "8889/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "55425"
                }
            ]
        },
        "Privileged": true,
        "PublishAllPorts": false,
        "Memory": 26379740000,
        "MemorySwap": 52759480000,
        "CpuShares": 100,
        "DiskQuota": 150000000000,
        "ShmSize": 94489280512,
        "Runtime": "nvidia",
        "Ulimits": [
            {
                "Name": "memlock",
                "Hard": -1,
                "Soft": -1
            }
        ]
    }
	
}
```

**Comment by deepbraindeveloper** [comment] 2020-07-22 06:41
sbin/init   /home/dbc_utils/dbc_task.sh   ,This command cannot be executed properly

**Comment by thaJeztah** [comment] 2020-07-27 15:33
If the posted inspect output is your actual config, then you may have used the incorrect quotes for the entrypoint (GitHub is marking them as invalid JSON); make sure to use regular/straight quotes, not "curly quotes";

```json
"Entrypoint": ["/sbin/init"],
```

Instead of

```json
"Entrypoint": [“/sbin/init”],
```

Also if you set an entrypoint, then arguments passed in `docker run <image> <arguments>`, or set as `CMD` in the Dockerfile are passed as arguments for the entrypoint. In your case, the container's CMD is;

```json
"Cmd": ["/home/dbc_utils/dbc_task.sh", "", "QmW7xeDshhbJFMiQ1WgtnimUJTd3j3JdfyQdtbdoz9mS6n", "run.sh "],
```

(note that the last one also has a trailing space)


Those will be send as arguments to `/sbin/init`, so the container will be started with:

```bash
/sbin/init "/home/dbc_utils/dbc_task.sh" "" "QmW7xeDshhbJFMiQ1WgtnimUJTd3j3JdfyQdtbdoz9mS6n" "run.sh "
```


However, please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-07-27 15:33 UTC
