### ISSUE TITLE
ContentRootPath of hosting environment in Docker

### ISSUE THREAD

**Issue by Shameer-Ali** [docker/cli#3182] opened 2021-07-09 08:54 UTC
I am creating an ASP Core web Application with Linux docker enabled. I need to get the proper ContentRootPath from the hosting environment to process this further.

In normal ASP Web Application, the local path is returned as “D:\Sample\WebApplication1” whereas in Linux, it is returned as “/app”.

For this reason , I tried to change the working directory directly in application docker file but it doesn’t work. I have also tried to change the working directory directly in command prompt using the below command

“docker run -w /D:/sample/webapplication1/ -i -t linux pwd”

But this throws an error " Error response from daemon: pull access denied for linux, repository does not exist or may require ‘docker login’: denied: requested access to the resource is denied."

I have also tried login with port number in command prompt but it throws error like Error response from daemon: Get http://localhost:32788/v2/: EOF but the port is running in chrome.

Can anyone please suggest on how to modify the working directory of Docker and get the exact local path in Linux Docker application?

**Comment by thaJeztah** [comment] 2021-07-09 09:12
```
daemon: pull access denied for linux
```

This looks to be because there's no `linux:latest` image on your machine; is that the actual name of the image you're trying to run?


Also note that Linux does not use drive-letters, so the `/D:/sample/webapplication1/` will likely create a directory named literally that.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2021-07-09 09:12 UTC
Labels: kind/question
