### ISSUE TITLE
build: create non-existent WORKDIR with USER permissions

### ISSUE THREAD

**Issue by r10r** [docker/cli#3346] opened 2021-10-21 09:15 UTC
Hi there,

I stumbled over the fact that a non-existent WORKDIR is always created with `root:root` permissions.
I think it would be good if a non-existent WORKDIR is honours the current user like  the RUN command does.

e.g  this Dockerfile fails with `touch: foobar: Permission denied`

```Dockerfile
FROM docker.io/library/alpine:latest
RUN adduser -D http -h /home/http
USER http
RUN id
WORKDIR /home/http/public
RUN ls -ld $PWD
RUN touch foobar
```

while this one works fine

```Dockerfile
FROM docker.io/library/alpine:latest
RUN adduser -D http -h /home/http
USER http
RUN id
RUN mkdir /home/http/public
WORKDIR /home/http/public
RUN ls -ld $PWD
RUN touch foobar
```

> Docker version 20.10.3, build 48d30b5b32

**Comment by thaJeztah** [comment] 2021-11-02 11:30
Thanks for reporting; this issue is related to the builder, which runs on the daemon side, and looks like a duplicate of https://github.com/moby/moby/issues/36677

However, it looks like this issue has been fixed in BuildKit (the next generation builder) enabled (`DOCKER_BUILDKIT=1`); https://github.com/moby/buildkit/pull/1002


With your example Dockerfile;

```bash
DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain .

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile:
#1 transferring dockerfile: 186B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/library/alpine:latest
#3 DONE 0.0s

#4 [1/6] FROM docker.io/library/alpine:latest
#4 CACHED

#5 [2/6] RUN adduser -D http -h /home/http
#5 DONE 0.3s

#6 [3/6] RUN id
#6 0.295 uid=1000(http) gid=1000(http)
#6 DONE 0.3s

#7 [4/6] WORKDIR /home/http/public
#7 DONE 0.0s

#8 [5/6] RUN ls -ld $PWD
#8 0.319 drwxr-sr-x    2 http     http          4096 Nov  2 11:26 /home/http/public
#8 DONE 0.3s

#9 [6/6] RUN touch foobar
#9 DONE 0.3s

#10 exporting to image
#10 exporting layers 0.1s done
#10 writing image sha256:5002bde5e530ccf68b2e294a47981edb6cad72647e00535a3957cd02721e8b31
#10 writing image sha256:5002bde5e530ccf68b2e294a47981edb6cad72647e00535a3957cd02721e8b31 done
#10 DONE 0.1s
```


The classic (non-buildkit) build is currently in "maintenance" mode, with the intent to use BuildKit as a default (it's already the default on Docker Desktop), so I'm not sure this will also be fixed for the classic builder.

That said, let me close this ticket, as this is fixed with BuildKit, and a duplicate of https://github.com/moby/moby/issues/36677, but feel free to continue the conversation. (let me also comment on, and close that other issue)

**Closed by thaJeztah** 2021-11-02 11:30 UTC
Labels: area/builder, area/builder/classic-builder

**Comment by r10r** [comment] 2021-11-09 06:44
Hi @thaJeztah, I just want to confirm that it works as it should when using BuildKit. Thanks a lot for your explanation!
