### ISSUE TITLE
Volume prune & image prune should list ahead what is going to delete

### ISSUE THREAD

**Issue by Nassiel** [docker/cli#3742] opened 2022-08-18 14:33 UTC
### Description

Hi,

After my experience from last night where, while all my pods were running and working, I did a `docker volume prune` clicked on yes and remove all the volumes. I see it much more useful than you say yes to what you know is going to happen.

For instance, in `apt install python3-pip` I know what things are going to change, so when I say yes/no, I know what's going to change, but here you see the "all volumes not currently in use will b deleted..." but then, if for whatever reason the system fails (like in my case) and deleted too much, is already too late!

There is no undone, you just cry. So, I consider this would be a huge improvement.

**Comment by thaJeztah** [comment] 2022-08-21 12:08
Thanks for opening; this looks to be a duplicate of;

- https://github.com/moby/moby/issues/30623
- https://github.com/moby/moby/issues/39418

Let me close this ticket to prevent the conversation on those from diverging, but feel free to participate there.

**Closed by thaJeztah** 2022-08-21 12:08 UTC
Labels: kind/feature, status/0-triage
