### ISSUE TITLE
Invalid Volume Specification

### ISSUE THREAD

**Issue by Ingosmar89219** [docker/cli#240] opened 2017-06-26 02:28 UTC
```
osmarvirux@joelvirux MINGW64 ~
$ docker run --rm -v C:\Dev-Ops\scaling-AWS-docker-Rails rails:4 rails new --sk
ip-bundle dockerzon
docker: Error response from daemon: invalid volume spec "C:Dev-Opsscaling-AWS-do
cker-Rails": invalid volume specification: 'C:Dev-Opsscaling-AWS-docker-Rails':
invalid mount config for type "volume": invalid mount path: 'Dev-Opsscaling-AWS-
docker-Rails' mount path must be absolute.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

Im using WINDOWS 8.1

please help me :(

**Comment by dnephin** [comment] 2017-06-29 17:36
Please provide all the necessary version information: https://github.com/docker/cli/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by thaJeztah** [comment] 2017-06-29 20:46
Based on `"MINGW64"`, and the error-message;

    invalid volume specification: 'C:Dev-Opsscaling-AWS-docker-Rails'

You're using backslashes in your path, which are an escape character, thus `C:\foo` is being converted to `C:foo`, which is invalid.

Try double-escaping the backslashes (`C:\\foo\\bar`), or possibly forward-slashes (`/c/foo/bar`). This comment may also be helpful; https://github.com/moby/moby/issues/31370#issuecomment-282758977

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

I'm going to close this issue because this is not a bug, but feel free to continue the conversation 👍

**Closed by thaJeztah** 2017-06-29 20:46 UTC
Labels: status/more-info-needed

**Comment by westim** [comment] 2018-05-11 15:15
For posterity, I was getting a `Invalid Volume Specification` error during a tutorial and eventually figured out that I was running Windows Containers instead of Linux Containers (the instructor failed to mention this prerequisite). Switching to Linux Containers resolved my issue.
