### ISSUE TITLE
The error message is misleading in output window when using explicit ports for "Docker" settings in "launchSettings.json" file (Make sure sslPort sets incorrectly)

### ISSUE THREAD

**Issue by v-zhiyul** [docker/cli#2371] opened 2020-03-03 03:30 UTC
OS Version: Win10 1909 19H2
Dev16 Build: Visual Studio 2019 version 16.5 Preview 5
Workload: Azure Development
 
**Reproduce Steps:**
1. Create an ASP.NET Core Web Application with 'Docker Support' enabled (Linux/Windows Container).
2. After the project warms up successfully,  open the launchSettings.json file and use explicit ports(Make sure httpPort sets correctly)(E.g "httpPort": 52000  "sslPort": 520001).​
3. Rewarm up and observe whether the error message is clear in output window or not.
 
**Expect:**
The error message is clear in output window.

**Actual:**
The error message is misleading in output window.
![Error](https://user-images.githubusercontent.com/50071077/75740282-319fc380-5d42-11ea-9a75-268911bd5507.PNG)

**Comment by thaJeztah** [comment] 2020-06-15 14:26
The problem looks to be that the second port that's specified (`-p 520001:443`) is out of range (maximum port number is `65536`), but it prints the first port-mapping as error. 🤔

**Comment by thaJeztah** [comment] 2020-06-15 14:31
Looks like this is a duplicate of https://github.com/docker/cli/issues/1962, and fixed on master through https://github.com/docker/cli/pull/2251

```
docker create -p 52000:80 -p 520001:443 busybox
docker: Invalid hostPort: 520001.
See 'docker create --help'.
```

This will be in the upcoming 20.x release of Docker, so let me close this one

**Closed by thaJeztah** 2020-06-15 14:31 UTC
Labels: kind/bug
