### ISSUE TITLE
The issue of Docker always timeout when pulling images

### ISSUE THREAD

**Issue by Handikang** [docker/cli#5166] opened 2024-06-18 11:34 UTC
### Description

Recently, I found that pulling some images on many of my devices has timed out. I tried to modify Docker/daemon.json and added several image sources, but to no avail
![image](https://github.com/docker/cli/assets/42713276/a4eee358-f1af-4b93-8481-84b7a746ae91)

### Reproduce

docker pull secretflow/teeapps-sgx-ubuntu22.04:latest

Time out occurred

### Expected behavior

Give me a reasonable way to solve this timeout. I have modified DNS and the image source, and I am confused why I still pull the image timeout

### docker version

```bash
Client:
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:39:56 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:44:54 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:        
 runc:
  Version:          1.1.12-0ubuntu2~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 6
  Running: 6
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.15.0-107-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.79GiB
 Name: idata08
 ID: G65L:QYMY:MLAK:X5DN:VEPF:DY7Y:YLOU:RT42:QR4W:64RZ:LYOG:DW7Q
 Docker Root Dir: /home/dockerdata
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  10.100.2.1:53
  172.16.16.40:5000
  127.0.0.0/8
 Registry Mirrors:
  https://xq0h056l.mirror.aliyuncs.com/
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by akerouanton** [comment] 2024-06-18 15:47
Hi,

Looking at your profile, it seems you live in China. We had multiple chinese users reporting the same sort of issues in the past few weeks.

If you look at the whois for `104.244.43.182`, you'll see that the IP address in the error message isn't owned by Docker or Cloudflare:

```console
$ whois 104.244.43.182
# whois.arin.net

NetRange:       104.244.40.0 - 104.244.47.255
CIDR:           104.244.40.0/21
NetName:        TWITTER-NETWORK
NetHandle:      NET-104-244-40-0-1
Parent:         NET104 (NET-104-0-0-0-0)
NetType:        Direct Allocation
OriginAS:       AS13414
Organization:   Twitter Inc. (TWITT)
RegDate:        2014-12-08
Updated:        2020-06-28
Ref:            https://rdap.arin.net/registry/ip/104.244.40.0
```

Unfortunately, there's nothing we can do as the issue is with your ISP / DNS provider. You should talk to them if you want that situation to get sorted. Alternatively, you can try to use another DNS server. You can take a look here, if you want to check if your (new) DNS servers are returning the right records: https://dnschecker.org/#A/production.cloudflare.docker.com.

As there's nothing actionable on our side, let me close this ticket, but feel free to continue the discussion.

**Closed by akerouanton** 2024-06-18 15:47 UTC
Labels: kind/bug, status/0-triage

**Comment by Handikang** [comment] 2024-06-18 16:47
Thank you for your reply and have a happy life




---Original---
From: "Albin ***@***.***&gt;
Date: Tue, Jun 18, 2024 23:47 PM
To: ***@***.***&gt;;
Cc: "Han ***@***.******@***.***&gt;;
Subject: Re: [docker/cli] The issue of Docker always timeout when pullingimages (Issue #5166)




 
Hi,
 
Looking at your profile, it seems you live in China. We had multiple chinese users reporting the same sort of issues in the past few weeks.
 
If you look at the whois for 104.244.43.182, you'll see that the IP address in the error message isn't owned by Docker or Cloudflare:
 $ whois 104.244.43.182 # whois.arin.net NetRange:       104.244.40.0 - 104.244.47.255 CIDR:           104.244.40.0/21 NetName:        TWITTER-NETWORK NetHandle:      NET-104-244-40-0-1 Parent:         NET104 (NET-104-0-0-0-0) NetType:        Direct Allocation OriginAS:       AS13414 Organization:   Twitter Inc. (TWITT) RegDate:        2014-12-08 Updated:        2020-06-28 Ref:            https://rdap.arin.net/registry/ip/104.244.40.0
 
Unfortunately, there's nothing we can do as the issue is with your ISP / DNS provider. You should talk to them if you want that situation to get sorted. Alternatively, you can try to use another DNS server. You can take a look here, if you want to check if your (new) DNS servers are returning the right records: https://dnschecker.org/#A/production.cloudflare.docker.com.
 
As there's nothing actionable on our side, let me close this ticket, but feel free to continue the discussion.
