### ISSUE TITLE
docker memory

### ISSUE THREAD

**Issue by wangqingpen** [docker/cli#4813] opened 2024-01-23 03:27 UTC
### Description

I use go to call c to get data, I can run for a long time when I use binaries, but there will always be memory problems when I use docker, for example：

```
fatal: morestack on g0
SIGSEGV: segmentation violation
PC=0x472894 m=8 sigcode=1.
```

### Reproduce

docker run

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:13 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:52:13 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment] 2024-01-23 10:11
Do you have steps to reproduce? With the current information, there's not enough to investigate. If this is the process inside the container, then this is not related to the CLI (which is only a client for the docker daemon), and may be better suited for a discussion in https://github.com/moby/moby/discussions



That said; I found quite some matches on Google for the `fatal: morestack on g0` error. Some were related to Go (using CGO); 

- https://github.com/golang/go/issues/62440
- https://github.com/golang/go/issues/62130


I'll close this ticket because of the above, but feel free to continue the conversation.

**Closed by thaJeztah** 2024-01-23 10:11 UTC
Labels: kind/bug, status/0-triage, status/more-info-needed, version/24.0
