### ISSUE TITLE
exec does not (always) forward signals to container process

### ISSUE THREAD

**Issue by reitzig** [docker/cli#2607] opened 2020-06-29 13:40 UTC
As a CLI user, I want container processes to be interrupted if I interrupt their attached "parent" `docker exec` from the calling shell so I don't leave rogue processes around.

**Steps to reproduce the issue:**

```bash
# Given
docker run -d --rm --name mwe ubuntu sleep 1000

# When
docker exec mwe tail -f /dev/null 
# Ctrl+C

# Then
[[ $(docker exec mwe ps -e | grep -c tail) -eq 0 ]]
```

**Describe the results you received:**

failure ( `echo $?` --> `1` )

**Describe the results you expected:**

success ( `echo $?` --> `0` )

**Additional information:**

 - Reproduces with either `-i` or `-t`.
 - Does _not_ reproduce with `-it`.
 - Interestingly, does not reproduce when run like so:

   ```bash
   docker exec mwe tail -f /dev/null &
   kill -s SIGINT $!
   ```
 - But _does_ reproduce when sending the signal from Go via `cmd.Process.Signal` (see [here](https://github.com/reitzig/container-do/blob/e6770fde94deb35902b497a9d0b47610b5c511f2/cmd/container-do/runner_docker.go#L51)) (unless `-t` is passed to `docker exec`).
 - While `-it` is a workaround in some situations, it is not always possible (build servers, tests, ...).

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 17
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-46-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.26GiB
 Name: tailchaser
 ID: NYXA:VM6T:PP6Z:LY57:2D2O:CZGZ:2MXO:SW5S:6HKV:DDWJ:2XLA:QD3P
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by aeruder** [comment] 2020-07-25 00:24
I can't even tell if this is really related to reitzig/container-do#6 but as a workaround I've found that simply using `com.docker.cli` instead of `docker` works fine - seems like the issue is between `docker` and `com.docker.cli`.  

```
Client:
 Debug Mode: false

Server:
 Containers: 23
  Running: 0
  Paused: 0
  Stopped: 23
 Images: 719
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.848GiB
 Name: docker-desktop
 ID: E2XT:3NCM:FAF3:2FLZ:K42B:J5QT:VUWI:HYCC:RKUG:25FB:ZHDI:O6RT
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 63
  Goroutines: 50
  System Time: 2020-07-25T00:23:59.3988063Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by reitzig** [comment] 2021-02-01 14:02
Still reproduces.

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by thaJeztah** [comment] 2021-02-15 17:40
This looks to be a duplicate of https://github.com/moby/moby/issues/9098

https://github.com/docker/cli/pull/1841 fixed this situation for `docker run`, but `docker exec` needs additional changes (some outlined in https://github.com/moby/moby/issues/9098)

Let me close this one to prevent the conversation from diverging.

**Closed by thaJeztah** 2021-02-15 17:40 UTC
